### ISSUE TITLE
Traceback error on Auth

### ISSUE THREAD

**Issue by thepspgamer** [DIGITALCRIMINAL/OnlyFans#1003]
Hi
Since older versions of the tool have stopped working, I updated to 6.4.4.
After doing all the usual setup steps, I am now getting this error on Auth.

Traceback (most recent call last):
  File "D:\OnlyFans-v.6.4.4\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans-v.6.4.4\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "D:\OnlyFans-v.6.4.4\modules\onlyfans.py", line 89, in account_setup
    authed = api.login()
  File "D:\OnlyFans-v.6.4.4\apis\onlyfans\onlyfans.py", line 609, in login
    print(f"Welcome {me_api.name} | {me_api.username}")
AttributeError: 'dict' object has no attribute 'name'

I have checked and confirmed all my details are as they should be, and I'm stumped. (Using Chrome)

Any ideas? Thanks in advance

**Comment by DIGITALCRIMINAL** [comment]
OnlyFans error.
