### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Derikflo** [DIGITALCRIMINAL/OnlyFans#1009]
Hi, I am using the latest version of the script v6.4.4
This error appears on some free OF profiles such as:
sabrinanichole
christinebarette

As far as I understand, our admin will help fix this error.

P/S
I think that the topic about beer should be renamed to Rolls Royce for our Admin. I think he deserves it. :)

Scrape Processing
Name: sabrinanichole
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "D:\OnlyFans Kachalka\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans Kachalka\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 632, in process_names
    result = module.start_datascraper(
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 713, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 1066, in media_scraper
    file_path = main_helper.reformat(
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 324, in reformat
    text = clean_text(text)
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 89, in clean_text
    string = string.replace(
AttributeError: 'NoneType' object has no attribute 'replace'

*******************************************************************************************

Scrape Processing
Name: christinebarette
Type: Profile
  2%|[32m█▍                                                                            [0m| 4.10k/218k [00:00<00:21, 9 13%|[32m██████████▎                                                                   [0m| 28.7k/218k [00:00<00:03, 6 92%|[32m█████████████████████████████████████████████████████████████████████████▊      [0m| 201k/218k [00:00<00:00, 100%|[32m████████████████████████████████████████████████████████████████████████████████[0m| 258k/258k [00:00<00:00, 273kB/s][0m
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "D:\OnlyFans Kachalka\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans Kachalka\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 632, in process_names
    result = module.start_datascraper(
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 713, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\OnlyFans Kachalka\modules\onlyfans.py", line 1066, in media_scraper
    file_path = main_helper.reformat(
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 324, in reformat
    text = clean_text(text)
  File "D:\OnlyFans Kachalka\helpers\main_helper.py", line 89, in clean_text
    string = string.replace(
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by thomas-ed** [comment]
I'm dealing with the same problem as you. Using OnlyFans 6.4.4, Python 64bit 3.9.4, W10 64bit.
Tried three times and everytime error occurs on same user (youngcharleyy). Also tried to change files/folders from Read-only -> not Read-only, but not any help for this problem

Scrape Processing
Name: youngcharleyy
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "O:\OnlyFans\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "O:\OnlyFans\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "O:\OnlyFans\helpers\main_helper.py", line 630, in process_names
    result = module.start_datascraper(
  File "O:\OnlyFans\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "O:\OnlyFans\modules\onlyfans.py", line 713, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\Omistaja\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Omistaja\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Omistaja\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Omistaja\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "O:\OnlyFans\modules\onlyfans.py", line 1066, in media_scraper
    file_path = main_helper.reformat(
  File "O:\OnlyFans\helpers\main_helper.py", line 324, in reformat
    text = clean_text(text)
  File "O:\OnlyFans\helpers\main_helper.py", line 89, in clean_text
    string = string.replace(
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by DIGITALCRIMINAL** [comment]
Has this been fixed?

**Comment by PsychoSid** [comment]
I am now getting this today from "mollynextdoor" which is free.

```
  File "Misc/OnlyFans/helpers/main_helper.py", line 648, in reformat
    text = clean_text(text)
  File "Misc/OnlyFans/helpers/main_helper.py", line 104, in clean_text
    string = string.replace(m, " ").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
```
