### ISSUE TITLE
attribute error, have I done something wrong?

### ISSUE THREAD

**Issue by audi4444player** [DIGITALCRIMINAL/OnlyFans#1021]
hello, I followed the instructions and filled in my authentication information but i'm getting an error that I don't know what to do with, here is what I see, have I done something wrong? Thank you for any help.

Site: 0 = onlyfans | x = Exit
0
Session IP: my ip

Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Traceback (most recent call last):
  File "C:\Files\[Holding]\Onlyfans Downloader\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Files\[Holding]\Onlyfans Downloader\OnlyFans-master\datascraper\main_datascraper.py", line 79, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "C:\Files\[Holding]\Onlyfans Downloader\OnlyFans-master\modules\onlyfans.py", line 89, in account_setup
    authed = api.login()
  File "C:\Files\[Holding]\Onlyfans Downloader\OnlyFans-master\apis\onlyfans\onlyfans.py", line 609, in login
    print(f"Welcome {me_api.name} | {me_api.username}")
AttributeError: 'dict' object has no attribute 'name'

**Comment by DIGITALCRIMINAL** [comment]
Nope, it's my fault.
