### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINAL/OnlyFans#1022]
Ok I guess this would be a new issue since I cant find any resolution on Github and every search online for this message is just giving me scattered details and people saying something about the script but noone is giving any insight on what I need to do to solve the problem or what is actually wrong.  I will admit I am not a computer guru like alot of you guys on here so I probably need things broken down into simpler terms. But let me explain the issue. Like a ton of people the scraper I was using for OF went dead last week so after searching this repository I saw that maybe I should install the latest version of Python as well as the latest scraper. I did both and moved the files from the latest scraper to the version that I was already using (5.4).  I updated the info on the JSON file and I was able to install each item that it said I needed via pip install ........ Until I got to this message.  Any instructions from this point would be helpful. Thank you guys in advance.

**Comment by ProjektPremium** [comment]
Can you post the exact error that you're getting?

**Comment by Daironman78** [comment]
C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4>python start_ofd.py
LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\.settings\config_backup.json)
Traceback (most recent call last):
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\helpers\main_helper.py", line 494, in get_config
    json_config, string = make_settings.fix(json_config)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\make_settings.py", line 104, in fix
    c = x.check_unique()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\prepare_metadata.py", line 321, in check_unique
    value = os.path.normpath(value)
  File "C:\Users\Tony_\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Daironman78** [comment]
> 
> 
> Can you post the exact error that you're getting?

C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4>python start_ofd.py
LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\.settings\config_backup.json)
Traceback (most recent call last):
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\helpers\main_helper.py", line 494, in get_config
    json_config, string = make_settings.fix(json_config)
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\make_settings.py", line 104, in fix
    c = x.check_unique()
  File "C:\Users\Tony_\Downloads\OnlyFans-5.4\OnlyFans-5.4\classes\prepare_metadata.py", line 321, in check_unique
    value = os.path.normpath(value)
  File "C:\Users\Tony_\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
