### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by monokin1114** [DIGITALCRIMINAL/OnlyFans#1034]
Was working fine on my old pc but doesnt like my new one. I am getting this error. I have no clue why

Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 14, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 11, in <module>
    import modules.onlyfans as m_onlyfans
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1092
    if found_medias:
IndentationError: expected an indented block

**Comment by nappyapp** [comment]
Are you using the latest commit?

**Comment by monokin1114** [comment]
Traceback (most recent call last):
  File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "F:\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "F:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 5, in <module>
    from sqlalchemy.ext.declarative import api
ModuleNotFoundError: No module named 'sqlalchemy'

is the issue I have on the newest commit but that module is installed. I made sure I installed it

**Comment by nappyapp** [comment]
Did you install it for python 2 or python 3? Pip vs pip3 makes a difference

**Comment by nappyapp** [comment]
Run this in the script main folder:

`python3 -m pip install -r requirements.txt"

**Comment by monokin1114** [comment]
Tried that and I am still getting that same error on the newest commit

**Comment by nappyapp** [comment]
Make sure it's running with the latest Python version the script needs, I
forget which exactly but I think 3.9? You could try uninstalling all python
except that version. Or call the same command as before but with python3.9
instead of python3. If it's not finding the import I'm guessing the imports
got installed for the wrong version

**Comment by drobb0690** [comment]
im getting the same error and ive tried pip3, python3, and everything else suggested.  even updated my python install to 3.9.4 which is latest, even though i was on 3.9 already.  

Traceback (most recent call last):
  File "G:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "G:\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "G:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 5, in <module>
    from sqlalchemy.ext.declarative import api
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by drobb0690** [comment]
Running pip3 install sqlalchemy i get 

Requirement already satisfied: sqlalchemy in c:\python3\lib\site-packages (1.3.23)

and running python3 start_ofd.py yields

Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Python3\lib\site.py", line 73, in <module>
    import os
  File "C:\Python3\lib\os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "C:\Python3\lib\_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
