### ISSUE TITLE
Error after it scrapes images and videos

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#106]
Traceback (most recent call last):
  File "d:\***********\OnlyFans-master\StartDatascraper.py", line 114, in <module>
    x.download_media(*arg)
  File "d:\************\OnlyFans-master\modules\onlyfans.py", line 342, in download_media
    media_set, [session], [directory], [username]))
  File "C:\Users\*******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\*********\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\********\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\**********\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "d:\**********\Desktop\OnlyFans-master\modules\onlyfans.py", line 326, in download
    with open(download_path, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'd:\\*********\\Desktop\\OnlyFans-master/sites//onlyfans/*******/Stories/Images/1620x2160_2704726b9f61a1c87ab635c9c2ad38279145825e08e3714ff69.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvOFwvODlcLzg5ZDA5ZWFkNWI2MzcwMGJjZTRjMzVjOTJjMTI3MzFiXC8xNjIweDIxNjBfMjcwNDcyNmI5ZjY.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvOFwvODlcLzg5ZDA5ZWFkNWI2MzcwMGJjZTRjMzVjOTJjMTI3MzFiXC8xNjIweDIxNjBfMjcwNDcyNmI5ZjYxYTFjODdhYjYzNWM5YzJhZDM4Mjc5MTQ1ODI1ZTA4ZTM3MTRmZjY5LmpwZyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU3Nzc1MzI0Nn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiI5MS4yMDcuMTc1LjE5N1wvMzIifX19XX0_&Signature=hBuUiw~Ao-~nXblSinBX-tWJ69SKNaM65N5KL34qybaee77~XNcr9TGFH7gSA2A5svuHGyU7E-6c7UuDbDmYeOwuGCAuflTte1BZgP2ExQgNeulHEGSCR2BRYJXBkeInea21YFGfgMFGeyqIu8lSvPodTXt57V7q0DD1cL0E4oB3py~qr0TjpQNmuCdFDvxYxTVQwX7bBeYdQroQz0jq~yTpzAGcczIYvOGhghY1YjnTqWONxMjKoBXj0DjJjC3BJg5JFKoFGO90j0c-Ub81vIWfuO07Ec1sm6eTZwGbRqsowJkU3JPU-WbnVC9EnU5uoUNwQteX8o2AB-NpQ-16gg__&Key-Pair-Id=APKAJKLR6VB3PTZVDEBA'

**Comment by DIGITALCRIMINAL** [comment]
Have you downloaded the latest release?

**Comment by elwoodflame** [comment]
I believe I have but I will retry.

**Comment by elwoodflame** [comment]
That was it. I ad updated 3 days ago and didnt catch that there was a update.
