### ISSUE TITLE
Crashes for some models - KeyError: 'media'

### ISSUE THREAD

**Issue by tocking** [DIGITALCRIMINAL/OnlyFans#1068]
Crashes for some (not all) OF models with the following error:

Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 630, in process_names
    result = module.start_datascraper(
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 714, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 976, in media_scraper
    for media in media_api["media"]:
KeyError: 'media'

**Comment by DIGITALCRIMINAL** [comment]
What version are you using

**Comment by tocking** [comment]
Latest version, freshly downloaded two days ago.

**Comment by DIGITALCRIMINAL** [comment]
What's the model's name

**Comment by tocking** [comment]
rhoneeandkhoa
paxclusive

**Comment by tocking** [comment]
Still getting this error on the latest commit.  Jut tried again for paxclusive:

Scrape Processing
Name: paxclusive
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
Scrape Attempt: 1/100
Found: Archived_posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 629, in process_names
    result = module.start_datascraper(
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 156, in start_datascraper
    results = prepare_scraper(
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 709, in prepare_scraper
    unrefined_result = pool.starmap(media_scraper, product(
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 976, in media_scraper
    for media in media_api["media"]:
KeyError: 'media'

**Comment by DIGITALCRIMINAL** [comment]
Ahh interesting. If you check the API response on the website for that post, you may find a key that's related to report ed posts. Maybe there's a "isReported" book.

**Comment by tocking** [comment]
Any pointers for how I would go about finding this info easily?  I'm fine on the Python side of things, but the networking side is a bit out of my scope of knowledge...

**Comment by DIGITALCRIMINAL** [comment]
Ahh thank you, I'll be sure to add that to script. I gotta fix the script again...
