### ISSUE TITLE
Various errors coming up today...

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINAL/OnlyFans#1086]
having this issue...

> Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Opening Browser
Traceback (most recent call last):
  File "B:\OnlyFans-6.4.3\OF-Extract\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "B:\OnlyFans-6.4.3\OF-Extract\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "B:\OnlyFans-6.4.3\OF-Extract\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "B:\OnlyFans-6.4.3\OF-Extract\extras\OFLogin\start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'

worked fine until today.

**Comment by Luke-L** [comment]
nvm it seems you are working on a fix. keep up the great work, much appreciated.
#1078
