### ISSUE TITLE
macOS: OSError: [Errno 30] Read-only file system: '/sites/'

### ISSUE THREAD

**Issue by josephlopez86** [DIGITALCRIMINAL/OnlyFans#110]
Hi,

As commented macOS needs to use pip3 and python3, but still get this (even when running as sudo permissions)...

Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "./StartDatascraper.py", line 109, in <module>
    result = x.start_datascraper(
  File "/Users/test/Desktop/OnlyFans-master/modules/onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "/Users/test/Desktop/OnlyFans-master/modules/onlyfans.py", line 298, in media_scraper
    os.makedirs(directory, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/sites/'

**Comment by DIGITALCRIMINAL** [comment]
Set a directory path in the config

**Comment by josephlopez86** [comment]
> Set a directory path in the config

thank you

**Comment by DIGITALCRIMINAL** [comment]
Installed Linux and I finally fixed this.
