### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by leightonstarwalt** [DIGITALCRIMINAL/OnlyFans#1123]
Had just pulled the latest data to get around that 'please refresh' problem..
After getting the new files in place, ran through the requirements install, and all that good stuff.

Started the script and was greeted by this error:

Traceback (most recent call last):
  File "/mnt/nasprv/onlyfans/OnlyFans/start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/mnt/nasprv/onlyfans/OnlyFans/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/mnt/nasprv/onlyfans/OnlyFans/helpers/main_helper.py", line 1, in <module>
    from apis.onlyfans import onlyfans as OnlyFans
  File "/mnt/nasprv/onlyfans/OnlyFans/apis/onlyfans/onlyfans.py", line 9, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

I did double check to make sure that dateutil was installed by running `pip3 install python-dateutil` 
but came back saying it was already installed and up-to-date.

**Comment by leightonstarwalt** [comment]
I got it figured out.

I ended up having to recreate the `venv` environment and re-install requirements.
