### ISSUE TITLE
Invalid escape?

### ISSUE THREAD

**Issue by cabalinan** [DIGITALCRIMINAL/OnlyFans#113]
Traceback (most recent call last):
  File "StartDatascraper.py", line 1, in <module>
    import modules.onlyfans as onlyfans
  File "C:\Users\Joshua\Downloads\OnlyFans-master\modules\onlyfans.py", line 2, in <module>
    from modules.helpers import *
  File "C:\Users\Joshua\Downloads\OnlyFans-master\modules\helpers.py", line 13, in <module>
    json_config = json.load(open('config.json'))
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 37 column 25 (char 995)

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by cabalinan** [comment]
PS C:\Users\Joshua\Downloads\OnlyFans-master> python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\Joshua\Downloads\OnlyFans-master> python StartDatascraper.py
Traceback (most recent call last):
  File "StartDatascraper.py", line 1, in <module>
    import modules.onlyfans as onlyfans
  File "C:\Users\Joshua\Downloads\OnlyFans-master\modules\onlyfans.py", line 2, in <module>
    from modules.helpers import *
  File "C:\Users\Joshua\Downloads\OnlyFans-master\modules\helpers.py", line 13, in <module>
    json_config = json.load(open('config.json'))
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Joshua\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 20 column 25 (char 587)

**Comment by DIGITALCRIMINAL** [comment]
Something is wrong with your config file. I'd download it again and add in all the things
