### ISSUE TITLE
Module.start_datascraper and 'media' errors.

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINAL/OnlyFans#1137]
I'm using the latest version 7.1, extracted to the same place as my old version with settings. ofc i told it to replace all the old files with current versions. Oddly enough, it extracted 3 or 4 models just fine before throwing this error at me.

> Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "B:\OnlyFans-6.4.3\OF-Extract\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "B:\OnlyFans-6.4.3\OF-Extract\datascraper\main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "B:\OnlyFans-6.4.3\OF-Extract\helpers\main_helper.py", line 629, in process_names
    result = module.start_datascraper(
  File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 154, in start_datascraper
    results = prepare_scraper(
  File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 711, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "B:\OnlyFans-6.4.3\OF-Extract\modules\onlyfans.py", line 973, in media_scraper
    for media in media_api["media"]:
KeyError: 'media'

**Comment by Gixxa** [comment]
Delete everything expect ".sites", ".profiles" and ".settings". Depending on the version you had before you might have cached parts of the old version which the new version will not create new but use the old ones.

Also you are using 6.4.3 by the looks of it. Use the newest master.
