### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by nkycldn** [DIGITALCRIMINAL/OnlyFans#117]
> test@The-MacBook-Pro-Don ~ % python3 /Users/test/Downloads/OnlyFans-master\ 6/StartDatascraper.py 
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Welcome 
Names: 0 = All | 1 = user1 | 2 = user2 | 3 = user3 | 4 = user4
4
Scrape Processing
Name: user
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "/Users/test/Downloads/OnlyFans-master 6/StartDatascraper.py", line 106, in <module>
    result = x.start_datascraper(
  File "/Users/test/Downloads/OnlyFans-master 6/modules/onlyfans.py", line 55, in start_datascraper
    results = media_scraper(
  File "/Users/test/Downloads/OnlyFans-master 6/modules/onlyfans.py", line 303, in media_scraper
    os.makedirs(location_directory, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '//onlyfans'

Any reasons for this issue? I installed all requirements...

**Comment by nkycldn** [comment]
found a solution, created a folder outside of the script directory and changed the directory path in the config and it works fine now.
