### ISSUE TITLE
SQLite 3 Error. Database is Locked

### ISSUE THREAD

**Issue by iamfreaky** [DIGITALCRIMINAL/OnlyFans#1181]
```
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 107, in start_datascraper
    names = main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 629, in process_names
    result = module.start_datascraper(
  File "/usr/src/app/modules/onlyfans.py", line 154, in start_datascraper
    results = prepare_scraper(
  File "/usr/src/app/modules/onlyfans.py", line 725, in prepare_scraper
    w = process_metadata(metadata_path, formatted_directories, new_metadata,
  File "/usr/src/app/modules/onlyfans.py", line 585, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "/usr/src/app/helpers/main_helper.py", line 230, in export_sqlite
    db_helper.run_migrations(alembic_location, database_path, api)
  File "/usr/src/app/helpers/db_helper.py", line 46, in run_migrations
    x = command.upgrade(alembic_cfg, 'head')
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/app/database/databases/posts/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/usr/src/app/database/databases/posts/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 545, in run_migrations
    self._ensure_version_table()
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 486, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 928, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)
```

I Hope you can help me. This accours if i write to a network storage. I tried the v.7.1 release and the master branch. Im Using Linux with the Docker Option.

**Comment by DIGITALCRIMINAL** [comment]
I had this problem as well. I was using rclone. I haven't found a way past it unfortunately :(

**Comment by rs516a1** [comment]
SQLite is known to not work nicely with network storage (NFS) and locks. You can have the program store the metadata/databases on local storage and then backup to the network storage.

**Comment by Rekconning** [comment]
add `nolock` parameter into your cifs mount.

**Comment by iamfreaky** [comment]
@Rekconning Will try that and will report later.
