### ISSUE TITLE
Getting Access Denied on login again

### ISSUE THREAD

**Issue by DaAanK** [DIGITALCRIMINAL/OnlyFans#1192]
Hi All,

using the latest master commit which i downloaded approx 15 mins ago - can't get the scraper to auth.

doesn't matter if i try with the old sess method or user/pass or having it all in auth.json

current output of powershell is

Choose Profile
Names: Username = username  | 0 = All | 1 = u6496869
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Traceback (most recent call last):
  File "R:\OnlyFans-6.1.2\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "R:\OnlyFans-6.1.2\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "R:\OnlyFans-6.1.2\modules\onlyfans.py", line 80, in account_setup
    authed = auth.login()
  File "R:\OnlyFans-6.1.2\apis\onlyfans\onlyfans.py", line 585, in login
    self.get_authed()
  File "R:\OnlyFans-6.1.2\apis\onlyfans\onlyfans.py", line 634, in get_authed
    r = self.session_manager.json_request(
  File "R:\OnlyFans-6.1.2\apis\api_helper.py", line 121, in json_request
    r = session.request(
  File "C:\Program Files\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

and then it boots me out of OF in my browser (chrome)

any idea's?

cheers

**Comment by DaAanK** [comment]
also - i've never seend auth_hash or x_bc in the cookies section to copy over - dunno if that's relevant or not

**Comment by ambersydney333** [comment]
i posted this like 1h ago in the previous section lol i thought im the only one, no one answered :/

**Comment by headphonia** [comment]
works for me on the latest commit.

**Comment by ElusiveZatchmo** [comment]
Not working for me on the latest commit either :(

**Comment by ElusiveZatchmo** [comment]
After updating to latest commit and resetting auth.json I got it to work

**Comment by Macmasteri** [comment]
I also got this error with the latest commit.

Has anything changed what you need to fill into the auth file?

I fill: auth id, session, x-bc and user agent.

**Comment by DaAanK** [comment]
i managed to fix it - i found the X_BC setting in the headers section of the F12 diagnostic thing in chrome - see image

![Untitled](https://user-images.githubusercontent.com/48913616/118387953-54ea2200-b619-11eb-8166-930f3e253e9f.jpg)

not sure if it'll help anyone else here - but getting the latest commit from 9 hours ago (time now for me is 0736 UK time) and adding x_bc to my auth worked

**Comment by DIGITALCRIMINAL** [comment]
Change auto_media_choice to 0 in the config. The alphabet characters don't work anymore
