### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by neuri4848** [DIGITALCRIMINAL/OnlyFans#1204]
File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = main_helper.process_names(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 631, in process_names
    result = module.start_datascraper(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 144, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 639, in prepare_scraper
    profile_scraper(authed, site_name, api_type, username,
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 250, in profile_scraper
    d_session = download_session()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
    cls.monitor = TMonitor(cls, cls.monitor_interval)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
    getattr(sys, 'setcheckinterval'))(100)
AttributeError: module 'sys' has no attribute 'setcheckinterval'

**Comment by BababyCua** [comment]
Yeah i got error too 

C:\Users\user\Desktop\OnlyFans-master\OnlyFans-master>python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\OnlyFans-master\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\user\Desktop\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\user\Desktop\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 2, in <module>
    from apis.onlyfans import onlyfans as OnlyFans
  File "C:\Users\user\Desktop\OnlyFans-master\OnlyFans-master\apis\onlyfans\onlyfans.py", line 9, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

**Comment by BababyCua** [comment]
Okey i don't know why but i have to do pip install -r requirements.txt again but now it's working so you should try do it too

**Comment by neuri4848** [comment]
doesnt work for me lol, the weird thing is that it happened to me mid-scrape

**Comment by ImpalaPUA** [comment]
You just have to do pip install -r requirements.txt again

**Comment by neuri4848** [comment]
Doesn't work. I even deleted everything and started all over again. I think it was a change on the site

**Comment by ImpalaPUA** [comment]
The new version should update your config

**Comment by neuri4848** [comment]
New or old it doesn't work. Ive both. Same error every time

**Comment by ImpalaPUA** [comment]
Not sure what to tell you, all the new version needs is updated requirements which can be done via 

pip install -r requirements.txt

**Comment by ImpalaPUA** [comment]
Also you have 2 folders inside each other

OnlyFans-master\OnlyFans-master\ 

Might want to check this out

**Comment by neuri4848** [comment]
tried it,,  wont work

**Comment by Macmasteri** [comment]
Got this errror right now. Have worked fine earlier. But this account has many subs on it and maybe that could be the case?
