### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by Septan** [DIGITALCRIMINAL/OnlyFans#1221]
Also try the latest commit same issue. 
Python 3.9.2
I also uninstall all requirements and reinstalled.

```Traceback (most recent call last):
  File "D:\github\OnlyFans-7.2\start_ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "D:\github\OnlyFans-7.2\datascraper\main_datascraper.py", line 69, in start_datascraper
    auths = choose_option(
  File "D:\github\OnlyFans-7.2\helpers\main_helper.py", line 568, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by deadcode0815** [comment]
you have to put quotes around the option like "0" for example: "auto_profile_choice": "0"
