### ISSUE TITLE
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm'

### ISSUE THREAD

**Issue by ozone1979** [DIGITALCRIMINAL/OnlyFans#1231]
Traceback (most recent call last):
  File "{.....}\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "{.....}\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "{.....}\helpers\main_helper.py", line 8, in <module>
    from sqlalchemy.orm import declarative_base
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (C:\Users\{...}\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\__init__.py)

**Comment by anon-ion** [comment]
You need to do ```pip install -r requirements.txt```

**Comment by ozone1979** [comment]
Much thanks.
