### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by otisrush** [DIGITALCRIMINAL/OnlyFans#1233]
Traceback (most recent call last):
  File "D:\...\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "D:\...\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "D:\...\OnlyFans-master\helpers\main_helper.py", line 363
    filtered_text = utf8_byte_truncate(text,text_length).decode('utf8')
                                                                       ^
IndentationError: unindent does not match any outer indentation level

Running the latest commit

**Comment by DIGITALCRIMINAL** [comment]
Fixed
