### ISSUE TITLE
Stopped working (os error 10061)

### ISSUE THREAD

**Issue by Nodrdickan** [DIGITALCRIMINAL/OnlyFans#1248]
Stopped working:
```
Session IP: 83.221.73.28

Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Please refresh the page
Opening Browser
Traceback (most recent call last):
  File "C:\Users\ivand\start_ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "C:\Users\ivand\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "C:\Users\ivand\modules\onlyfans.py", line 106, in account_setup
    cookies = oflogin.login(auth, domain, proxy)
  File "C:\Users\ivand\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "C:\Users\ivand\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ivand\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (os error 10061)
```

**Comment by ProjektPremium** [comment]
Did you run the requirements.txt?

**Comment by Nodrdickan** [comment]
> Did you run the requirements.txt?

Everything worked fine yesterday.
Doesn't work today.
Maybe because of the changes on OnlyFans?

**Comment by ProjektPremium** [comment]
I don't think the changes to the OnlyFans layout would bring up those kind of errors.

**Comment by Nodrdickan** [comment]
> I don't think the changes to the OnlyFans layout would bring up those kind of errors.

And what then could be the problem if everything worked fine yesterday?

**Comment by LunarPenguin** [comment]
Its a selenium error, so if the OF site changed the browser login may no longer work if the field(s) it uses have changed. (This is an educated guess from my personal experience with selenium, i am not familiar with the browser login code)

**Comment by Nodrdickan** [comment]
what should I do?

**Comment by lEtranger1942** [comment]
ATM everybody has this issue https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1247 . Wait for this to get fixed and try again later

**Comment by prockerxoxo** [comment]
I found out if you keep updating the "sess" it works for me

**Comment by Macmasteri** [comment]
> I found out if you keep updating the "sess" it works for me

Do you fill in manually in auth file or using geckdriver?

**Comment by Macmasteri** [comment]
I still getting the error after latest commit when using geckodriver.
