### ISSUE TITLE
Is min_drive_space working?

### ISSUE THREAD

**Issue by WellSomething** [DIGITALCRIMINAL/OnlyFans#1263]
Hi,

I have set `"min_drive_space": 4,` so from my understanding is that at 4GB of remaining drive space the script will go on an infinite loop (only have 1 drive for downloads) until the drive has enough space again.

Instead, my drive is getting filled up fully and then I have these errors:

```
Traceback (most recent call last):
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\YYYYYYYYYY\OnlyFans\OnlyFans-v7.2-master\start_ofd.py", line 43, in <module>
    api = main_datascraper.start_datascraper(
  File "Z:\YYYYYYYYYY\OnlyFans\OnlyFans-v7.2-master\datascraper\main_datascraper.py", line 106, in start_datascraper
    x = main_helper.process_downloads(api, module)
  File "Z:\YYYYYYYYYY\OnlyFans\OnlyFans-v7.2-master\helpers\main_helper.py", line 651, in process_downloads
    module.download_media(auth, subscription)
  File "Z:\YYYYYYYYYY\OnlyFans\OnlyFans-v7.2-master\modules\onlyfans.py", line 1127, in __init__
    database_session.commit()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3262, in flush
    self._flush(objects)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3402, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3362, in _flush
    flush_context.execute()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 455, in execute
    rec.execute(self)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 629, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 234, in save_obj
    _emit_update_statements(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 998, in _emit_update_statements
    c = connection._execute_20(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: UPDATE medias SET size=?, downloaded=? WHERE medias.id = ?]
[parameters: (47926, True, 540)]
```

Thanks

**Comment by DIGITALCRIMINAL** [comment]
Increase the limit Mines set to 100gb. The minimum is only checked at before you download a model.
