### ISSUE TITLE
Windows 10: Permission Error [Errno 13]

### ISSUE THREAD

**Issue by bwr89** [DIGITALCRIMINAL/OnlyFans#127]
The data scraper was working fine for a week or so, but now I'm getting the below error.  Updated my auth info, didn't help.  Running the script as admin also didn't work.  Directories have remained the same this whole time, and I haven't changed permissions for anything.

Traceback (most recent call last):
  File "C:\Users\bwr\Desktop\OnlyFans-master\StartDatascraper.py", line 111, in <module>
    x.download_media(*arg)
  File "C:\Users\bwr\Desktop\OnlyFans-master\modules\onlyfans.py", line 346, in download_media
    pool.starmap(download, product(
  File "C:\Users\bwr\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\bwr\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\bwr\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\bwr\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\bwr\Desktop\OnlyFans-master\modules\onlyfans.py", line 331, in download
    with open(download_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:/Users/bwr/Desktop/xxx/onlyfans/xxx/Posts/Images/'

**Comment by DIGITALCRIMINAL** [comment]
If you're using file_name_format, just use "{file_name}.{ext}"

**Comment by bwr89** [comment]
> If you're using file_name_format, just use "{file_name}.{ext}"

That seems to have worked, thank you!
