### ISSUE TITLE
ValueError: Invalid isoformat string: '01-01-0001 00:00:00'

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#1275]
Anyone else getting the following error?

```
0it [00:00, ?it/s]Traceback (most recent call last):
File "C:\Users\user\Desktop\OnlyFans-master\start_ofd.py", line 44, in
api = main_datascraper.start_datascraper(json_config, site_name_lower)
File "C:\Users\user\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 114, in start_datascraper
x = main_helper.process_downloads(api, module)
File "C:\Users\user\Desktop\OnlyFans-master\helpers\main_helper.py", line 652, in process_downloads
module.download_media(auth, subscription)
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 1259, in __init__
pool.starmap(
File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
return self._map_async(func, iterable, starmapstar, chunksize).get()
File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
raise self._value
File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 1327, in prepare_download
unrefined_result = [media_scraper(
File "C:\Users\user\Desktop\OnlyFans-master\modules\onlyfans.py", line 1076, in media_scraper
date_object = datetime.fromisoformat(date)
ValueError: Invalid isoformat string: '01-01-0001 00:00:00'
```

**Comment by DIGITALCRIMINAL** [comment]
Which model are you scraping

**Comment by avekifes** [comment]
kittyhotwife69

**Comment by ProjektPremium** [comment]
Could it have something to do with the fact that she's inactive?

**Comment by avekifes** [comment]
Interesting. I wasn't aware that inactive accounts are still counted as active subscriptions.

**Comment by DIGITALCRIMINAL** [comment]
It's not because of inactive. I was able to scrape it fully. What's your config settings?

**Comment by avekifes** [comment]
```
{
  "info": {
    "version": 7.1
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [

      ],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [

          ],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [

          ],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [

          ],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [

    ],
    "cert": "",
    "random_string": "f02360cd40ef11eb84db0c9d92876231"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          "X:\\OnlyFans"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{media_type}",
        "filename_format": "[{date}] {filename}.{ext}",
        "metadata_directories": [
          "X:\\OnlyFans"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [

        ],
        "ignore_type": "",
        "blacklist_name": "Blacklist",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [

        ],
        "ignore_type": "",
        "blacklist_name": "",
        "webhook": true
      }
    }
  }
}
```

**Comment by DIGITALCRIMINAL** [comment]
Strange, I was able to download her stuff. Did you buy any of their content?

**Comment by tocking** [comment]
I get this error for the profile notmyaveragepage

**Comment by foxdude42** [comment]
I'm seeing this too. The issue is `master_date` in `onlyfans.py`. It's set to `01-01-0001 00:00:00` which isn't a valid ISO 8601 date-time.

**Comment by DIGITALCRIMINAL** [comment]
Latest commit should fix it, but the latest commit is a pretty much a rewrite .-.
