### ISSUE TITLE
Date error for some posts

### ISSUE THREAD

**Issue by tocking** [DIGITALCRIMINAL/OnlyFans#1288]
Getting the following error for one of the models I am signed up for:

0it [00:00, ?it/s]Traceback (most recent call last):
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 114, in start_datascraper
    x = main_helper.process_downloads(api, module)
  File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 652, in process_downloads
    module.download_media(auth, subscription)
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 1259, in __init__
    pool.starmap(
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 1327, in prepare_download
    unrefined_result = [media_scraper(
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 1076, in media_scraper
    date_object = datetime.fromisoformat(date)
ValueError: Invalid isoformat string: '01-01-0001 00:00:00'

**Comment by OFfriend** [comment]
i thinks it's the same issue like #1275
