### ISSUE TITLE
Error when trying to scrape

### ISSUE THREAD

**Issue by lanzjose** [DIGITALCRIMINAL/OnlyFans#1296]
Hello people! When I try to download something, i get this error :( What can i do?

Type: Profile
Traceback (most recent call last):
  File "D:\Only\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\Only\datascraper\main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "D:\Only\helpers\main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "D:\Only\modules\onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "D:\Only\modules\onlyfans.py", line 742, in prepare_scraper
    profile_scraper(
  File "D:\Only\modules\onlyfans.py", line 283, in profile_scraper
    d_session = download_session()
  File "C:\Program Files\Python39\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
    cls.monitor = TMonitor(cls, cls.monitor_interval)
  File "C:\Program Files\Python39\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
    getattr(sys, 'setcheckinterval'))(100)
AttributeError: module 'sys' has no attribute 'setcheckinterval'

**Comment by DIGITALCRIMINAL** [comment]
What's your OS?
