### ISSUE TITLE
KeyError: 'content-length'

### ISSUE THREAD

**Issue by YDdraigGoch** [DIGITALCRIMINAL/OnlyFans#130]
Hello again.

When I am downloading a particular model I get a KeyError: 'content-length' error. I don't know if it's to do with her having 7k photos (not counting videos). Other models download fine. On a Windows PC.

`Traceback (most recent call last):
  File "StartDatascraper.py", line 109, in <module>
    x.download_media(*arg)
  File "\OnlyFans-3.6\modules\onlyfans.py", line 352, in download_media
    pool.starmap(download, product(
  File "C:\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "\OnlyFans-3.6\modules\onlyfans.py", line 321, in download
    content_length = int(header["content-length"])
  File "C:\Python38\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'`

**Comment by DIGITALCRIMINAL** [comment]
Try newest release

**Comment by YDdraigGoch** [comment]
Seems to work now. Thanks.
