### ISSUE TITLE
Issue with update

### ISSUE THREAD

**Issue by dballs6666** [DIGITALCRIMINAL/OnlyFans#1301]
Traceback (most recent call last):
  File "D:\OnlyFans-master\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 50, in start_datascraper
    original_sessions = api_helper.create_session(settings=json_settings)
  File "D:\OnlyFans-master\apis\api_helper.py", line 206, in create_session
    session = test_session(max_threads=max_threads)
  File "D:\OnlyFans-master\apis\api_helper.py", line 183, in test_session
    r = session_manager().json_request(
  File "D:\OnlyFans-master\apis\api_helper.py", line 63, in __init__
    dynamic_rules = requests.get(dr_link).json()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by dballs6666** [comment]
SO windows 10

**Comment by Jakeyy22** [comment]
Don't think it has anything to do with the latest commit, I'm having the same issue on the commit from before.

Could be an OF change, as mine was working this morning then suddenly getting this error

**Comment by Macmasteri** [comment]
Can you still login with python?

**Comment by DIGITALCRIMINAL** [comment]
Github is messed up atm

**Comment by Jakeyy22** [comment]
Looks to be ok now
