### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html

### ISSUE THREAD

**Issue by newadventure079** [DIGITALCRIMINAL/OnlyFans#1306]
I'm on the latest commit

```
python3 start_ofd.py
Auth (V1) Attempt 1/10
Welcome xxxxx | xxxxx
Scraping Paid Content
Scraping - sexbydesign | 1 / 29
Scraping - melody_katt | 2 / 29
Scraping - angela_ride | 3 / 29
Scraping - yummycouple | 4 / 29
Scraping - officialkmbooty | 5 / 29
Scraping - jessiebuns | 6 / 29
Scraping - moodyfeet | 7 / 29
Scraping - jessikagotti | 8 / 29
Scraping - aaliyahlove | 9 / 29
Scraping - xtaylorjayx | 10 / 29
Scraping - allipark22 | 11 / 29
Scraping - sheisatang | 12 / 29
Scraping - annablossom | 13 / 29
Scraping - youlovemads | 14 / 29
Scraping - pixei | 15 / 29
Scraping - juliecb | 16 / 29
Scraping - jewlsmarciano | 17 / 29
Scraping - kikimarie | 18 / 29
Scraping - sashawonderr | 19 / 29
Scraping - kyliecupcake | 20 / 29
Scraping - tiffanyhouston_of | 21 / 29
Scraping - saffronbacchus | 22 / 29
Scraping - hollybabyxoxo | 23 / 29
Scraping - jessnjamez | 24 / 29
Scraping - brandibraids | 25 / 29
Scraping - lemon__cakes | 26 / 29
Scraping - fit_american_girl | 27 / 29
Scraping - surfergirl121 | 28 / 29
Scraping - subgirl0831 | 29 / 29
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = sexbydesign | 2 = melody_katt | 3 = angela_ride | 4 = yummycouple | 5 = officialkmbooty | 6 = jessiebuns | 7 = moodyfeet | 8 = jessikagotti | 9 = aaliyahlove | 10 = xtaylorjayx | 11 = allipark22 | 12 = sheisatang | 13 = annablossom | 14 = youlovemads | 15 = pixei | 16 = juliecb | 17 = jewlsmarciano | 18 = kikimarie | 19 = sashawonderr | 20 = kyliecupcake | 21 = tiffanyhouston_of | 22 = saffronbacchus | 23 = hollybabyxoxo | 24 = jessnjamez | 25 = brandibraids | 26 = lemon__cakes | 27 = fit_american_girl | 28 = surfergirl121 | 29 = subgirl0831
0
Scrape Processing
Name: sexbydesign
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6b1b10eb67de -> a918b6b05d2f, content
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6b1b10eb67de -> a918b6b05d2f, content
Type: Profile
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.98M/2.98M [00:01<00:00, 1.79MB/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "/Users/Documents/code/OnlyFans/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "/Users/Documents/code/OnlyFans/helpers/main_helper.py", line 684, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 789, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/Users/Documents/code/OnlyFans/apis/onlyfans/classes/create_user.py", line 288, in get_posts
    results = await api_helper.scrape_endpoint_links(
  File "/Users/Documents/code/OnlyFans/apis/api_helper.py", line 453, in scrape_endpoint_links
    results = await session_manager.async_requests(links)
  File "/Users/Documents/code/OnlyFans/apis/api_helper.py", line 221, in async_requests
    results = await asyncio.ensure_future(run(items))
  File "/Users/Documents/code/OnlyFans/apis/api_helper.py", line 218, in run
    responses = await asyncio.gather(*tasks)
  File "/Users/Documents/code/OnlyFans/apis/api_helper.py", line 179, in json_request
    result = await response.json()
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://onlyfans.com/api2/v2/users/32518692/posts?limit=10&offset=280&order=publish_date_desc&skip_users_dups=0')
```

**Comment by newadventure079** [comment]
It works now and is much faster!
