### ISSUE TITLE
New database error when scraping

### ISSUE THREAD

**Issue by aschettler** [DIGITALCRIMINAL/OnlyFans#1309]
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "D:\Python\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\Python\OnlyFans\datascraper\main_datascraper.py", line 101, in start_datascraper
    paid_content = await module.paid_content_scraper(api, identifiers)
  File "D:\Python\OnlyFans\modules\onlyfans.py", line 421, in paid_content_scraper
    w = process_metadata(
  File "D:\Python\OnlyFans\modules\onlyfans.py", line 670, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "D:\Python\OnlyFans\helpers\main_helper.py", line 297, in export_sqlite
    x = legacy_database_fixer(
  File "D:\Python\OnlyFans\helpers\main_helper.py", line 205, in legacy_database_fixer
    x = export_sqlite(old_database_path, datas, database_name, legacy_fixer=True)
  File "D:\Python\OnlyFans\helpers\main_helper.py", line 326, in export_sqlite
    post_db.archived = post["archived"]
KeyError: 'archived'

**Comment by Macmasteri** [comment]
Are you using the latest commit? Works fine here. Check Auth settings.

**Comment by hdeathray** [comment]
I am seeing this issue as well on both windows and ubuntu (20.01).  It appears to be an issue with the DB on one of the latest commits.  I "resolved" the issue by removing the .sites directory and redownloading everything

**Comment by DIGITALCRIMINAL** [comment]
It's to do with json file in metadata, I do need to fix it.

**Comment by mwald84** [comment]
I'm having this one for a few days. Not sure if related: 

```
Traceback (most recent call last):
  File "d:\OneDrive\cb\grabOF\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "d:\OneDrive\cb\grabOF\OnlyFans\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "d:\OneDrive\cb\grabOF\OnlyFans\helpers\main_helper.py", line 684, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "d:\OneDrive\cb\grabOF\OnlyFans\modules\onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "d:\OneDrive\cb\grabOF\OnlyFans\modules\onlyfans.py", line 794, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "d:\OneDrive\cb\grabOF\OnlyFans\apis\onlyfans\classes\create_user.py", line 336, in get_messages
    has_more = results[-1]["hasMore"]
KeyError: 'hasMore'
```

**Comment by DIGITALCRIMINAL** [comment]
Update to the latest commit

**Comment by mwald84** [comment]
> Not related, but update to the latest commit

That output was after syncing to the latest master.

**Comment by DIGITALCRIMINAL** [comment]
@hdeathray @aschettler what model are you scraping?

**Comment by fl4shback** [comment]
Hey!

I managed to solve this by removing the Pre_Alembic_*.db files in my metadata folders.

Maybe there's something there

**Comment by DIGITALCRIMINAL** [comment]
> Hey!
> 
> I managed to solve this by removing the Pre_Alembic_*.db files in my metadata folders.
> 
> Maybe there's something there

Don't do that... Renaming the json files didn't help?

**Comment by fl4shback** [comment]
No, nothing worked until I did that. Maybe my files were corrupted..

If I remember correctly those files are used to rename downloaded files, no ?

**Comment by DIGITALCRIMINAL** [comment]
> > Hey!
> > I managed to solve this by removing the Pre_Alembic_*.db files in my metadata folders.
> > Maybe there's something there
> 
> Don't do that... Renaming the json files didn't help?

Ohh sorry, I thought it was something else. Yee I remember a problem with that.

**Comment by avekifes** [comment]
I'm running into this error. Just to confirm, the fix is to delete Pre_Alembic_*.db?

**Comment by DIGITALCRIMINAL** [comment]
> I'm running into this error. Just to confirm, the only fix is to delete Pre_Alembic_*.db?

If I can remember pre_alembic contains nothing
