### ISSUE TITLE
Issue scrapping my profile

### ISSUE THREAD

**Issue by twist3dimages** [DIGITALCRIMINAL/OnlyFans#1313]
I don't have any issues with other users but this errors out on my profile every time

Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.

Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.

Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.

Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.

Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
No Archived Found.
Type: Messages
Traceback (most recent call last):
  File "c:\Onlyfans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "c:\Onlyfans\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "c:\Onlyfans\helpers\main_helper.py", line 684, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "c:\Onlyfans\modules\onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "c:\Onlyfans\modules\onlyfans.py", line 794, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "c:\Onlyfans\apis\onlyfans\classes\create_user.py", line 336, in get_messages
    has_more = results[-1]["hasMore"]
KeyError: 'hasMore'

**Comment by DIGITALCRIMINAL** [comment]
Ohh okay, so you're a creator?

**Comment by twist3dimages** [comment]
I do have my own profile but I can't delete it

**Comment by twist3dimages** [comment]
Is there a way to only scrape users besides my own profile?

**Comment by mwald84** [comment]
I'm having a similar problem. I opened an issue before I saw this one so I closed it.

I'm running the current master (I just synced to be sure) and I am having this error:

```
Processing metadata.
Merging new metadata with old metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
No Archived Found.
Type: Messages
Traceback (most recent call last):
  File "d:\OneDrive\cb\grabOF\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "d:\OneDrive\cb\grabOF\OnlyFans\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "d:\OneDrive\cb\grabOF\OnlyFans\helpers\main_helper.py", line 684, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "d:\OneDrive\cb\grabOF\OnlyFans\modules\onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "d:\OneDrive\cb\grabOF\OnlyFans\modules\onlyfans.py", line 794, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "d:\OneDrive\cb\grabOF\OnlyFans\apis\onlyfans\classes\create_user.py", line 336, in get_messages
    has_more = results[-1]["hasMore"]
KeyError: 'hasMore'
```

I tried to clone the repo again in a new folder but the error still happens. I also tried to not reuse the `.sites/` from the previous runs. Same error.

I'm a creator. I checked `.sites/` after the error when running from scratch. It creates part of the folder structure (only posts for some creators, only messages for others) and the only thing it downloads is my profile pic (not my header pic, only the one from profile).

I also tried to turn on and off the renamer option and change to 1 and -1 the threads option.

I changed `auto_model_choice` to false in the config and tried one by one the creators. The scrapping of my profile shows the previous problem but what is weird is that it shows this:

```
Scraping [photo]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.

Scraping [text]. Should take less than a minute.
```

repeating that a lot of times before giving that error (I think it's weird because it's only 1 profile). And if I pressa a key, it repeats, asking for a new profile to scrap.

But if I try to choose any other creator (free or paid OF) I get this error:

```
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022AF909D430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
and the script aborts.

Any ideas?

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit

**Comment by mwald84** [comment]
It says it finished but no media was downloaded (except for my profile pic, again)

```
Archive Completed in 6.46 Minutes
Now exiting.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000016030AFD430>
Traceback (most recent call last):
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "d:\mrs\WPy64-3940\python-3.9.4.amd64\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by mwald84** [comment]
> Download latest commit

I did. Same problem.

**Comment by twist3dimages** [comment]
Fixed for me
