### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: [WinError 121]

### ISSUE THREAD

**Issue by Flskrnr** [DIGITALCRIMINAL/OnlyFans#1327]
Hello, I have this error just after the script tells me the download is processing, what can I do ?

Traceback (most recent call last):
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\datascraper\main_datascraper.py", line 113, in start_datascraper
    x = await main_helper.process_downloads(api, module)
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\helpers\main_helper.py", line 692, in process_downloads
    await module.prepare_downloads(subscription)
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\modules\onlyfans.py", line 1263, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\api_helper.py", line 309, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\api_helper.py", line 242, in run
    responses = await asyncio.gather(*tasks)
  File "H:\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\api_helper.py", line 172, in json_request
    async with request_method(link, headers=headers) as response:
  File "C:\Python 39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Python 39\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "C:\Python 39\lib\site-packages\aiohttp\client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "C:\Python 39\lib\site-packages\aiohttp\streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 121] Le délai de temporisation de sémaphore a expiré``

**Comment by Kroganil** [comment]
I have, kind of, the same issue. I can't start it from the github desktop version. So i've downloaded the last commit manually and it's what i got : 
`E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49>start_ofd.py
Traceback (most recent call last):
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\helpers\main_helper.py", line 3, in <module>
    from apis.onlyfans.classes.extras import content_types
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\onlyfans\classes\__init__.py", line 1, in <module>
    from apis.onlyfans.classes.create_auth import create_auth
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\onlyfans\classes\create_auth.py", line 8, in <module>
    from apis import api_helper
  File "E:\OnlyFans\OnlyFans-f49a5d6e9a9633148736db3e19f037d26a829a49\apis\api_helper.py", line 16, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'`

Any cue?

**Comment by kingknuts** [comment]
Use ‘pip install -r requirements.txt’

**Comment by Kroganil** [comment]
Thank you!
I didn't know we had to do it from time to time.
OP, sorry to hijack your thread.

**Comment by DIGITALCRIMINAL** [comment]
Seems to be related to your hardware.
