### ISSUE TITLE
Windows:  FileNotFoundError

### ISSUE THREAD

**Issue by vv211** [DIGITALCRIMINAL/OnlyFans#133]
the script always gets caught on one model's one specific post with this error

`Traceback (most recent call last):
  File "StartDatascraper.py", line 109, in <module>
    x.download_media(*arg)
  File "D:\Downloads\.tools\OnlyFans-3.6.1\modules\onlyfans.py", line 354, in download_media
    pool.starmap(download, product(
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\Downloads\.tools\OnlyFans-3.6.1\modules\onlyfans.py", line 339, in download
    with open(download_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './downloads/onlyfans/nevamore/Posts/Images/2020-01-16_~_Goo
d morning, favorites!   It's supposed to rain today! Think I'll play in it and take some photos for you!_~_1098x2160
_b3d8f5f17b2eb155a0125a84e8384e977663875e208b9bb9c04.jpg'`

Here is my config

`      "settings": {
        "auto_choice": "a",
        "auto_scrape_all": false,
        "directory": "./downloads",
        "file_name_format": "{username}/{date}_~_{text}_~_{file_name}.{ext}",
        "text_length": "42",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_unfollowed_accounts": ""
`

I am running on the latest release (3.6.1)

**Comment by DIGITALCRIMINAL** [comment]
Remove text

**Comment by vv211** [comment]
Thank you, I will try that and let you know

**Comment by vv211** [comment]
removing text worked, sorry i forgot to follow up
