### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by tocking** [DIGITALCRIMINAL/OnlyFans#1336]
Scraping [photo]. Should take less than a minute.

Traceback (most recent call last):
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 685, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 167, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 821, in prepare_scraper
    unrefined_set = pool.starmap(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 1200, in media_scraper
    for temp_media in medias:
TypeError: 'NoneType' object is not iterable

**Comment by Macmasteri** [comment]
Dont know if its the same error. Running the latest commit and got this after scraping a model for a minute:

Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 113, in start_datascraper
    x = await main_helper.process_downloads(api, module)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 693, in process_downloads
    await module.prepare_downloads(subscription)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1262, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "E:\OnlyFans-master\apis\api_helper.py", line 328, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "E:\OnlyFans-master\apis\api_helper.py", line 323, in run
    result = await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\api_helper.py", line 307, in process_download
    await main_helper.write_data(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 734, in write_data
    async for data in response.content.iter_chunked(4096):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 39, in __anext__
    rv = await self.read_func()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 380, in read
    await self._wait("read")
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 306, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

**Comment by DIGITALCRIMINAL** [comment]
> Dont know if its the same error. Running the latest commit and got this after scraping a model for a minute:
> 
> Traceback (most recent call last):
> File "E:\OnlyFans-master\start_ofd.py", line 44, in main
> api = await main_datascraper.start_datascraper(json_config, site_name_lower)
> File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 113, in start_datascraper
> x = await main_helper.process_downloads(api, module)
> File "E:\OnlyFans-master\helpers\main_helper.py", line 693, in process_downloads
> await module.prepare_downloads(subscription)
> File "E:\OnlyFans-master\modules\onlyfans.py", line 1262, in prepare_downloads
> a = await subscription.session_manager.async_downloads(
> File "E:\OnlyFans-master\apis\api_helper.py", line 328, in async_downloads
> results = await asyncio.ensure_future(run(download_list))
> File "E:\OnlyFans-master\apis\api_helper.py", line 323, in run
> result = await asyncio.gather(*tasks)
> File "E:\OnlyFans-master\apis\api_helper.py", line 307, in process_download
> await main_helper.write_data(
> File "E:\OnlyFans-master\helpers\main_helper.py", line 734, in write_data
> async for data in response.content.iter_chunked(4096):
> File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 39, in **anext**
> rv = await self.read_func()
> File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 380, in read
> await self._wait("read")
> File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 306, in _wait
> await waiter
> aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

It's not, but I fixed in latest commit.

**Comment by DIGITALCRIMINAL** [comment]
> Scraping [photo]. Should take less than a minute.
> 
> Traceback (most recent call last):
> File "G:\OF2\OnlyFans-master\start_ofd.py", line 44, in main
> api = await main_datascraper.start_datascraper(json_config, site_name_lower)
> File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 104, in start_datascraper
> names = await main_helper.process_names(
> File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 685, in process_names
> result = await module.start_datascraper(authed, username, site_name)
> File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 167, in start_datascraper
> results = await prepare_scraper(authed, site_name, item)
> File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 821, in prepare_scraper
> unrefined_set = pool.starmap(
> File "C:\Users<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
> return self._map_async(func, iterable, starmapstar, chunksize).get()
> File "C:\Users<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
> raise self._value
> File "C:\Users<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
> result = (True, func(*args, **kwds))
> File "C:\Users<username>\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
> return list(itertools.starmap(args[0], args[1]))
> File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 1200, in media_scraper
> for temp_media in medias:
> TypeError: 'NoneType' object is not iterable

Which model?
