### ISSUE TITLE
Ver 7.3 - KeyError: 'list'

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#1337]
```
Type: Messages
Traceback (most recent call last):
  File "I:\OnlyFans-7.3\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "I:\OnlyFans-7.3\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "I:\OnlyFans-7.3\helpers\main_helper.py", line 685, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "I:\OnlyFans-7.3\modules\onlyfans.py", line 167, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "I:\OnlyFans-7.3\modules\onlyfans.py", line 788, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "I:\OnlyFans-7.3\apis\onlyfans\classes\create_user.py", line 341, in get_messages
    final_results = [x["list"] for x in results]
  File "I:\OnlyFans-7.3\apis\onlyfans\classes\create_user.py", line 341, in <listcomp>
    final_results = [x["list"] for x in results]
KeyError: 'list'
```

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit
