### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by Dr1zak** [DIGITALCRIMINAL/OnlyFans#1338]
Running the script after initial setup:

Traceback (most recent call last):
  File "C:\Users\...Account Name...\Desktop\OnlyFans-7.3\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\..Account Name....\Desktop\OnlyFans-7.3\datascraper\main_datascraper.py", line 71, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "C:\Users\...Account Name...\Desktop\OnlyFans-7.3\helpers\main_helper.py", line 625, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by DIGITALCRIMINAL** [comment]
Input a digit

**Comment by Dr1zak** [comment]
> Input a digit

Where?
