### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by icemouton** [DIGITALCRIMINAL/OnlyFans#1342]
Since June 6th I am getting permission denied errors on every run.
I pulled the latest commits a few times including last night's.
I'm geting some succesful downloads and then a random one will fail.
Wasn't able to complete a full run since...
```
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/datascraper/main_datascraper.py", line 113, in start_datascraper
    x = await main_helper.process_downloads(api, module)
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/helpers/main_helper.py", line 700, in process_downloads
    await module.prepare_downloads(subscription)
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/modules/onlyfans.py", line 1268, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 336, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 331, in run
    result = await asyncio.gather(*tasks)
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 308, in process_download
    status_code = await main_helper.write_data(
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/helpers/main_helper.py", line 742, in write_data
    with open(download_path, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/secure/rips/OnlyFans/[REDACTED]/Messages/Free/Images/3840x2880_b58817ee71467054544bbba72c2564c4.jpg''
```
![image](https://user-images.githubusercontent.com/6319013/121911210-9267cb00-ccfd-11eb-8b2c-7012a2fde625.png)

**Comment by DIGITALCRIMINAL** [comment]
> Since June 6th I am getting permission denied errors on every run.
> I pulled the latest commits a few times including last night's.
> I'm geting some succesful downloads and then a random one will fail.
> Wasn't able to complete a full run since...
> 
> ```
> 0it [00:00, ?it/s]Traceback (most recent call last):
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/start_ofd.py", line 45, in main
>     api = await main_datascraper.start_datascraper(
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/datascraper/main_datascraper.py", line 113, in start_datascraper
>     x = await main_helper.process_downloads(api, module)
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/helpers/main_helper.py", line 700, in process_downloads
>     await module.prepare_downloads(subscription)
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/modules/onlyfans.py", line 1268, in prepare_downloads
>     a = await subscription.session_manager.async_downloads(
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 336, in async_downloads
>     results = await asyncio.ensure_future(run(download_list))
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 331, in run
>     result = await asyncio.gather(*tasks)
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/api_helper.py", line 308, in process_download
>     status_code = await main_helper.write_data(
>   File "/media/DATANAS01/secure/OnlyFans/OnlyFans/helpers/main_helper.py", line 742, in write_data
>     with open(download_path, "wb") as f:
> PermissionError: [Errno 13] Permission denied: '/secure/rips/OnlyFans/[REDACTED]/Messages/Free/Images/3840x2880_b58817ee71467054544bbba72c2564c4.jpg''
> ```
> 
> ![image](https://user-images.githubusercontent.com/6319013/121911210-9267cb00-ccfd-11eb-8b2c-7012a2fde625.png)

Is there multiple files called "3840x2880_b58817ee71467054544bbba72c2564c4"?

**Comment by icemouton** [comment]
Not sure what you mean ? There is a file with that name in the folder already from oct 2020...

**Comment by DIGITALCRIMINAL** [comment]
> Not sure what you mean ? There is a file with that name in the folder already from oct 2020...

Is there more than one?

**Comment by icemouton** [comment]
No only one file in the folder with that name, I'm not sure how 2 files with the same name can exist in the same folder in any filesystem I know of...

**Comment by icemouton** [comment]
So I deleted the file becuase twice it gave the same file name but next run it stopped here :
```
Scrape Processing
Name: [REDACTED]
Type: Profile
0.00B [00:03, ?B/s]
Type: Stories
Scraping [photo]. Should take less than a minute.

Scraping [video | stream | gif]. Should take less than a minute.

Scraping [audio]. Should take less than a minute.

Scraping [text]. Should take less than a minute.

Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Traceback (most recent call last):
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/helpers/main_helper.py", line 692, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/modules/onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/modules/onlyfans.py", line 788, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/onlyfans/classes/create_user.py", line 297, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/onlyfans/classes/create_user.py", line 297, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "/media/DATANAS01/secure/OnlyFans/OnlyFans/apis/onlyfans/classes/create_post.py", line 9, in __init__
    self.responseType: str = option.get("responseType")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by DIGITALCRIMINAL** [comment]
Which model are you scraping
