### ISSUE TITLE
 'NoneType' object has no attribute 'content_length' Error - Can't finish run

### ISSUE THREAD

**Issue by EightDee** [DIGITALCRIMINAL/OnlyFans#1349]
I'm constantly getting some variation of the following error. I haven't been able to finish a cycle in a few weeks. Nothing gets downloaded. I'm using the latest committed code.

```
Scraping [text]. Should take less than a minute.

Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Scrape Completed

Scrape Processing
Name: iwantjudyyy
Type: Profile
0it [00:00, ?it/s]Traceback (most recent call last):
  File "Y:\Temp\Scrape\start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "Y:\Temp\Scrape\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "Y:\Temp\Scrape\helpers\main_helper.py", line 692, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 773, in prepare_scraper
    await profile_scraper(
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 311, in profile_scraper
    if os.path.getsize(download_path) == response.content_length:
AttributeError: 'NoneType' object has no attribute 'content_length'
```

**Comment by DIGITALCRIMINAL** [comment]
Have her profile's avatar and header already been downloaded?
