### ISSUE TITLE
Script won't run

### ISSUE THREAD

**Issue by mikejones498** [DIGITALCRIMINAL/OnlyFans#135]
I'm not sure if I'm missing something but I have python installed and set up the config file and get this when i try to run the scraper 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\>cd C:\Users\Nathan\Downloads\OnlyFans-master

C:\Users\\Downloads\OnlyFans-master>python StartDatascraper.py
Traceback (most recent call last):
  File "StartDatascraper.py", line 1, in <module>
    from modules.helpers import update_config
  File "C:\Users\\Downloads\OnlyFans-master\modules\helpers.py", line 14,
in <module>
    json_config = json.load(open('config.json'))
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\json\__ini
t__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\json\__ini
t__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\json\decod
er.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\\AppData\Local\Programs\Python\Python38-32\lib\json\decod
er.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 12 column 9 (char 33
7)

C:\Users\\Downloads\OnlyFans-master>

**Comment by DIGITALCRIMINAL** [comment]
Your config format is wrong

**Comment by DIGITALCRIMINAL** [comment]
Did you fix it, or do you need help?
