### ISSUE TITLE
KeyError: 'hasMore'

### ISSUE THREAD

**Issue by newadventure079** [DIGITALCRIMINAL/OnlyFans#1350]
I was halfway thru a bunch of models and this error was thrown.  I'm on the latest commit.

```
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
No Archived Found.
Type: Messages
Traceback (most recent call last):
  File "/Users/Documents/code/OnlyFans/start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "/Users/Documents/code/OnlyFans/helpers/main_helper.py", line 692, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 172, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 793, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "/Users/Documents/code/OnlyFans/apis/onlyfans/classes/create_user.py", line 342, in get_messages
    has_more = results[-1]["hasMore"]
KeyError: 'hasMore'
```

**Comment by oferchen** [comment]
I have the exact same issue.

**Comment by DIGITALCRIMINAL** [comment]
Model name?

**Comment by oferchen** [comment]
> Model name?

lionawild

**Comment by DIGITALCRIMINAL** [comment]
Did you block her from messaging you

**Comment by oferchen** [comment]
yes

> Did you block her from messaging you

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit
