### ISSUE TITLE
TypeError: 'error_details' object does not support item assignment

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINAL/OnlyFans#1354]
with commit 736 (2ca95beec5dd526b9b825497dc6227aafbaf67ad) version I receive this error after the start:

Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 45, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 73, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 111, in account_setup
    subscriptions += await manage_subscriptions(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1281, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 321, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 302, in multi
    tasks = await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 203, in get_user
    result["session_manager"] = self.session_manager
TypeError: 'error_details' object does not support item assignment

I have checked the auth file and seems correct.

**Comment by hammerheaddf** [comment]
Same here. Python 3.9.5 on Raspbian 64-bit.

**Comment by DIGITALCRIMINAL** [comment]
Which model are you scraping

**Comment by hammerheaddf** [comment]
> 
> 
> Which model are you scraping

In my case, none. It fails on authenticating.

**Comment by DIGITALCRIMINAL** [comment]
Ahh I see, you're a creator?

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by CannotTouch** [comment]
thanks it works again for me
