### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#1360]
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Traceback (most recent call last):
  File "I:\OnlyFans-7.3\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "I:\OnlyFans-7.3\datascraper\main_datascraper.py", line 104, in start_datascraper
    names = await main_helper.process_names(
  File "I:\OnlyFans-7.3\helpers\main_helper.py", line 685, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "I:\OnlyFans-7.3\modules\onlyfans.py", line 167, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "I:\OnlyFans-7.3\modules\onlyfans.py", line 783, in prepare_scraper
    master_set = await subscription.get_posts()
  File "I:\OnlyFans-7.3\apis\onlyfans\classes\create_user.py", line 295, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "I:\OnlyFans-7.3\apis\onlyfans\classes\create_user.py", line 295, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "I:\OnlyFans-7.3\apis\onlyfans\classes\create_post.py", line 9, in __init__
    self.responseType: str = option.get("responseType")
AttributeError: 'str' object has no attribute 'get'

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by bobsage123** [comment]
With the latest commit I get this soon after authing

Traceback (most recent call last):
  File "I:\OnlyFans-7.3_test\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "I:\OnlyFans-7.3_test\datascraper\main_datascraper.py", line 96, in start_datascraper
    paid_content = await module.paid_content_scraper(api, identifiers)
  File "I:\OnlyFans-7.3_test\modules\onlyfans.py", line 399, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'

**Comment by DIGITALCRIMINAL** [comment]
I need to see which version of tqdm you have, so run "pip show tqdm"

**Comment by bobsage123** [comment]
Version: 4.56.2

**Comment by DIGITALCRIMINAL** [comment]
pip install --upgrade --user -r requirements.txt

**Comment by bobsage123** [comment]
Thanks, looks fixed. Got a warning to add my python script folder to the PATH environment variable so did that as well.
