### ISSUE TITLE
isinstance() arg 2 must be a type or tuple of types

### ISSUE THREAD

**Issue by jp1151419** [DIGITALCRIMINAL/OnlyFans#1361]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "X:\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "X:\OnlyFans\datascraper\main_datascraper.py", line 108, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "X:\OnlyFans\helpers\main_helper.py", line 701, in process_downloads
    await module.prepare_downloads(subscription)
  File "X:\OnlyFans\modules\onlyfans.py", line 1263, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "X:\OnlyFans\apis\api_helper.py", line 333, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "X:\OnlyFans\apis\api_helper.py", line 328, in run
    result = await asyncio.gather(*tasks)
  File "X:\OnlyFans\apis\api_helper.py", line 296, in process_download
    result = await self.download_content(
  File "X:\OnlyFans\apis\api_helper.py", line 369, in download_content
    new_result = await subscription.get_post(post_id)
  File "X:\OnlyFans\apis\onlyfans\classes\create_user.py", line 311, in get_post
    if isinstance(dict,response):
TypeError: isinstance() arg 2 must be a type or tuple of types

Having this error appear on multiple creators, running the latest version after using update.py

**Comment by DIGITALCRIMINAL** [comment]
Update
