### ISSUE TITLE
TypeError: 'error_details' object is not subscriptable

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINAL/OnlyFans#1369]
im having this really weird error where for some reason mid way through scraping one profile it switches to scraping a profile I no longer subscribe to and then errors out. Any help would be amazing!!

```
Scrape Processing
Name: XXXX
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
  0%|←[35m                                                                                            ←[0m| 0/7 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 7/7 [00:00<00:00, 447.86it/s]←[0m
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6b1b10eb67de -> a918b6b05d2f, content
Renaming files.
  0%|←[35m                                                                                            ←[0m| 0/7 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 7/7 [00:00<00:00, 500.17it/s]←[0m
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
  0%|←[35m                                                                                            ←[0m| 0/3 [00:00<?100%|←[35m████████████████████████████████████████████████████████████████████████████████████████████←[0m| 3/3 [00:00<?, ?it/s]←[0m
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade aeb9fe314556 -> 7c1c6e101059, content
Renaming files.
  0%|←[35m                                                                                            ←[0m| 0/3 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 3/3 [00:00<00:00, 191.94it/s]←[0m
Scrape Completed

Download Processing
Name: YYYY | Type: Messages | Count: 10 | Directory: E:\OnlyFans-master\.sites

0it [00:00, ?it/s]Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 111, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 702, in process_downloads
    await module.prepare_downloads(subscription)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1231, in prepare_downloads
    a = await subscription.session_manager.async_downloads(
  File "E:\OnlyFans-master\apis\api_helper.py", line 337, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "E:\OnlyFans-master\apis\api_helper.py", line 332, in run
    result = await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\api_helper.py", line 300, in process_download
    result = await self.download_content(
  File "E:\OnlyFans-master\apis\api_helper.py", line 369, in download_content
    new_result = await subscription.get_message_by_id(
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 380, in get_message_by_id
    results = [x for x in results["list"] if x["id"] == message_id]
TypeError: 'error_details' object is not subscriptable
```

**Comment by DIGITALCRIMINAL** [comment]
Are you using a proxy

**Comment by jimmothy-beep** [comment]
In trying to fix this I removed the YYYY profile from the .profiles folder, re-ran the pip requirements script to confirm they were defiantly up to date then tried running another profile that wasnt XXX. I was alot more successful and it seemed to start downloading until this error got spat out.

```
Traceback (most recent call last):
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 425, in checkout
    rec = pool._do_get()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 368, in __init__
    self.__connect()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 111, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 702, in process_downloads
    await module.prepare_downloads(subscription)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1225, in prepare_downloads
    media_set_count = db_helper.get_count(download_list)
  File "E:\OnlyFans-master\helpers\db_helper.py", line 96, in get_count
    count = q.session.execute(count_q).scalar()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 3165, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 3244, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 3214, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 425, in checkout
    rec = pool._do_get()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 253, in _create_connection
    return _ConnectionRe #cord(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 368, in __init__
    self.__connect()
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\pool\base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\asdf\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Comment by jimmothy-beep** [comment]
> Are you using a proxy

no proxy

**Comment by jimmothy-beep** [comment]
> im having this really weird error where for some reason mid way through scraping one profile it switches to scraping a profile I no longer subscribe to and then errors out. Any help would be amazing!!
> 
> ```
> Scrape Processing
> Name: XXXX
> Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Type: Profile
> Type: Stories
> No Stories Found.
> Type: Posts
> Scrape Attempt: 1/100
> Type: Archived Posts
> Processing Scraped Posts
>   0%|←[35m                                                                                            ←[0m| 0/7 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 7/7 [00:00<00:00, 447.86it/s]←[0m
> Processing metadata.
> Finished processing metadata.
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO  [alembic.runtime.migration] Running upgrade 6b1b10eb67de -> a918b6b05d2f, content
> Renaming files.
>   0%|←[35m                                                                                            ←[0m| 0/7 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 7/7 [00:00<00:00, 500.17it/s]←[0m
> Type: Archived
> No Archived Found.
> Type: Messages
> Processing Scraped Messages
>   0%|←[35m                                                                                            ←[0m| 0/3 [00:00<?100%|←[35m████████████████████████████████████████████████████████████████████████████████████████████←[0m| 3/3 [00:00<?, ?it/s]←[0m
> Processing metadata.
> Finished processing metadata.
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO  [alembic.runtime.migration] Running upgrade aeb9fe314556 -> 7c1c6e101059, content
> Renaming files.
>   0%|←[35m                                                                                            ←[0m| 0/3 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 3/3 [00:00<00:00, 191.94it/s]←[0m
> Scrape Completed
> 
> Download Processing
> Name: YYYY | Type: Messages | Count: 10 | Directory: E:\OnlyFans-master\.sites
> 
> 0it [00:00, ?it/s]Traceback (most recent call last):
>   File "E:\OnlyFans-master\start_ofd.py", line 62, in <module>
>     loop.run_until_complete(main())
>   File "C:\Users\asdf\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "E:\OnlyFans-master\start_ofd.py", line 46, in main
>     api = await main_datascraper.start_datascraper(
>   File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 111, in start_datascraper
>     await main_helper.process_downloads(api, module)
>   File "E:\OnlyFans-master\helpers\main_helper.py", line 702, in process_downloads
>     await module.prepare_downloads(subscription)
>   File "E:\OnlyFans-master\modules\onlyfans.py", line 1231, in prepare_downloads
>     a = await subscription.session_manager.async_downloads(
>   File "E:\OnlyFans-master\apis\api_helper.py", line 337, in async_downloads
>     results = await asyncio.ensure_future(run(download_list))
>   File "E:\OnlyFans-master\apis\api_helper.py", line 332, in run
>     result = await asyncio.gather(*tasks)
>   File "E:\OnlyFans-master\apis\api_helper.py", line 300, in process_download
>     result = await self.download_content(
>   File "E:\OnlyFans-master\apis\api_helper.py", line 369, in download_content
>     new_result = await subscription.get_message_by_id(
>   File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 380, in get_message_by_id
>     results = [x for x in results["list"] if x["id"] == message_id]
> TypeError: 'error_details' object is not subscriptable
> ```

removing both folders seemed to have fixed this issue. ive re-installed python, all the requirements and pulled a new copy of the code to start from scratch so ill see if issue two is fixed by re-installing

**Comment by DIGITALCRIMINAL** [comment]
Did you buy anything from the model you unsubbed from

**Comment by jimmothy-beep** [comment]
> Did you buy anything from the model you unsubbed from

yeah previously - the model seems to have removed her account

**Comment by DIGITALCRIMINAL** [comment]
> Did you buy anything from the model you unsubbed from

That's the reason why. I'll fix it in a bit.

**Comment by jimmothy-beep** [comment]
easy as!

**Comment by jimmothy-beep** [comment]
re-installing everything seems to have fixed error number 2 as well

**Comment by Nostang3** [comment]
I"m getting a similar error. Is it the same as this one or should I make a new ticket? I'm on 7.4. 

```
Traceback (most recent call last):
  File "G:\OnlyFans\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\OnlyFans\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "G:\OnlyFans\datascraper\main_datascraper.py", line 75, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "G:\OnlyFans\modules\onlyfans.py", line 112, in account_setup
    subscriptions += await manage_subscriptions(
  File "G:\OnlyFans\modules\onlyfans.py", line 1243, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "G:\OnlyFans\apis\onlyfans\classes\create_auth.py", line 314, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "G:\OnlyFans\apis\onlyfans\classes\create_auth.py", line 284, in multi
    subscriptions = [
TypeError: 'error_details' object is not iterable
```
