### ISSUE TITLE
AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#1370]
Running latest commit and seeing the following error

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\Documents\GitHub\OnlyFans\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 102, in start_datascraper
    names = await main_helper.process_names(
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 693, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 167, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 821, in prepare_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
AttributeError: type object 'tqdm_asyncio' has no attribute 'gather'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\start_ofd.py", line 66, in <module>
    input()

**Comment by ChillyP** [comment]
Sorry just seen a similar issue to mine that's already been closed.

Running "pip install --upgrade --user -r requirements.txt" looks like its fixed the issue
