### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by EightDee** [DIGITALCRIMINAL/OnlyFans#1383]
Randomly got this error. Was able to complete a few runs then got this. on a new OF acct brienightwood

```
Scrape Processing
Name: brienightwood
Type: Profile
Type: Stories
Processing Scraped Stories
  0%|←[35m
100%|←[35m████████████████████████████████████████████████████████████████████████████████████████████████
.32it/s]←[0m
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
  0%|←[35m
100%|←[35m████████████████████████████████████████████████████████████████████████████████████████████████
.08it/s]←[0m
Type: Posts
Scrape Attempt: 1/3
Type: Archived Posts
Scrape Attempt: 1/3
Traceback (most recent call last):
  File "Y:\Temp\Scrape\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "Y:\Temp\Scrape\datascraper\main_datascraper.py", line 99, in start_datascraper
    names = await main_helper.process_names(
  File "Y:\Temp\Scrape\helpers\main_helper.py", line 693, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 167, in start_datascraper
    results = await prepare_scraper(authed, site_name, item)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 792, in prepare_scraper
    master_set += await subscription.get_archived_posts()
  File "Y:\Temp\Scrape\apis\onlyfans\classes\create_user.py", line 419, in get_archived_posts
    results = await api_helper.scrape_endpoint_links(
  File "Y:\Temp\Scrape\apis\api_helper.py", line 502, in scrape_endpoint_links
    media_set = list(chain(*media_set))
TypeError: 'NoneType' object is not iterable

```

**Comment by qpidcock** [comment]
Was this a user you just subbed to? If so it sounds like it may be a caching issue. It was using old credentials maybe & after you subbed they were updated perhaps?

**Comment by EightDee** [comment]
New sub and no change in credentials. Maybe caching

**Comment by qpidcock** [comment]
Yeah it sounds like when it went to pull those downloads it got an empty response because it didn't have access for some reason.

**Comment by EightDee** [comment]
I haven't had the issue in a few days. Closing the issue.
