### ISSUE TITLE
TypeError: 'module' object is not callable when downloading

### ISSUE THREAD

**Issue by BlatantWombat** [DIGITALCRIMINAL/OnlyFans#1385]
Running the latest version, new config. It appears to scrape fine, but gives this error when downloading. Happens with two different OF users.

0it [00:00, ?it/s]Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 102, in start_datascraper
    await main_helper.process_downloads(api, module)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 816, in process_downloads
    await module.prepare_downloads(subscription)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1224, in prepare_downloads
    await main_helper.async_downloads(download_list, subscription)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 247, in async_downloads
    results = await asyncio.ensure_future(run(download_list))
  File "E:\OnlyFans-master\helpers\main_helper.py", line 242, in run
    await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 210, in process_download
    result = await session_m.download_content(
  File "E:\OnlyFans-master\apis\api_helper.py", line 257, in download_content
    new_result = await subscription.get_message_by_id(
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 383, in get_message_by_id
    final_result = create_message(result, self)
TypeError: 'module' object is not callable

However, removing the folder and forcing it to redownload, the entire user I get no errors.

**Comment by DIGITALCRIMINAL** [comment]
Fixed
