### ISSUE TITLE
Stuck when downloading posts

### ISSUE THREAD

**Issue by pjmartorell** [DIGITALCRIMINAL/OnlyFans#1407]
Hi, I'm trying to download all contents from a profile but the program is getting stuck when downloading Posts:
```
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 67.73it/s]
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade aeb9fe314556 -> 7c1c6e101059, content
INFO  [alembic.runtime.migration] Running upgrade 7c1c6e101059 -> bf20242a238f, content
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 417.61it/s]
Scrape Completed

Download Processing
Name: asdfghjkl | Type: Posts | Count: 19878 | Directory: /usr/src/app/.sites


```
I'm using the `master` branch (`099e64f`)

**Comment by DIGITALCRIMINAL** [comment]
Just let it do its task.

**Comment by pjmartorell** [comment]
I was waiting for more than half an hour and nothing was being updated in the destination folder. After interrupting the process it printed the following, just in case it's useful:
```
^CTraceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/app/helpers/main_helper.py", line 190, in run
    temp_response = [
  File "/usr/src/app/helpers/main_helper.py", line 193, in <listcomp>
    if response and str(response.url) == download_item.link
KeyboardInterrupt
```
