### ISSUE TITLE
alembic traceback error.

### ISSUE THREAD

**Issue by ThrowawayDane** [DIGITALCRIMINAL/OnlyFans#1408]
Updated to the latest release code here today, and after updating pip first i still get this error when i run the script:

Traceback (most recent call last):
  File "/home/XXXXXXXX/OnlyFans-master/start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/XXXXXXXX/OnlyFans-master/start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "/home/XXXXXXXX/OnlyFans-master/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/home/XXXXXXXX/OnlyFans-master/modules/onlyfans.py", line 407, in paid_content_scraper
    await process_metadata(
  File "/home/XXXXXXXX/OnlyFans-master/modules/onlyfans.py", line 653, in process_metadata
    final_result, delete_metadatas = main_helper.legacy_sqlite_updater(
  File "/home/XXXXXXXX/OnlyFans-master/helpers/main_helper.py", line 491, in legacy_sqlite_updater
    db_helper.run_migrations(alembic_location, legacy_metadata_path)
  File "/home/XXXXXXXX/OnlyFans-master/helpers/db_helper.py", line 49, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/command.py", line 274, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/script/base.py", line 148, in from_config
    return ScriptDirectory(
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/script/base.py", line 70, in __init__
    raise util.CommandError(
alembic.util.exc.CommandError: Path doesn't exist: '/home/XXXXXXXX/OnlyFans-master/database/archived_databases/Messages/alembic'.  Please use the 'init' command to create a new scripts folder.

If i then rename the folders from messages to Messages i get this traceback instead:

Traceback (most recent call last):
  File "/home/XXXXXXXX/OnlyFans-master/start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/XXXXXXXX/OnlyFans-master/start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "/home/XXXXXXXX/OnlyFans-master/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/home/XXXXXXXX/OnlyFans-master/modules/onlyfans.py", line 407, in paid_content_scraper
    await process_metadata(
  File "/home/XXXXXXXX/OnlyFans-master/modules/onlyfans.py", line 653, in process_metadata
    final_result, delete_metadatas = main_helper.legacy_sqlite_updater(
  File "/home/XXXXXXXX/OnlyFans-master/helpers/main_helper.py", line 491, in legacy_sqlite_updater
    db_helper.run_migrations(alembic_location, legacy_metadata_path)
  File "/home/XXXXXXXX/OnlyFans-master/helpers/db_helper.py", line 49, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/XXXXXXXX/.local/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/XXXXXXXX/OnlyFans-master/database/archived_databases/Messages/alembic/env.py", line 8, in <module>
    from database.archived_databases.messages import messages
ModuleNotFoundError: No module named 'database.archived_databases.messages'

**Comment by evilalmus** [comment]
I'm having the same problem

**Comment by DIGITALCRIMINAL** [comment]
Which model were you scraping?

**Comment by DIGITALCRIMINAL** [comment]
Update script

**Comment by ThrowawayDane** [comment]
Great it is working again. Thanks.

**Comment by DIGITALCRIMINAL** [comment]
I forgot Linux file paths are case sensitive 🥺
