### ISSUE TITLE
TypeError: 'error_details' object is not iterable

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINAL/OnlyFans#1409]
With the latest commit 757 f077e30d8312a10aa2fe576864f37c1d7a1df5e3 i receive this error on startup after the Welcome messages:

Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 105, in account_setup
    subscriptions += await manage_subscriptions(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1253, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 305, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 275, in multi
    subscriptions = [
TypeError: 'error_details' object is not iterable

**Comment by CannotTouch** [comment]
my fault.  with the update of requirements.txt and pip all works again.
