### ISSUE TITLE
Accidentally ran updater.py

### ISSUE THREAD

**Issue by Sasquatch00** [DIGITALCRIMINAL/OnlyFans#1414]
I accidentally ran the updater.py file and now anytime I try to run start_ofd.py I get the following error:

Site: 0 = onlyfans |
0
Traceback (most recent call last):
  File "F:\39\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\39\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "F:\39\OnlyFans-master\datascraper\main_datascraper.py", line 57, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "F:\39\OnlyFans-master\helpers\main_helper.py", line 861, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

Any assistance towards reversing what I did or how to move forwards would be greatly appreciated. I have tried running the script from a different Hard Drive to see if I could circumvent the issue but it persists. I see the error references a file in my user folder AppData if I delete the asyncio library would that solve it?

**Comment by dralfs513** [comment]
Download the current release: https://github.com/DIGITALCRIMINAL/OnlyFans/releases.

Unzip this.

Find the `.sites`, `.logs` and `.profiles` folders in the messed up folder.

Move these to the version you just unzipped. Run `start_ofd.py`.

Move the .sites and .profiles folders from the one you messed up to the re-downloaded 7.4 release and try running start_ofd.py.

**Comment by Sasquatch00** [comment]
I just tried this, however I do not have a folder called .logs but I moved .sites and .profiles still getting the same error:

The .settings\config.json file has been updated. Fill in whatever you need to fill in and then press enter when done.

Site: 0 = onlyfans |
0
Traceback (most recent call last):
  File "F:\OnlyFans-7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\OnlyFans-7.4\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans-7.4\datascraper\main_datascraper.py", line 66, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "F:\OnlyFans-7.4\helpers\main_helper.py", line 633, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by Sasquatch00** [comment]
Update: 
I was looking at the errors and saw that most of them were related to the fact that I was using auto choice options so I removed all of the settings related to the auto site/profile/media choice and ran the script. I did get to scraping usernames but midway through the initial list of models I ended up with this error:


  0%|←[35m                                                    ←[0m| 0/1 [00:00<?100%|←[35m███████████████████████████████████████████←[0m| 1/1 [00:00<00:00, 333.23it/s]←[0m
Processing metadata.
Merging new metadata with old metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 171, in _catch_revision_errors
    yield
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 365, in _upgrade_revs
    revs = list(revs)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 706, in iterate_revisions
    revisions, heads = fn(
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 1290, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 457, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 457, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 479, in get_revisions
    return tuple(
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 480, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 546, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'bf20242a238f'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\OnlyFans-7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\OnlyFans-7.4\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans-7.4\datascraper\main_datascraper.py", line 99, in start_datascraper
    paid_content = await module.paid_content_scraper(api, identifiers)
  File "F:\OnlyFans-7.4\modules\onlyfans.py", line 414, in paid_content_scraper
    await process_metadata(
  File "F:\OnlyFans-7.4\modules\onlyfans.py", line 662, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "F:\OnlyFans-7.4\helpers\main_helper.py", line 306, in export_sqlite
    db_helper.run_migrations(alembic_location, database_path)
  File "F:\OnlyFans-7.4\helpers\db_helper.py", line 48, in run_migrations
    command.upgrade(alembic_cfg, 'head')
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\command.py", line 294, in upgrade
    script.run_env()
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\OnlyFans-7.4\database\databases\messages\alembic\env.py", line 80, in <module>
    run_migrations_online()
  File "F:\OnlyFans-7.4\database\databases\messages\alembic\env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\migration.py", line 549, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\command.py", line 283, in upgrade
    return script._upgrade_revs(revision, rev)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 366, in _upgrade_revs
    return [
  File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 203, in _catch_revision_errors
    compat.raise_(util.CommandError(resolution), from_=re)
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\compat.py", line 296, in raise_
    raise exception
alembic.util.exc.CommandError: Can't locate revision identified by 'bf20242a238f'

**Comment by DIGITALCRIMINAL** [comment]
> Update:
> I was looking at the errors and saw that most of them were related to the fact that I was using auto choice options so I removed all of the settings related to the auto site/profile/media choice and ran the script. I did get to scraping usernames but midway through the initial list of models I ended up with this error:
> 
> 0%|←[35m ←[0m| 0/1 [00:00<?100%|←[35m███████████████████████████████████████████←[0m| 1/1 [00:00<00:00, 333.23it/s]←[0m
> Processing metadata.
> Merging new metadata with old metadata.
> Finished processing metadata.
> INFO [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO [alembic.runtime.migration] Will assume non-transactional DDL.
> Traceback (most recent call last):
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 171, in _catch_revision_errors
> yield
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 365, in _upgrade_revs revs = list(revs) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 706, in iterate_revisions revisions, heads = fn( File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 1290, in _collect_upgrade_revisions current_revisions = self.get_revisions(lower) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 457, in get_revisions return sum([self.get_revisions(id_elem) for id_elem in id_], ()) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 457, in return sum([self.get_revisions(id_elem) for id_elem in id_], ())
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 479, in get_revisions
> return tuple(
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 480, in
> self._revision_for_ident(rev_id, branch_label)
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\revision.py", line 546, in _revision_for_ident
> raise ResolutionError(
> alembic.script.revision.ResolutionError: No such revision or branch 'bf20242a238f'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "F:\OnlyFans-7.4\start_ofd.py", line 62, in
> loop.run_until_complete(main())
> File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
> return future.result()
> File "F:\OnlyFans-7.4\start_ofd.py", line 46, in main
> api = await main_datascraper.start_datascraper(
> File "F:\OnlyFans-7.4\datascraper\main_datascraper.py", line 99, in start_datascraper
> paid_content = await module.paid_content_scraper(api, identifiers)
> File "F:\OnlyFans-7.4\modules\onlyfans.py", line 414, in paid_content_scraper
> await process_metadata(
> File "F:\OnlyFans-7.4\modules\onlyfans.py", line 662, in process_metadata
> Session, api_type, folder = main_helper.export_sqlite(
> File "F:\OnlyFans-7.4\helpers\main_helper.py", line 306, in export_sqlite
> db_helper.run_migrations(alembic_location, database_path)
> File "F:\OnlyFans-7.4\helpers\db_helper.py", line 48, in run_migrations
> command.upgrade(alembic_cfg, 'head')
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\command.py", line 294, in upgrade
> script.run_env()
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 490, in run_env
> util.load_python_file(self.dir, "env.py")
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
> module = load_module_py(module_id, path)
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\compat.py", line 184, in load_module_py
> spec.loader.exec_module(module)
> File "", line 790, in exec_module
> File "", line 228, in _call_with_frames_removed
> File "F:\OnlyFans-7.4\database\databases\messages\alembic\env.py", line 80, in
> run_migrations_online()
> File "F:\OnlyFans-7.4\database\databases\messages\alembic\env.py", line 74, in run_migrations_online
> context.run_migrations()
> File "", line 8, in run_migrations
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\environment.py", line 813, in run_migrations
> self.get_context().run_migrations(**kw)
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\migration.py", line 549, in run_migrations
> for step in self._migrations_fn(heads, self):
> File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\command.py", line 283, in upgrade
> return script._upgrade_revs(revision, rev) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 366, in _upgrade_revs return [ File "C:\Users\Sasquatch\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in **exit** self.gen.throw(type, value, traceback) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\script\base.py", line 203, in _catch_revision_errors compat.raise_(util.CommandError(resolution), from_=re) File "C:\Users\Sasquatch\AppData\Roaming\Python\Python39\site-packages\alembic\util\compat.py", line 296, in raise_
> raise exception
> alembic.util.exc.CommandError: Can't locate revision identified by 'bf20242a238f'

Do fresh install
