### ISSUE TITLE
Does auto_profile in .settings work?

### ISSUE THREAD

**Issue by taux1c** [DIGITALCRIMINAL/OnlyFans#1429]
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 57, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "/usr/src/app/helpers/main_helper.py", line 862, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

^CTraceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 57, in start_datascraper
    auths = choose_option(subscription_list, auto_profile_choice, True)
  File "/usr/src/app/helpers/main_helper.py", line 862, in choose_option
    if value.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

During handling of the above exception, another exception occurred:

**Comment by ThrowawayDane** [comment]
As the error also point out it want a digit so change 
"auto_profile_choice": "True",
over to:
"auto_profile_choice": "0",

then it will work just fine. :D

**Comment by taux1c** [comment]
Ah, I didn't think about passing it as a string. I tried as int but got an error so I tried a int in a list (because it was defaulted to a list.) I was tired and had just gotten home from work. lol

**Comment by taux1c** [comment]
It worked, thank you so much for the help. :)
