### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#144]
This is what I get when I run.

Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Traceback (most recent call last):
  File "d:\******\Desktop\OnlyFans-master\StartDatascraper.py", line 94, in <module>
    user_agent, app_token, auth_array)
  File "d:\******\Desktop\OnlyFans-master\modules\onlyfans.py", line 384, in create_session
    session.head("https://onlyfans.com")
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 315, in prepare
    self.prepare_cookies(cookies)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 572, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 142, in get_cookie_header
    jar.add_cookie_header(r)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\http\cookiejar.py", line 1358, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\http\cookiejar.py", line 1317, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object

**Comment by markt38** [comment]
exact same issue i have

**Comment by boulara** [comment]
same here too.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I messed up. Didn't push a commit I had hours ago. I finally ended up pushing it. It'll work now.
