### ISSUE TITLE
scraping error 

### ISSUE THREAD

**Issue by neuri4848** [DIGITALCRIMINAL/OnlyFans#1448]
Traceback (most recent call last):
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 930, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 159, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 786, in prepare_scraper
    master_set = await subscription.get_posts()
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 300, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 300, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by LunarPenguin** [comment]
Please provide some more context as to when this error is occuring. Right now we can only guess at the problem. 

I good start would be providing the python version your using, the OS your using and if you are running native or in a docker.

**Comment by neuri4848** [comment]
Current commit. Windows 10. Native. Python 3.9.5

Happens right when the scrape is supposed to start. Checked the user db file and the only thing thats in there is "stories" when there should be several pictures and a few videos

**Comment by DIGITALCRIMINAL** [comment]
Which user were you scraping

**Comment by neuri4848** [comment]
Gwengwiz

**Comment by bambooLoutre** [comment]
same here : 

Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "/usr/src/app/helpers/main_helper.py", line 906, in process_profiles
    auth = api.add_auth(json_auth)
  File "/usr/src/app/apis/onlyfans/onlyfans.py", line 45, in add_auth
    temp_auth_details = auth_details(options).upgrade_legacy(options)
  File "/usr/src/app/apis/onlyfans/classes/extras.py", line 9, in __init__
    self.cookie = cookie_parser(options.get("cookie", ""))
  File "/usr/src/app/apis/onlyfans/classes/extras.py", line 62, in __init__
    key, value = crumble.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by tocking** [comment]
@bambooLoutre the sess_id is the same in both the init and me responses for me - are they different for you?

**Comment by bambooLoutre** [comment]
> @bambooLoutre the sess_id is the same in both the init and me responses for me - are they different for you?

Didn't pay attention sorry :/ but i saw the cookie in INIT was way shorter than the one in the ME response so i assumed the first one wasn't right.

**Comment by neuri4848** [comment]
new commit didnt fix my issue

**Comment by tocking** [comment]
@neuri4848 @DIGITALCRIMINAL Still getting this error, even with the latest commit

**Comment by neuri4848** [comment]
yeah this issue hasnt been resolved. bambooloutre had a completely different issue than mine.

@DIGITALCRIMINAL
