### ISSUE TITLE
ValueError: not enough values

### ISSUE THREAD

**Issue by TheDonMaster** [DIGITALCRIMINAL/OnlyFans#1466]
First of all my apologies for the inconvenience, but I need some help. For some reason that I cant fathom I keep getting the same error. I've been trying to understand what's the cause of the issue, but after a few hours i'm not able to find it. So i'm getting the next error:

Site: 0 = onlyfans |
0
Traceback (most recent call last):
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\donny\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\helpers\main_helper.py", line 915, in process_profiles
    auth = api.add_auth(json_auth)
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\apis\onlyfans\onlyfans.py", line 45, in add_auth
    temp_auth_details = auth_details(options).upgrade_legacy(options)
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\apis\onlyfans\classes\extras.py", line 9, in __init__
    self.cookie = cookie_parser(options.get("cookie", ""))
  File "C:\Users\donny\Downloads\Python\OnlyFans-master\apis\onlyfans\classes\extras.py", line 62, in __init__
    key, value = crumble.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)

How can I fix this?

**Comment by J4k-The-Reaper** [comment]
yeah same here. i get same issue.

**Comment by TheDonMaster** [comment]
> yeah same here. i get same issue.
> 
> i am on Windows 11 Preview. if you are as well, i think the upgrade deleted the auth.json. had to redo it. works now.

Thanks, this fixed it for me! 👍
