### ISSUE TITLE
Now I have an issue. Stack trace in description.

### ISSUE THREAD

**Issue by fungastorba** [DIGITALCRIMINAL/OnlyFans#147]
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "J:\Scrapers\OnlyFans-3.7.3\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "J:\Scrapers\OnlyFans-3.7.3\modules\onlyfans.py", line 305, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "J:\Scrapers\OnlyFans-3.7.3\modules\onlyfans.py", line 249, in scrape_array
    file_path = reformat(directory[0][1], file_name,
  File "J:\Scrapers\OnlyFans-3.7.3\modules\helpers.py", line 41, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 213, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Am I missing some Python library?

**Comment by DIGITALCRIMINAL** [comment]
Pip install lxml

**Comment by fungastorba** [comment]
Ok, that solved this problem.

I decided to scrape again the content from one particular user in a new directory using the basic naming format ({date} {file_name}). I noticed that videos from DMs are missing - only 4 out of ca 14 are being scraped, meaning that they are not present in the metadata either. However, some of them were downloaded by the pre version 3.0 scraper (by some I mean those that were send to me at the time, however the most recent ones canno't be scraped because the old script cannot login in my account anymore ;(   )

**Comment by DIGITALCRIMINAL** [comment]
Hmm, I'll check again because several other people are having the same problem, but it's hard to fix it because I don't have access to their messages and account.

**Comment by fungastorba** [comment]
I understand that, and I wouldn't mind sharing my credentials, except this one has also my credit card information

**Comment by DIGITALCRIMINAL** [comment]
Hmm, hold on. Have you paid for any of the videos?

**Comment by fungastorba** [comment]
Some of them, most not. The 4 that are being scraped are paid, but there are 1 or 2 paid and more free that are missing.

**Comment by DIGITALCRIMINAL** [comment]
Hmm alright, what's the username you're trying to scrape?

**Comment by fungastorba** [comment]
evenink_cosplay

**Comment by DIGITALCRIMINAL** [comment]
Hmm alright, I'll try to fix it on my end first

**Comment by DIGITALCRIMINAL** [comment]
Ye, can't do it. Would you mind sending me your auth_id, auth_hash, sess and user-agent so I can try fix it?

If so, my email is datahoarders@protonmail.com
