### ISSUE TITLE
key error: author

### ISSUE THREAD

**Issue by neuri4848** [DIGITALCRIMINAL/OnlyFans#1475]
Scrape Processing
Name: gwengwiz
Type: Profile
Type: Stories
Processing Scraped Stories
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.11it/s]
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 788, in prepare_scraper
    master_set = await subscription.get_posts()
  File "C:\Users\userr\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\user\Downloads\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

Current commit. Windows 10. Native. Python 3.9.5

Happens right when the scrape is supposed to start. Checked the user db file and the only thing thats in there is "stories" when there should be several pictures and a few videos

**Comment by neuri4848** [comment]
@DIGITALCRIMINAL as ive said before, this error was never addressed, another person brought up another error and fixed that. The new commit didnt change anything..

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419
