### ISSUE TITLE
Error once it trys to start 

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#150]
Receiving this error and it just does nothing as far as saving.

```
user@asdfasdf:~/OnlyFans$ sudo python3 StartDatascraper.py 
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Welcome User
Traceback (most recent call last):
  File "StartDatascraper.py", line 100, in <module>
    session[0], app_token, session[2], me_api, auth_count)
  File "/home/user/OnlyFans/modules/onlyfans.py", line 473, in get_subscriptions
    result_date = datetime.fromisoformat(
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by ctrlcmdshft** [comment]
issue still exists after reinstalling and its being run with python 3.8
