### ISSUE TITLE
traceback error, No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by idontsmokegas** [DIGITALCRIMINAL/OnlyFans#1501]
after running the start.ofd.py file, i get this error.

Traceback (most recent call last):
  File "C:\Users\User\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\User\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\User\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "C:\Users\User\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

I have downloaded everything necessary from the requirements.txt

**Comment by LunarPenguin** [comment]
sqlalchemy has a very peculiar spelling make sure to spell it like SQLAlchemy.

So to install it you would do something like: `pip install -U SQLAlchemy`

**Comment by idontsmokegas** [comment]
did this, still getting the same error message.

**Comment by blade2005** [comment]
I assume you only have one version of python installed? If you run `pip --version` and `python --version` does the versions match?

**Comment by idontsmokegas** [comment]
turned out i had 3 versions of python, which was causing trouble with the requirements. got it up and running now. thanks!
