### ISSUE TITLE
Strange error. sometimes it gives me this, sometimes it just stays scraping forever

### ISSUE THREAD

**Issue by lanzjose** [DIGITALCRIMINAL/OnlyFans#153]
What could it be?
----------------------------------------
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\OpenSSL\SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\OpenSSL\SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (10054, 'WSAECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\modules\onlyfans.py", line 309, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\modules\onlyfans.py", line 197, in scrape_array
    y = json_request(session, link)
  File "C:\Users\Jose\Documents\GitHub\Onlyfans\OnlyFans\modules\helpers.py", line 205, in json_request
    r = session.request(method,link ,stream=stream)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))

**Comment by DIGITALCRIMINAL** [comment]
No idea how to fix this...

**Comment by DIGITALCRIMINAL** [comment]
The latest commit should catch this error
