### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by HoneyBadger116** [DIGITALCRIMINAL/OnlyFans#1537]
Traceback (most recent call last):
  File "D:\OF Rip\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\kioro\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OF Rip\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OF Rip\OnlyFans\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "D:\OF Rip\OnlyFans\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\OF Rip\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\OF Rip\OnlyFans\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "D:\OF Rip\OnlyFans\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "D:\OF Rip\OnlyFans\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "D:\OF Rip\OnlyFans\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by HoneyBadger116** [comment]
I have reran  pip install --upgrade --user -r requirements.txt
Also wiped everything and started fresh. I'm sure it's something simple I've overlooked.

**Comment by naodrej** [comment]
Try this workaround:
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231

**Comment by HoneyBadger116** [comment]
Thank you @naodrej However, I tired that work around and got a whole new issue. This issue seems to be only with some models. And I do have a sub to them with no issue on the website.


Traceback (most recent call last):
  File "D:\OF Rip\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\kioro\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OF Rip\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OF Rip\OnlyFans\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "D:\OF Rip\OnlyFans\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\OF Rip\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\OF Rip\OnlyFans\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "D:\OF Rip\OnlyFans\apis\onlyfans\classes\create_user.py", line 298, in get_posts
    results = await api_helper.scrape_endpoint_links(
  File "D:\OF Rip\OnlyFans\apis\api_helper.py", line 362, in scrape_endpoint_links
    media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]
UnboundLocalError: local variable 'media_set' referenced before assignment

**Comment by HoneyBadger116** [comment]
Thank you @naodrej 
That fixed the issue. Funny it only seemed to be an issue with some models and not all.
