### ISSUE TITLE
problem last 3 uppdates. 

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#154]
I get this error 3 last uppdates if i go back and use old works fine. what have i done wrong? Or have i find bug in the 3 last uppdates?

Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v3.7.5\StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 311, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Users\Marpa\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Marpa\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Marpa\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 246, in scrape_array
    file_path = reformat(directory[0][1], file_name,
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\helpers.py", line 41, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "C:\Users\Marpa\AppData\Local\Programs\Python\Python38\lib\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by fungastorba** [comment]
Pip install lxml

**Comment by Dalla-maker** [comment]
I have run that command and its installed. And it give me this error..

**Comment by DIGITALCRIMINAL** [comment]
You're installing it with the wrong Python version then.
`pip install lxml` is the fix; but install it for Python 3.8.
