### ISSUE TITLE
TypeError: object list can't be used in 'await' expression

### ISSUE THREAD

**Issue by PurpleDrank21** [DIGITALCRIMINAL/OnlyFans#1552]
I started getting this error a few days ago and I'm not quite sure what changed. 

I was running 7.2.1 and updated to 7.4.1 to see if that would  help. I've also tried blacklisting the account listed just before the error occurs with no effect. Currently running Python 3.9.6 with pip 21.2.3 with no other versions installed. All requirements are satisfied and up to date.

Scraping - [account] | 19 / 24
  0%|                                                                                                                                    | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Purple\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "D:\OnlyFans\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\Purple\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Purple\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Purple\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Purple\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression

**Comment by JohnFedorchak** [comment]
Same here. Just got this today. First time using the program so I have no previous experience to compare to.

**Comment by PurpleDrank21** [comment]
> Someone else has submitted this issue already. View the replies for a fix.

A link would be helpful as I haven't found the thread you're referencing.

**Comment by JohnFedorchak** [comment]
> > Someone else has submitted this issue already. View the replies for a fix.
> 
> A link would be helpful as I haven't found the thread you're referencing.

It's in the issues list multiple times. It even has the same title as yours. About 12 threads down.
[#1518 TypeError: object list can't be used in 'await' expression](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1518)

**Comment by PurpleDrank21** [comment]
> It's in the issues list multiple times. It even has the same title as yours. About 12 threads down.
> [#1518 TypeError: object list can't be used in 'await' expression](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1518)

Thank you.
