### ISSUE TITLE
Right after Profile selection 

### ISSUE THREAD

**Issue by andzzzzz** [DIGITALCRIMINAL/OnlyFans#1558]
Traceback (most recent call last):
  File "/home/andz/OnlyFans/./start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/andz/OnlyFans/./start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/home/andz/OnlyFans/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/home/andz/OnlyFans/modules/onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
TypeError: gather() takes 2 positional arguments but 5 were given

**Comment by LunarPenguin** [comment]
The first thing to check is if you have `tqdm` version `4.62.0` or greater installed and are running the latest version of the script.

**Comment by xxx-uploaded** [comment]
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = lisaxxxcross
0
Scrape Processing
Name: lisaxxxcross
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
100%|█████████████████████████████████████████████████████████████████████████████| 1.78M/1.78M [00:00<00:00, 9.96MB/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
No Posts Found.
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 999.12it/s]
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Scrape Completed

Archive Completed in 0.2 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |

does not load videos and photos

**Comment by LunarPenguin** [comment]
@xxx-uploaded your issue is different from the original issue so please open a new issue.
