### ISSUE TITLE
When Scraping Paid Content: TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by gw1345** [DIGITALCRIMINAL/OnlyFans#1566]
I get this after the script authenticates and it starts to scrape paid content. I ran the updater just in case, but I'm not able to get passed this. It was working a few days ago, not sure what happened.

Welcome **** | ****** 
Scraping Paid Content
Scraping -  ********* | 1 / 22
Scraping -  ********* | 2 / 22
Traceback (most recent call last):
  File "F:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans-master\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "F:\OnlyFans-master\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 74, in gather
    ifs = [wrap_awaitable(i, f) for i, f in enumerate(fs)]
TypeError: 'coroutine' object is not iterable

**Comment by americanseeder1865** [comment]
what version is your tpdm package?

**Comment by gw1345** [comment]
Update: it seemed to of fixed itself somehow... Guess it was just something on onlyfans' end?

**Comment by srw91** [comment]
I'm still having this issue, everything seems to be updated.
