### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by JbManny** [DIGITALCRIMINAL/OnlyFans#1583]
This happens whenever i try to scrape any type of content from some authors. I haven't found any similarities between the content creators.

```
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "D:\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "D:\OnlyFans\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\OnlyFans\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "D:\OnlyFans\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "D:\OnlyFans\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "D:\OnlyFans\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
```

**Comment by JbManny** [comment]
noted this was a know issue. Apologies for opening.
