### ISSUE TITLE
Error with individual subscription

### ISSUE THREAD

**Issue by Rakshae** [DIGITALCRIMINAL/OnlyFans#1587]
I'm getting this error on only one of my subscriptions (siswet19), all the rest scrape correctly. Is this a known issue or can someone direct me to fix it?

Running version 7.4.1, I know the file name says 6.4.3. I dumped all the non-site contents when moving to the new version.

```
Traceback (most recent call last):
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "<path>\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "F:\My Files\Video\NSFW\OnlyFans-6.4.3\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
```

**Comment by 7uAip6** [comment]
Try this:

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893866110

**Comment by Rakshae** [comment]
> 
> 
> Try this:
> 
> [#1419 (comment)](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893866110)

Worked like a charm, thank you for the assistance.
