### ISSUE TITLE
Program just hangs

### ISSUE THREAD

**Issue by AMTitan** [DIGITALCRIMINAL/OnlyFans#1609]
When I run it just hangs on 
![image](https://user-images.githubusercontent.com/29708070/130327629-28007852-78ac-4e28-9a56-4b04d821f042.png)
and that's it my auth.json is 
![image](https://user-images.githubusercontent.com/29708070/130327686-b1093b69-d11f-418f-9d8f-f0bfcfc684ee.png)
When I force quit it I get this
```py
Traceback (most recent call last):
  File "OnlyFans/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "OnlyFans/start_ofd.py", line 40, in main
    site_choice = str(input())
KeyboardInterrupt
```
I am using python version: `3.9.6`

I also tried from git and v7.4.1 both had the same hang

I am using Linux but that should not affect anything

My config.json is the same as defualt

**Comment by AMTitan** [comment]
I was dumb did not know I had to type 1
