### ISSUE TITLE
Auth loop on onlyfans but cookie settings are correct, also 10054 error

### ISSUE THREAD

**Issue by danj2k** [DIGITALCRIMINAL/OnlyFans#161]
This was working yesterday but is no longer working today, I tried redoing the cookie settings several times but getting the same result:

```
C:\python38\python.exe .\StartDatascraper.py
Auth (V1) Attempt 1/10
[name redacted]
Auth (V1) Attempt 2/10
[name redacted]
Auth (V1) Attempt 3/10
[name redacted]
Auth (V1) Attempt 4/10
[name redacted]
Auth (V1) Attempt 5/10
[name redacted]
Auth (V1) Attempt 6/10
[name redacted]
Auth (V1) Attempt 7/10
[name redacted]
Auth (V1) Attempt 8/10
[name redacted]
Auth (V1) Attempt 9/10
[name redacted]
Auth (V1) Attempt 10/10
[name redacted]
Auth (V2) Attempt 1/10
[name redacted]
Auth (V2) Attempt 2/10
[name redacted]
Auth (V2) Attempt 3/10
[name redacted]
Auth (V2) Attempt 4/10
[name redacted]
Auth (V2) Attempt 5/10
[name redacted]
Auth (V2) Attempt 6/10
[name redacted]
Auth (V2) Attempt 7/10
[name redacted]
Auth (V2) Attempt 8/10
[name redacted]
Auth (V2) Attempt 9/10
[name redacted]
Auth (V2) Attempt 10/10
[name redacted]
You're not subscribed to any users.
Auth (V1) Attempt 1/10
[name redacted]
Auth (V1) Attempt 2/10
[name redacted]
Auth (V1) Attempt 3/10
[name redacted]
Auth (V1) Attempt 4/10
[name redacted]
Auth (V1) Attempt 5/10
[name redacted]
Auth (V1) Attempt 6/10
[name redacted]
Auth (V1) Attempt 7/10
[name redacted]
Auth (V1) Attempt 8/10
[name redacted]
Auth (V1) Attempt 9/10
[name redacted]
Auth (V1) Attempt 10/10
[name redacted]
Auth (V2) Attempt 1/10
[name redacted]
Auth (V2) Attempt 2/10
[name redacted]
Auth (V2) Attempt 3/10
[name redacted]
Auth (V2) Attempt 4/10
[name redacted]
Auth (V2) Attempt 5/10
[name redacted]
Auth (V2) Attempt 6/10
[name redacted]
Auth (V2) Attempt 7/10
[name redacted]
Auth (V2) Attempt 8/10
[name redacted]
Auth (V2) Attempt 9/10
[name redacted]
Auth (V2) Attempt 10/10
[name redacted]
You're not subscribed to any users.
Auth (V1) Attempt 1/10
[name redacted]
Auth (V1) Attempt 2/10
[name redacted]
Auth (V1) Attempt 3/10
[name redacted]
Auth (V1) Attempt 4/10
[name redacted]
Auth (V1) Attempt 5/10
[name redacted]
Auth (V1) Attempt 6/10
[name redacted]
Auth (V1) Attempt 7/10
[name redacted]
Auth (V1) Attempt 8/10
[name redacted]
Auth (V1) Attempt 9/10
[name redacted]
Auth (V1) Attempt 10/10
[name redacted]
Auth (V2) Attempt 1/10
[name redacted]
Auth (V2) Attempt 2/10
[name redacted]
Auth (V2) Attempt 3/10
[name redacted]
Auth (V2) Attempt 4/10
[name redacted]
Auth (V2) Attempt 5/10
[name redacted]
Auth (V2) Attempt 6/10
[name redacted]
Auth (V2) Attempt 7/10
[name redacted]
Auth (V2) Attempt 8/10
[name redacted]
Auth (V2) Attempt 9/10
[name redacted]
Auth (V2) Attempt 10/10
[name redacted]
You're not subscribed to any users.
```
I am subscribed to users though?

Also last night instead of running to completion, it crapped out with the following error (which is why I was retrying this morning):
```
Traceback (most recent call last):
  File "C:\python38\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\python38\lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\python38\lib\socket.py", line 669, in readinto
  File "C:\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\requests\models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\python38\lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\python38\lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\python38\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\StartDatascraper.py", line 150, in <module>
    x.download_media(*arg)
  File "D:\Downloads\OnlyFans-master\modules\onlyfans.py", line 365, in download_media
    pool.starmap(download, product(
  File "C:\python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\Downloads\OnlyFans-master\modules\onlyfans.py", line 351, in download
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\python38\lib\site-packages\requests\models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
application.log is empty, so I'm not able to attach a log file.

I notice that the actual cookie has some parameters which don't appear to be mentioned in the configuration file, notably `auth_uniq_<id>` (where `<id>` is replaced by the auth_id) and `fp`, is it possible that Onlyfans has upgraded their security with additional authentication requirements?

**Comment by DIGITALCRIMINAL** [comment]
Do you have 2FA on?

**Comment by danj2k** [comment]
> Do you have 2FA on?

Yes, does it need to be turned off for the script to work? But then why did it work yesterday?

**Comment by DIGITALCRIMINAL** [comment]
Dunno tbh; if you refresh the page after you run the script; you're session token would become invalid because of 2FA.

**Comment by danj2k** [comment]
I just logged back in to Onlyfans, and out of the parameters to specify in config.json the only one that has changed is auth_hash. All the others are still the same, which is why I was wondering if the extra auth_uniq and fp cookie parts might be needed as well.

**Comment by danj2k** [comment]
I bodged in the fp and auth_uniq parts into the appropriate areas of the script and now it works again.

In StartDataScraper.py I added:

```
                fp = json_auth['fp']
                auth_uniq = json_auth['auth_uniq']
```

and

```
                auth_array["fp"] = fp
                auth_array["auth_uniq"] = auth_uniq
```

In onlyfans.py I changed:

```
    auth_cookies = [
        {'name': 'auth_id', 'value': auth_array["auth_id"]},
        {'name': 'auth_hash', 'value': auth_array["auth_hash"]},
		{'name': 'fp', 'value': auth_array["fp"]},
		{'name': 'auth_uniq_'+auth_array["auth_id"], 'value': auth_array["auth_uniq"]}
    ]
```

And in config.json I added fp and auth_uniq under the "auth" section of onlyfans.

**Comment by DIGITALCRIMINAL** [comment]
Thank you. Are you sure you need the FP there? Before all I had to do was add the auth_uniq

If you could make a new merge; I'd be happy to approve it into the script and enhance it from there.
