### ISSUE TITLE
error in some users (KeyError: 'author')

### ISSUE THREAD

**Issue by Sirk6** [DIGITALCRIMINAL/OnlyFans#1611]
only in some user i recived this error:
apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by bobsage123** [comment]
Me too.

```
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "I:\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "I:\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "I:\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "I:\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "I:\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "I:\OnlyFans-7.4.1\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "I:\OnlyFans-7.4.1\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "I:\OnlyFans-7.4.1\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "I:\OnlyFans-7.4.1\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
```

**Comment by LunarPenguin** [comment]
look here #1419 and here #1588

**Comment by howdothiswork** [comment]
this workaround does not work for me!

**Comment by vacuran** [comment]
> this workaround does not work for me!

What error did you get after making the update?

**Comment by Sirk6** [comment]
> look here #1419 and here #1588

Work for me, thanks
