### ISSUE TITLE
Error while scraping

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#164]
I get this error after it scraps all the subscribed users.
Traceback (most recent call last):
  File "d:\******\Desktop\OnlyFans-master\StartDatascraper.py", line 150, in <module>
    x.download_media(*arg)
  File "d:\******\Desktop\OnlyFans-master\modules\onlyfans.py", line 362, in download_media
    pool = ThreadPool()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 194, in __init__
    self._task_handler.start()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by DIGITALCRIMINAL** [comment]
What's your CPU

**Comment by elwoodflame** [comment]
Intel i7-6700Q @2.60ghz 12 gb ram 64 bit

**Comment by DIGITALCRIMINAL** [comment]
Does it happen everytime?

**Comment by daniespejel** [comment]
Same problem here since last week, it's start suddenly, one day was working fine and next one this weird error.

Traceback (most recent call last):
  File "StartDatascraper.py", line 152, in <module>
    x.download_media(*arg)
  File "E:\users\user\python-venv\of-scrapper\OnlyFans\modules\onlyfans.py", line 362, in download_media
    pool = ThreadPool()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 194, in __init__
    self._task_handler.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread


Scrapping process it's ok, but when it starts with downloads crash, only happens when i select all names on onlyfans, (its the only service i have, 11names) could do 3 or 5 of them and then crash, but i can do one by one manually whit out problems.

Processor Intel Core 17-7500U, 16GB RAM, Windows 10 Pro with latest updates

anything you need i'm available to test or document ;)

**Comment by elwoodflame** [comment]
Every time i select all. If i do them 1 at a time it works fine.

**Comment by DIGITALCRIMINAL** [comment]
Have you tried the latest commit; was updated 20hrs ago

**Comment by daniespejel** [comment]
> 
> 
> Have you tried the latest commit; was updated 20hrs ago

Just did it, same error

Traceback (most recent call last):
  File "StartDatascraper.py", line 150, in <module>
    x.download_media(*arg)
  File "E:\userpython-venv\of-scrapper\OnlyFans\modules\onlyfans.py", line 369, in download_media
    pool = ThreadPool()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 51, in start
    threading.Thread.start(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap,

**Comment by elwoodflame** [comment]
I tried it . I still have the same  issue. I noticed this pops up while its scraping.

Scraping [video | stream | gif]. Should take less than a minute.
C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4\__init__.py:294: UserWarning: "b'...  '" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
Type: Messages

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit
