### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by looeyWei** [DIGITALCRIMINAL/OnlyFans#1648]
when I start, input `0`, then this error apper, how to solve this error.

python start_ofd.py
Site: 0 = onlyfans |
0
Traceback (most recent call last):
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "D:\app\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\helpers\main_helper.py", line 915, in process_profiles
    auth = api.add_auth(json_auth)
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\apis\onlyfans\onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\apis\onlyfans\classes\create_auth.py", line 44, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "C:\Users\congw\Downloads\Compressed\OnlyFans-7.4.1\OnlyFans-7.4.1\apis\api_helper.py", line 99, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\congw\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\app\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\app\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by LunarPenguin** [comment]
this to me seems like an internet issue, please try again and report back if the issue persists

**Comment by looeyWei** [comment]
@LunarPenguin  Yes, you are right ! Because I opened VPN. But a new problem appeared. Anyway, thank you very much ！ I'll look for a solution to the new problem
