### ISSUE TITLE
error randomly appeared

### ISSUE THREAD

**Issue by jamesp132** [DIGITALCRIMINAL/OnlyFans#1667]
Hi, 

i am randomy now receiving this error and unable to pass, if anyone has any ideas please can you let me know.

Traceback (most recent call last):
  File "\\mycloudpr4100\OF\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "\\mycloudpr4100\OF\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "\\mycloudpr4100\OF\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "\\mycloudpr4100\OF\OnlyFans-7.4.1\helpers\main_helper.py", line 910, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Trailing data

**Comment by LunarPenguin** [comment]
Check if your `auth.json` file is valid `json` using a site like [this](https://jsonlint.com/).

You could also supply a (redacted) version of your `auth.json` file so i can have a look for myself
