### ISSUE TITLE
Got a fix for this error...???

### ISSUE THREAD

**Issue by undacovabrutha** [DIGITALCRIMINAL/OnlyFans#1674]
When I get to the point where is says "0 = Onlyfans", I hit the 0 and enter.  I get the error below in return.  Any fix help would be greatly appreciated.  Thanks!

Traceback (most recent call last):
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd2\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd2\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd2\datascraper\main_datascraper.py", line 57, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd2\helpers\main_helper.py", line 664, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value

**Comment by undacovabrutha** [comment]
I installed the updated Onlyfans scraper and pretty much the same error again....

Traceback (most recent call last):
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd7.4.1\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\bates_pu5jag3\Downloads\OnlyFansNerd7.4.1\helpers\main_helper.py", line 910, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value

**Comment by Macmasteri** [comment]
Just before it worked fine. Saw some popup on OF with Internal Error and then this:

Welcome xx| xx
```
Scraping Paid Content
Traceback (most recent call last):
  File "xxx start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/xxx/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "xxx/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "xxx/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "xxx/modules/onlyfans.py", line 322, in paid_content_scraper
    for paid_content in paid_contents:
TypeError: 'error_details' object is not iterable

```

**Comment by undacovabrutha** [comment]
@DIGITALCRIMINAL I'll give you access to fix.  Thanks!
