### ISSUE TITLE
File "C:\temp\OnlyFans DataScraper v3.7.5\StartDatascraper.py", line 147, in <module>     result = x.start_datascraper(

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#172]
From Last night i get this error on every onlyfans

Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v3.7.5\StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 311, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\temp\OnlyFans DataScraper v3.7.5\modules\onlyfans.py", line 213, in scrape_array
    size = source["size"]
KeyError: 'size'

how do i fix this problem?

**Comment by Dalla-maker** [comment]
other error in lines "onlyfans.py"  have not make any change.. Just retry
--
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\temp\OnlyFans-master\StartDatascraper.py", line 148, in <module>
    result = x.start_datascraper(
  File "C:\temp\OnlyFans-master\modules\onlyfans.py", line 59, in start_datascraper
    results = media_scraper(
  File "C:\temp\OnlyFans-master\modules\onlyfans.py", line 359, in media_scraper
    x = pool.starmap(scrape_array, product(
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ellirhc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\temp\OnlyFans-master\modules\onlyfans.py", line 229, in scrape_array
    size = source["size"]
KeyError: 'size'

**Comment by DIGITALCRIMINAL** [comment]
Download new release
