### ISSUE TITLE
Error during Scrape

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINAL/OnlyFans#173]
I seem to keep getting the same error during scraping. there are also no files being saved other than Metadata files during the scrape.

> Traceback (most recent call last):
  File "E:\OnlyFans-master\OnlyFans-master\StartDatascraper.py", line 148, in <module>
    result = x.start_datascraper(
  File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 59, in start_datascraper
    results = media_scraper(
  File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 359, in media_scraper
    x = pool.starmap(scrape_array, product(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 229, in scrape_array
    size = source["size"]
KeyError: 'size'

**Comment by DIGITALCRIMINAL** [comment]
Download new release
