### ISSUE TITLE
Python error with latest commit

### ISSUE THREAD

**Issue by writerinthedark** [DIGITALCRIMINAL/OnlyFans#174]
I've started getting an error and I'm not sure what it's refering to. I'm using the latest commit and have made sure cookies/auth/useragent/etc are up to date. I've replaced personal information with generic test in **.

Auth (V1) Attempt 1/10
Welcome *name*
Names: 0 = All | 1 = *modelname* | 2 = *modelname* | 3 = *modelname* | 4 = *modelname* | 5 = *modelname* | 6 = *modelname* | 7 = *modelname* | 8 = *modelname* | 9 = *modelname* | 10 = *modelname* | 11 = *modelname*
Scrape Processing
Name: *modelname*
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "F:\*path*\StartDatascraper.py", line 148, in <module>
    result = x.start_datascraper(
  File "F:\*path*\onlyfans.py", line 60, in start_datascraper
    results = media_scraper(
  File "F:\*path*\onlyfans.py", line 376, in media_scraper
    x = pool.starmap(scrape_array, product(
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\*path*\onlyfans.py", line 264, in scrape_array
    file_path = reformat(directory[0][1], file_name,
  File "F:\*path*\", line 40, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "C:\Users\*user*\AppData\Roaming\Python\Python38\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by DIGITALCRIMINAL** [comment]
> pip install lxml
