### ISSUE TITLE
string match error

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#1781]
After the new update (to add x-bc) I updated my install from the repository, updated the requirements and I am getting this error:

```
d:\OneDrive\cb\grabOF\OnlyFans>python start_ofd.py
Traceback (most recent call last):
  File "d:\OneDrive\cb\grabOF\OnlyFans\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "d:\OneDrive\cb\grabOF\OnlyFans\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax
``` 

before running it, I did a 

```
pip install --upgrade -r requirements.txt
```

any suggestions?

**Comment by mwald84** [comment]
Same with the release: 

```
d:\OneDrive\cb\grabOF\OnlyFans-7.6.1>python start_ofd.py
Traceback (most recent call last):
  File "d:\OneDrive\cb\grabOF\OnlyFans-7.6.1\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "d:\OneDrive\cb\grabOF\OnlyFans-7.6.1\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax
```

I'm running it on Windows 10 with python 3.9.4

**Comment by mwald84** [comment]
Ok, I see it now. It's probably Python version. I didn't notice the change. Thanks.

**Comment by DIGITALCRIMINALS** [comment]
Ye you need Python 3.10
