### ISSUE TITLE
Auth 404'ed - v7.6.1 - Clean Install

### ISSUE THREAD

**Issue by npine88** [DIGITALCRIMINAL/OnlyFans#1803]
I'm getting an Auth 404'ed error on the latest build. I've done a fresh install / build using the generated auth/config files. Any ideas how to fix this?

```
pip 21.3.1 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)
Python 3.10.1

REDACTED@REDACTEDs-iMac OnlyFans-7.6.1 % python3 start_ofd.py
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Auth 404'ed
Auth (V1) Attempt 4/10
Auth 404'ed
Auth (V1) Attempt 5/10
Auth 404'ed
Auth (V1) Attempt 6/10
Auth 404'ed
Auth (V1) Attempt 7/10
Auth 404'ed
Auth (V1) Attempt 8/10
Auth 404'ed
Auth (V1) Attempt 9/10
Auth 404'ed
Auth (V1) Attempt 10/10
Auth 404'ed
Traceback (most recent call last):
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 88, in account_setup
    authed = await auth.login()
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/apis/onlyfans/classes/create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

^CTraceback (most recent call last):
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/modules/onlyfans.py", line 88, in account_setup
    authed = await auth.login()
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/apis/onlyfans/classes/create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/REDACTED/Downloads/OnlyFans-7.6.1/start_ofd.py", line 107, in <module>
    input()
KeyboardInterrupt

```

**Comment by npine88** [comment]
FYI, running this command fixed the issue:
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1316#issuecomment-862201562
