### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by RAR98** [DIGITALCRIMINAL/OnlyFans#1821]
I got this error everytime, i launch "start_ofd.py" 

This line appear in the python window
Site: 0 = onlyfans |
i then press enter and get this :
Traceback (most recent call last):
  File "C:\Users\redaa\Downloads\OnlyFans-7.4.1\start_ofd.py", line 59, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\redaa\Downloads\OnlyFans-7.4.1\start_ofd.py", line 40, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by Alex350123** [comment]
I meet the same problem here. Have you worked it out? Any solutions?

**Comment by VhenFrey** [comment]
how did you fix this issue?
