### ISSUE TITLE
I get this error when scraping all

### ISSUE THREAD

**Issue by elwoodflame** [DIGITALCRIMINAL/OnlyFans#186]
2020-04-01 17:41:04,545 ERROR errors can't start new thread
Traceback (most recent call last):
  File "d:\******\Desktop\OnlyFans-master\StartDatascraper.py", line 152, in <module>
    x.download_media(*arg)
  File "d:\******\Desktop\OnlyFans-master\modules\onlyfans.py", line 474, in download_media
    pool = ThreadPool()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\dummy\__init__.py", line 51, in start
    threading.Thread.start(self)
  File "C:\Users\******\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by DIGITALCRIMINAL** [comment]
How many models are you subbed to?

**Comment by elwoodflame** [comment]
I currently have 6 subscription's.

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by elwoodflame** [comment]
Will try and let you know.
