### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid control character at: line 19 column 139 (char 643)

### ISSUE THREAD

**Issue by acetheplace** [DIGITALCRIMINAL/OnlyFans#188]
downloaded, editing the auth settings, ran 'pip install -r requirements.txt',
then i get this error

C:\Users\shadaloo\Downloads\OnlyFans-master>python StartDatascraper.py
Traceback (most recent call last):
  File "StartDatascraper.py", line 2, in <module>
    import modules.onlyfans as onlyfans
  File "C:\Users\shadaloo\Downloads\OnlyFans-master\modules\onlyfans.py", line 2, in <module>
    from modules.helpers import get_directory, json_request, reformat, format_directory, format_media_set, export_archive, format_image, check_for_dupe_file, setup_logger
  File "C:\Users\shadaloo\Downloads\OnlyFans-master\modules\helpers.py", line 16, in <module>
    json_config = json.load(open(path))
  File "C:\Users\shadaloo\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\shadaloo\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shadaloo\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shadaloo\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 19 column 139 (char 643)

**Comment by DIGITALCRIMINAL** [comment]
Then there's something wrong with your authentication config. It's not formatted properly.

**Comment by acetheplace** [comment]
thanks for your reply -- sorry for all the spam and garbage mails(that was
my morning and one of the first things i did still drinking coffee), i will
try again

**Comment by sirdark01** [comment]
Don't worry about spam, I deleted them, it's not for me?) Reverend, help me format my account correctly, I can't understand) confirm email or what? just i think  I thought that I mixed up something with the commands in the CMD terminal?  sry me, this a lot of questions
 
 
--
Knight

**Comment by sirdark01** [comment]
the problem is still the same, we can scrape all accounts that are present on onlyfans or only those that are open?
 
 
--
Knight

**Comment by sirdark01** [comment]
what should I do?
 
 
--
Knight

**Comment by DIGITALCRIMINAL** [comment]
Buy the subscription?

**Comment by sirdark01** [comment]
and there are no more options?

**Comment by DIGITALCRIMINAL** [comment]
No. Just buy the subscription and use my scraper to download the files. Stop spamming the thread.

**Comment by sirdark01** [comment]
thank you, sry(
