### ISSUE TITLE
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

### ISSUE THREAD

**Issue by qmzn12** [DIGITALCRIMINAL/OnlyFans#1886]
When I  click enter after completing auth.json  , the following error message appears. What is the problem and how to solve it?

Traceback (most recent call last):
  File "D:\game\OnlyFans-master\start_ofd.py", line 16, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "D:\game\OnlyFans-master\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "D:\game\OnlyFans-master\modules\onlyfans.py", line 13, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "D:\game\OnlyFans-master\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\qmzn533\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

**Comment by n00mkrad** [comment]
Why did you close this?

I have the same problem.

**Comment by n00mkrad** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1884#issuecomment-1170601961

this worked for me.
