### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by qmzn12** [DIGITALCRIMINAL/OnlyFans#1887]
How could I solve this?

D:\GamePP Wonderful Moment\OnlyFans-master\.profiles\OnlyFans\default\auth.json has been created. Fill in the relevant details and then press enter to continue.
Site: 0 = onlyfans |

Traceback (most recent call last):
  File "D:\GamePP Wonderful Moment\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\qmzn533\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\GamePP Wonderful Moment\OnlyFans-master\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by VhenFrey** [comment]
how did you fix this issue?
