### ISSUE TITLE
maximum recursion depth

### ISSUE THREAD

**Issue by icemouton** [DIGITALCRIMINAL/OnlyFans#1889]
The script had been running fine for months then a few days ago (July 8th) it stopped working I just noticed today. Error is maximum recursion depth.
Tried pulling the latest version first to see if it fixes it.. it doesn't.

```
Traceback (most recent call last):
  File "/secure/src/OnlyFans/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/secure/src/OnlyFans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/media/DATANAS-02/secure/src/OnlyFans/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/media/DATANAS-02/secure/src/OnlyFans/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/media/DATANAS-02/secure/src/OnlyFans/helpers/main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "/media/DATANAS-02/secure/src/OnlyFans/modules/module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "/media/DATANAS-02/secure/src/OnlyFans/modules/module_streamliner.py", line 238, in prepare_scraper
    unrefined_set = await subscription.get_messages()
  File "/media/DATANAS-02/secure/src/OnlyFans/apis/fansly/classes/user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "/media/DATANAS-02/secure/src/OnlyFans/apis/fansly/classes/user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  File "/media/DATANAS-02/secure/src/OnlyFans/apis/fansly/classes/user_model.py", line 406, in get_messages
    results2 = await self.get_messages(
  [Previous line repeated 960 more times]
  File "/media/DATANAS-02/secure/src/OnlyFans/apis/fansly/classes/user_model.py", line 399, in get_messages
    results = api_helper.merge_dictionaries(results)
  File "/media/DATANAS-02/secure/src/OnlyFans/apis/api_helper.py", line 599, in merge_dictionaries
    final_dictionary: dict[str, Any] = merge({}, *items, strategy=Strategy.ADDITIVE)  # type: ignore
  File "/home/username/.local/lib/python3.10/site-packages/mergedeep/mergedeep.py", line 100, in merge
    return reduce(partial(_deepmerge, strategy=strategy), sources, destination)
  File "/home/username/.local/lib/python3.10/site-packages/mergedeep/mergedeep.py", line 87, in _deepmerge
    dst[key] = deepcopy(src[key])
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by icemouton** [comment]
After writing this I had an idea... I was scrapping both fansly and OF and when I removed fansly from the array and it started working as usual...

**Comment by LunarPenguin** [comment]
This version of the program is dead. please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)
