### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by blairg23** [DIGITALCRIMINAL/OnlyFans#1898]
GIT commit SHA: `85aec02065f6065c5b99b6caedec20ce947ffc2d`
Python Version: Python 3.10

```
Traceback (most recent call last):
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/helpers/main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/modules/module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/modules/module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/modules/onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/apis/onlyfans/classes/user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results]
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/apis/onlyfans/classes/user_model.py", line 283, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "/mnt/d/pr0ns/programs/scrapers/OnlyFans/apis/onlyfans/classes/hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by blairg23** [comment]
Sorry fix is here: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518
