### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by Septan** [DIGITALCRIMINAL/OnlyFans#192]
```
628 ERROR errors [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)
 Tries: 0
Traceback (most recent call last):
  File "D:\github\OnlyFans-3.9\modules\onlyfans.py", line 436, in download
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\Python38\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Python38\lib\site-packages\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Python38\lib\site-packages\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)
```
I got this during scraping of images.

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit.
