### ISSUE TITLE
Keep getting this error when I run the script. Have reinstalled it multiple times.

### ISSUE THREAD

**Issue by GeasLwo** [DIGITALCRIMINAL/OnlyFans#1923]
Traceback (most recent call last):
  File "F:\a\Stuff\of\start_ofd.py", line 16, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "F:\a\Stuff\of\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "F:\a\Stuff\of\modules\onlyfans.py", line 13, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "F:\a\Stuff\of\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\Seiju\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

**Comment by LunarPenguin** [comment]
It seems as the script is trying to start your webbrowser (which i guess is Opera) but it has no way to control that browser. but anyway, you should go [here](https://github.com/DIGITALCRIMINALS/OnlyFans) which is a continuation/fork of this repo by the original maintainer and this repo is now dead/stale.

**Comment by GeasLwo** [comment]
> 

Funny thing is I don't even have Opera installed. I figured there must be a new version of this. Thanks for linking it and I'll give a it a try.

**Comment by LunarPenguin** [comment]
> Funny thing is I don't even have Opera installed. I figured there must be a new version of this. Thanks for linking it and I'll give a it a try.

I can only infer so much from a stacktrace so i have no idea what caused this. If you successfully move over to the new version please consider closing this issue, so we can keep the issue list fairly clean.

**Comment by GeasLwo** [comment]
Traceback (most recent call last):
  File "F:\a\Stuff\OnlyFans-7.6.1\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "F:\a\Stuff\OnlyFans-7.6.1\helpers\main_helper.py", line 823
    match options_type:
          ^
SyntaxError: invalid syntax

I upgraded to the new version and now get this upon starting the script.

**Comment by GeasLwo** [comment]
Got it working. Had to install all the modules manually using `pip install 'modulenamehere'` and running Python 3.10 . Closing this.
