### ISSUE TITLE
Get this error when scraping

### ISSUE THREAD

**Issue by Jassy7** [DIGITALCRIMINAL/OnlyFans#193]
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\Users\bipu94860\Downloads\OnlyFans-3.7.5\OnlyFans-3.7.5\StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "C:\Users\bipu94860\Downloads\OnlyFans-3.7.5\OnlyFans-3.7.5\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "C:\Users\bipu94860\Downloads\OnlyFans-3.7.5\OnlyFans-3.7.5\modules\onlyfans.py", line 311, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "C:\Users\bipu94860\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\bipu94860\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\bipu94860\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\bipu94860\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\bipu94860\Downloads\OnlyFans-3.7.5\OnlyFans-3.7.5\modules\onlyfans.py", line 213, in scrape_array
    size = source["size"]
KeyError: 'size'

**Comment by custardcream123** [comment]
Same issue using Firefox but with 2 girls both have over 1,000 items so dont know if hits a limit 
@katie71cams 1404 photos and 713 vids
@nymphopixie 2119 photos and 437 vids
I have 7 active subscription
Thanks 
Cust ;-(

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit.
