### ISSUE TITLE
get  this error. after update 3.8 too 3.9

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#195]
2020-04-05 15:48:38,291 ERROR errors HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCA4DD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\dkal\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCA4DD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCA4DD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v3.9\modules\helpers.py", line 185, in json_request
    r = session.request(method, link, stream=stream)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCA4DD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-04-05 15:48:50,604 ERROR errors HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCBEDAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCBEDAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCBEDAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v3.9\modules\helpers.py", line 185, in json_request
    r = session.request(method, link, stream=stream)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Johodu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_155448.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019ACCBEDAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by DIGITALCRIMINAL** [comment]
Thank you for this. Seems like OF has a new URL for delivering videos.
What model are you trying to scrape?

**Comment by Dalla-maker** [comment]
I send you model name in email.. Im not posting name here.. Hope that ok

**Comment by P0rr** [comment]
Have send email now.. Is there any info  i can send you that can help make it work ?

**Comment by DIGITALCRIMINAL** [comment]
> I send you model name in email.. Im not posting name here.. Hope that ok

I need the exact username of the model that caused this error

**Comment by Dalla-maker** [comment]
there username is in the email i did send you.

**Comment by DIGITALCRIMINAL** [comment]
You sent four models instead of one..... You're telling me all models cause the "us.upload.onlyfans.com" error?

**Comment by Dalla-maker** [comment]
yes they give me that error... And no other model have update video cant check if i get error on them..

**Comment by DIGITALCRIMINAL** [comment]
Hmm, strange because it's working for me. Have you downloaded the latest commit?

**Comment by Dalla-maker** [comment]
did get downloaded the latest last night. i get reget it now and see if it start working for me

**Comment by DIGITALCRIMINAL** [comment]
Download this
https://github.com/DIGITALCRIMINAL/OnlyFans/archive/master.zip

**Comment by Dalla-maker** [comment]
that zip file give me this error 

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.upload.onlyfans.com', port=443): Max retries exceeded with url: /files/20190605_162254.mp4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D5AE80BF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by DIGITALCRIMINAL** [comment]
What username are you scraping...

**Comment by Dalla-maker** [comment]
Sallydangeloxxx

**Comment by DIGITALCRIMINAL** [comment]
Weird, it's working for me. Have you purchased any of her content?

**Comment by DIGITALCRIMINAL** [comment]
Nvm it's not working for me; I see the error. Thanks.

**Comment by Dalla-maker** [comment]
Hope its a error you can fix. And thanks for see the error

**Comment by DIGITALCRIMINAL** [comment]
Download and try now
https://github.com/DIGITALCRIMINAL/OnlyFans/archive/master.zip

**Comment by Dalla-maker** [comment]
Work in a way i think now.. i get preview.jpg not video mp4

https://cdn2.onlyfans.com/files/g/gt/gtk/gtkuvqst5kdsl6oialmw6v2lrfxhbuyr1559766870/preview.jpg?Tag=1&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvZ1wvZ3RcL2d0a1wvZ3RrdXZxc3Q1a2RzbDZvaWFsbXc2djJscmZ4aGJ1eXIxNTU5NzY2ODcwXC9wcmV2aWV3LmpwZz9UYWc9MSIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4NjYzODUxMX0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIxOTQuNzEuMjE3LjY4XC8zMiJ9fX1dfQ__&Signature=f21tkQXtUYMgikrjbeV34~NM2HiAau4Fw4uIW-Wfu8kMV1tKGnFH0i1SV6x0zza5SIEYOB7eZucMM92cQYOPbkzUma2j0Dk2XY47fCbUaWpq-S4~ZyPD-ecbtym0rj56fwPTATYqV0TjRyCVdCea2b31isObGDblV6ns26i0iVe6x1Fa3~brk9rRzRUazAH0ogmhVxpBnsfgIMwweGB2DrdYIsKHYAWqEFBx8UP6MqafjZV~66jFtJPfJqLjdioaWsBSBe3Epcp-CmC-56OhgASlylhIDJy4iQsrA4cIVj4eOeiLgrKnC1wWq0fRF6egGbqoadMMxJ2ZTNo~xAieuQ__&Key-Pair-Id=APKAJZU4IULC2OKULHGA
2020-04-10 22:56:42,349 INFO downloads Path: C:\***\********\sites/onlyfans/sallydangeloxxx/Posts/Videos/preview.jpg

**Comment by Dalla-maker** [comment]
Name: theonlykiaramia

   raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.convert.onlyfans.com', port=443): Max retries exceeded with url: /upload/9bbb4989dda65c2d900cf5e606a22b71751643.jpeg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000028720B06340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Download Processing

**Comment by DIGITALCRIMINAL** [comment]
Thanks for this. Try the latest commit.

**Comment by Dalla-maker** [comment]
I am not home now. Will try it when I'm back home later today

**Comment by Dalla-maker** [comment]
Sorry it took longer than expected before I got home. Have tried all models I follow onlyfans and latest zip file you asked me to try. Works great pictures and video as well as audio. Thank you so much for arranging quickly so it worked for me again
