### ISSUE TITLE
Error when scraping

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINAL/OnlyFans#197]
I seem to be getting this issue mainly when scraping models with a decent amount of content.
 the error is attached in a text file
[error.txt](https://github.com/DIGITALCRIMINAL/OnlyFans/files/4461741/error.txt)

**Comment by jimmothy-beep** [comment]
I completely re-downloaded and setup the tool this morning thinking that I may have missed a version and its still coming up with this
`2020-04-11 11:39:27,476 ERROR errors Unterminated string starting at: line 1 column 932879 (char 932878)
Traceback (most recent call last):
  File "E:\OnlyFans-master\OnlyFans-master\modules\helpers.py", line 191, in json_request
    return json.loads(r.text)
  File "C:\Users\James Robertson\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\James Robertson\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\James Robertson\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 932879 (char 932878)`

**Comment by DIGITALCRIMINAL** [comment]
Commits are different from release.
Download this
https://github.com/DIGITALCRIMINAL/OnlyFans/archive/master.zip
