### ISSUE TITLE
KeyError: 'size'

### ISSUE THREAD

**Issue by user123456789101112** [DIGITALCRIMINAL/OnlyFans#198]
```
Type: Messages
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "StartDatascraper.py", line 145, in <module>
    result = x.start_datascraper(
  File "...OnlyFans-master\modules\onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "...OnlyFans-master\modules\onlyfans.py", line 311, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "...AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "...AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "...AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "...AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "...OnlyFans-master\modules\onlyfans.py", line 213, in scrape_array
    size = source["size"]
KeyError: 'size'
```

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest commit?

**Comment by user123456789101112** [comment]
My apologies, I thought I was using the latest commit, but upon re-download it has worked.
