### ISSUE TITLE
ERROR errors ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINAL/OnlyFans#213]
2020-04-21 03:02:49,803 ERROR errors ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))
 Tries: 0
Traceback (most recent call last):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] En befintlig anslutning tvingades att stänga av fjärrvärddatorn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\Added an option to individually scrape the following\modules\onlyfans.py", line 474, in download
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))
2020-04-21 03:02:51,484 ERROR errors ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))
 Tries: 0
Traceback (most recent call last):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] En befintlig anslutning tvingades att stänga av fjärrvärddatorn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\Added an option to individually scrape the following\modules\onlyfans.py", line 474, in download
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\Users\albin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None)", ConnectionResetError(10054, 'En befintlig anslutning tvingades att stänga av fjärrvärddatorn', None, 10054, None))

**Comment by DIGITALCRIMINAL** [comment]
Hmm, you're using the latest commit right? The script is supposed to catch this error and essentially ignore it.

**Comment by Dalla-maker** [comment]
Yes i use one that 13h lastest commit

**Comment by DIGITALCRIMINAL** [comment]
The script prints this error; ignores it and continues to download.
