### ISSUE TITLE
Error: Expecting value

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#219]
I'm not sure what I'm doing wrong here. I did a clean install of the onlyfans downloader files and when I try to run it, this is what I get:

`python StartDatascraper.py`
`Traceback (most recent call last):`
`  File "StartDatascraper.py", line 2, in <module>`
`    import modules.onlyfans as onlyfans`
`  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 2, in <module>`
`    from modules.helpers import get_directory, json_request, reformat, format_directory,` `format_media_set, export_archive, format_image, check_for_dupe_file, setup_logger`
`  File "/media/sdw1/holonet81/OnlyFans/modules/helpers.py", line 16, in <module>`
`    json_config = json.load(open(path))`
`  File "/media/sdw1/holonet81/python3/lib/python3.8/json/__init__.py", line 293, in load`
`    return loads(fp.read(),`
`  File "/media/sdw1/holonet81/python3/lib/python3.8/json/__init__.py", line 357, in loads`
`    return _default_decoder.decode(s)`
`  File "/media/sdw1/holonet81/python3/lib/python3.8/json/decoder.py", line 337, in decode`
`    obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`  File "/media/sdw1/holonet81/python3/lib/python3.8/json/decoder.py", line 355, in raw_decode`
`    raise JSONDecodeError("Expecting value", s, err.value) from None`
`json.decoder.JSONDecodeError: Expecting value: line 29 column 24 (char 1108)`

Any help would be greatly appreciated.

**Comment by ElusiveZatchmo** [comment]
Disregard, there was a typo in my settings. There was a missing ". My apologies.
