### ISSUE TITLE
ERROR errors HTTPSConnectionPool(host='uk.convert.onlyfans.com', port=443): Max retries exceeded with

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#223]
2020-04-28 07:32:44,538 INFO downloads Path: C:\temp\OnlyFans DataScraper v4.0\.sites/OnlyFans/sophieaslut/Posts/Images/768x1024_e67a2aded13412c00848f7aec56dbda2.jpg
2020-04-28 07:36:00,212 ERROR errors HTTPSConnectionPool(host='uk.convert.onlyfans.com', port=443): Max retries exceeded with url: /upload/74d6d8d5dc53ddad44061bf5f3b73593375150.jpeg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D1965A4670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by DIGITALCRIMINAL** [comment]
Fixed in the new commit; lemme know if it works

**Comment by Dalla-maker** [comment]
I give it a try now. get back too your soon..

**Comment by misterscraper** [comment]
No config in latest release....

**Comment by DIGITALCRIMINAL** [comment]
config is in .settings folder

**Comment by DIGITALCRIMINAL** [comment]
It's been fixed
