### ISSUE TITLE
Keep getting connection errors?

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINAL/OnlyFans#226]
`Traceback (most recent call last):
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='onlyfans.com', port=443): Max retries exceeded with url: /api2/v2/users/9730880/posts?limit=100&offset=100&order=publish_date_desc&app-token=33d57ade8c02dbc5a333db99ff9ae26a (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10bd51f98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))`

Traceback (most recent call last):
  File "/Users/****/Downloads/OnlyFans-master/helpers/main_helper.py", line 185, in json_request
    r = session.request(method, link, stream=stream)
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='onlyfans.com', port=443): Max retries exceeded withrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='onlyfans.com', port=443): Max retries exceeded with
 url: /api2/v2/users/9730880/posts?limit=100&offset=100&order=publish_date_desc&app-token=33d57ade8c02dbc5a333db99ff9ae26a (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10bd51f98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2020-05-03 08:36:42,176 ERROR errors HTTPSConnectionPool(host='onlyfans.com', port=443): Max retries exceeded with url: /api2/v2/users/9730880/posts?limit=100&offset=200&order=publish_date_desc&app-token=33d57ade8c02dbc5a333db99ff9ae26a (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10bd51630>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Traceback (most recent call last):
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/Users/****/Library/Python/3.7/lib/python/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10bd51630>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

**anyone else getting these issues?**

**Comment by DIGITALCRIMINAL** [comment]
It's best if you use PY 3.8

**Comment by IRlyLikeBac0n** [comment]
@DIGITALCRIMINAL I'm getting the same issue with 3.8

**Comment by misterscraper** [comment]
> It's best if you use PY 3.8

still get same error with 3.8

**Comment by DIGITALCRIMINAL** [comment]
I'm looking into it

**Comment by misterscraper** [comment]
anyone had any luck on a fix?

**Comment by DIGITALCRIMINAL** [comment]
You can just ignore those errors; the script automatically retries to download content

**Comment by misterscraper** [comment]
> You can just ignore those errors; the script automatically retries to download content

ok thanks!

**Comment by misterscraper** [comment]
I now get this error:

`helpers/main_helper.py", line 185, in json_request
    r = session.request(method, link, stream=stream)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cdn2.onlyfans.com', port=443): Read timed out. (read timeout=None)`

**Comment by DIGITALCRIMINAL** [comment]
> I now get this error:
> 
> `helpers/main_helper.py", line 185, in json_request r = session.request(method, link, stream=stream) File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 529, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cdn2.onlyfans.com', port=443): Read timed out. (read timeout=None)`

That's the same error as the one above. You can just ignore that error.
