### ISSUE TITLE
More Traceback and Other Errors

### ISSUE THREAD

**Issue by NotMyMainOne** [DIGITALCRIMINAL/OnlyFans#236]
```
--- Logging error ---
Traceback (most recent call last):
  File "Z:\completed\Other\onlyfans\modules\onlyfans.py", line 490, in download
    with open(download_path, 'wb') as f:
OSError: [Errno 22] Invalid argument: '\\\\SERVER\\downloads\\completed\\Other\\onlyfans\\.sites/OnlyFans/xxx/Posts/Images/2019-12-29 - 2200 fans and counting...you’ve changed my life. You’.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f90d' in position 326: character maps to <undefined>
Call stack:
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "Z:\completed\Other\onlyfans\modules\onlyfans.py", line 504, in download
    log_error.exception(str(e) + "\n Tries: "+str(count))
```

Again yes the folder is on a Linux drive. Running the latest version 4.0 commit 17. Also the same problem with the character count not being limited persists. I left the file name in the post in tact so you can see what it looks like when it runs out of room while I removed the middle part for clutter sake. As you can see when it gets cut off it doesn't get to the file_name so there's no unique identifier to allow posts with multiple files be downloaded.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I don't recommend using text in the name format at all because there are so many errors that pop up which will lead you to download duplicates. What's the username you're trying to scrape?

**Comment by NotMyMainOne** [comment]
That one is darshellestevens.

**Comment by DIGITALCRIMINAL** [comment]
Try using the latest commit
