### ISSUE TITLE
nvalidProxyURL("Please check proxy URL. It is malformed"

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#239]
aceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v4.0\helpers\main_helper.py", line 196, in json_request
    r = session.request(method, link, stream=stream)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 307, in get_connection
    raise InvalidProxyURL("Please check proxy URL. It is malformed"
requests.exceptions.InvalidProxyURL: Please check proxy URL. It is malformed and could be missing the host.
2020-05-11 15:32:48,387 ERROR errors Please check proxy URL. It is malformed and could be missing the host.
Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v4.0\helpers\main_helper.py", line 196, in json_request
    r = session.request(method, link, stream=stream)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 307, in get_connection
    raise InvalidProxyURL("Please check proxy URL. It is malformed"
requests.exceptions.InvalidProxyURL: Please check proxy URL. It is malformed and could be missing the host.
2020-05-11 15:32:48,391 ERROR errors Please check proxy URL. It is malformed and could be missing the host.
Traceback (most recent call last):
  File "C:\temp\OnlyFans DataScraper v4.0\helpers\main_helper.py", line 196, in json_request
    r = session.request(method, link, stream=stream)
  File "C:\Users\Dala\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in re

**Comment by DIGITALCRIMINAL** [comment]
Oops; I forgot to do an if condition.

**Comment by DIGITALCRIMINAL** [comment]
Fixed
