### ISSUE TITLE
Error With Latest Update

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINAL/OnlyFans#241]
`2020-05-12 06:49:10,839 ERROR errors 'price'
Traceback (most recent call last):
  File "/Users/admin/Downloads/OnlyFans-master-2/datascraper/main_datascraper.py", line 177, in start_datascraper
    result = x.start_datascraper(
  File "/Users/admin/Downloads/OnlyFans-master-2/modules/onlyfans.py", line 85, in start_datascraper
    results = prepare_scraper(
  File "/Users/admin/Downloads/OnlyFans-master-2/modules/onlyfans.py", line 455, in prepare_scraper
    x = pool.starmap(media_scraper, product(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/admin/Downloads/OnlyFans-master-2/modules/onlyfans.py", line 290, in media_scraper
    new_dict["price"] = media_api["price"]
KeyError: 'price'`

**Comment by DIGITALCRIMINAL** [comment]
What's the username you are trying to scrape?

**Comment by onlyFPanda** [comment]
having same issue with multiple usernames. error below is from trying to scrape chloekhan
2020-05-12 14:34:30,257 ERROR errors 'price'
Traceback (most recent call last):
  File "D:\Users\panda\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 177, in start_datascraper
    result = x.start_datascraper(
  File "D:\Users\panda\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 85, in start_datascraper
    results = prepare_scraper(
  File "D:\Users\panda\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 455, in prepare_scraper
    x = pool.starmap(media_scraper, product(
  File "D:\Users\panda\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "D:\Users\panda\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "D:\Users\panda\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\Users\panda\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\Users\panda\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 290, in media_scraper
    new_dict["price"] = media_api["price"]

**Comment by DIGITALCRIMINAL** [comment]
@onlyFPanda latest commit that I pushed a moment ago has fixed that error

**Comment by DIGITALCRIMINAL** [comment]
I've also pushed a new commit, maybe it fixed it because I can't recreate it on my end.
If it's not fixed, do you have another username?

**Comment by DIGITALCRIMINAL** [comment]
Fixed
