### ISSUE TITLE
main_helper.py", line 95, in export_archive     if data["valid"]:

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#249]
Not sure where to begin.
Section is commented "not finished" but not sure how to avoid it. (using .csv)

ERROR errors list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/user/of/datascraper/main_datascraper.py", line 177, in start_datascraper
    result = x.start_datascraper(
  File "/home/user/of/modules/onlyfans.py", line 86, in start_datascraper
    results = prepare_scraper(
  File "/home/user/of/modules/onlyfans.py", line 489, in prepare_scraper
    export_archive(metadata_set, archive_directory)
  File "/home/user/of/helpers/main_helper.py", line 95, in export_archive
    if data["valid"]:

**Comment by DIGITALCRIMINAL** [comment]
Thanks, gonna sort it out now

**Comment by DIGITALCRIMINAL** [comment]
Fixed
