### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)

### ISSUE THREAD

**Issue by dilemmax** [DIGITALCRIMINAL/OnlyFans#266]
C:\OLF 4.0.0>pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

C:\OLF 4.0.0>python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 7, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "C:\OLF 4.0.0\datascraper\main_datascraper.py", line 9, in <module>
    import helpers.main_helper as main_helper
  File "C:\OLF 4.0.0\helpers\main_helper.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

C:\OLF 4.0.0>python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by dilemmax** [comment]
Worked it out.

pip install -r requirements.txt
