### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac'

### ISSUE THREAD

**Issue by jebzaki** [DIGITALCRIMINAL/OnlyFans#27]
```
Traceback (most recent call last):
  File "OnlyFans.py", line 231, in <module>
    user_id = link_check()
  File "OnlyFans.py", line 58, in link_check
    r = session.get(link)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1285, in _send_request
    self.putheader(hdr, value)
  File "D:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1217, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 31: ordinal not in range(256)
```

The issue I encounter when I try to run it as is

**Comment by DIGITALCRIMINAL** [comment]
What's the account username

**Comment by jebzaki** [comment]
`kittenkate`, I'm running this on Windows 10 btw

**Comment by DIGITALCRIMINAL** [comment]
Ahh I see the problem. She has an emoji in her name lol. I'll message back when it's fixed.

**Comment by jebzaki** [comment]
Thanks!

**Comment by DIGITALCRIMINAL** [comment]
Hmm this is strange. Are you putting in the username for the input?

**Comment by jebzaki** [comment]
I tried both with the same result unfortunately.

**Comment by DIGITALCRIMINAL** [comment]
Hmm, are you using the latest commit?

**Comment by jebzaki** [comment]
I'll try master again now.

**Comment by jebzaki** [comment]
It worked! I guess I can close this issue. Thanks again!

**Comment by dharbigt** [comment]
Hello, I'm seeing a similar issue:

Traceback (most recent call last):
  File "./StartDatascraper.py", line 61, in <module>
    session = x.create_session(
  File "/Users/ajax/Sites/OnlyFans/modules/onlyfans.py", line 276, in create_session
    session.head("https://onlyfans.com")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1271, in _send_request
    self.putheader(hdr, value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1203, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 30: ordinal not in range(256)

**Comment by DIGITALCRIMINAL** [comment]
> Hello, I'm seeing a similar issue:
> 
> ```
> Traceback (most recent call last):
>   File "./StartDatascraper.py", line 61, in <module>
>     session = x.create_session(
>   File "/Users/ajax/Sites/OnlyFans/modules/onlyfans.py", line 276, in create_session
>     session.head("https://onlyfans.com")
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 568, in head
>     return self.request('HEAD', url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
>     httplib_response = self._make_request(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1271, in _send_request
>     self.putheader(hdr, value)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1203, in putheader
>     values[i] = one_value.encode('latin-1')
> UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 30: ordinal not in range(256)
> ```
Check your auth cookies
