### ISSUE TITLE
4chan errors

### ISSUE THREAD

**Issue by RuneDemomn** [DIGITALCRIMINAL/OnlyFans#283]
2020-06-10 09:18:51,489 ERROR errors reformat() missing 1 required positional argument: 'maximum_length'
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 196, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\[REDACTED]\Desktop\OnlyFans-master\modules\fourchan.py", line 72, in start_datascraper
    threads = pool.starmap(thread_scraper,
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\[REDACTED]\Desktop\OnlyFans-master\modules\fourchan.py", line 166, in thread_scraper
    download_path = reformat(
TypeError: reformat() missing 1 required positional argument: 'maximum_length'

**Comment by lowtolerance** [comment]
The data scraper modules for fourchan and bbwchan are missing a parameter for the "reformat" function. In modules/fourchan.py, change:

    download_path = reformat(
                new_directory, None, filename, text, ext, date_object, post["name"], format_path, date_format, maximum_length)

To:
    download_path = reformat(
                new_directory, None, None, filename, text, ext, date_object, post["name"], format_path, date_format, maximum_length)

And do the same thing for modules/bbwchan.py.

**Comment by DIGITALCRIMINAL** [comment]
I fixed it, use the latest commit
