### ISSUE TITLE
No schema supplied. Perhaps you meant http://?

### ISSUE THREAD

**Issue by Morticioner87** [DIGITALCRIMINAL/OnlyFans#286]
Getting this error while downloading content.
latest release (5.0) and python 3.8.2

Keeps spamming every milisecond. my logfile is over 800mb

2020-06-14 15:26:47,053 ERROR errors Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "C:\Scripts\OnlyFans-5.0\helpers\main_helper.py", line 210, in json_request
    r = session.request(method, link,stream=stream)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by Morticioner87** [comment]
*Update
Tried updating to python 3.8.3 but same error

**Comment by Morticioner87** [comment]
Ok i managed to solve this.
Not sure what did it but i downloaded the master, and changed my user-agent from chrome to firefox.
Also updated hash, session, token.
Anyways no more errors.

**Comment by DIGITALCRIMINAL** [comment]
Download newest commit
