### ISSUE TITLE
Recurring error regarding invalid literal for int()

### ISSUE THREAD

**Issue by aschettler** [DIGITALCRIMINAL/OnlyFans#293]
I have received this error every time I run the script, even when selecting different individual subscriptions. This started with the "Fixed shebang" commit and has recurred through each commit. Reverting to the previous commit fixes the issue. All required Python components are up to date, and I'm running Python 3.8.3 x64 on Windows 10 v2004. 

2020-06-20 15:07:54,806 ERROR errors invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "D:\Python\OnlyFans\datascraper\main_datascraper.py", line 186, in start_datascraper
    result = x.start_datascraper(
  File "D:\Python\OnlyFans\modules\onlyfans.py", line 92, in start_datascraper
    results = prepare_scraper(
  File "D:\Python\OnlyFans\modules\onlyfans.py", line 512, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "D:\Python\OnlyFans\helpers\main_helper.py", line 101, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "D:\Python\OnlyFans\extras\OFRenamer\start.py", line 79, in start
    metadata.valid = fix_metadata(
  File "D:\Python\OnlyFans\extras\OFRenamer\start.py", line 49, in fix_metadata
    reformat = prepare_reformat(model2)
  File "D:\Python\OnlyFans\extras\OFRenamer\start.py", line 46, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''

**Comment by LP560** [comment]
I was having the same issue. version 5.1 fixed it

**Comment by aschettler** [comment]
Hmmmm... It's still doing it for me on 5.1. I'll re-download the entire script and report back.

**Comment by DIGITALCRIMINAL** [comment]
Set text_length to 255 in the config

**Comment by aschettler** [comment]
Yep, that was the problem. I was using the older config file, and it wasn't working. Once I copied and pasted the cookie information and added my settings back, it worked.
