### ISSUE TITLE
Starsavn errors

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#296]
Getting this error for Starsavn

2020-06-23 14:06:07,005 ERROR errors 'link'
Traceback (most recent call last):
  File "F:\OnlyFans-5.1\datascraper\main_datascraper.py", line 192, in start_datascraper
    x.download_media(*arg)
  File "F:\OnlyFans-5.1\modules\starsavn.py", line 483, in download_media
    pool.starmap(download, product(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\OnlyFans-5.1\modules\starsavn.py", line 430, in download
    link = media["link"]
KeyError: 'link'
Traceback (most recent call last):
  File "F:\OnlyFans-5.1\datascraper\main_datascraper.py", line 192, in start_datascraper
    x.download_media(*arg)
  File "F:\OnlyFans-5.1\modules\starsavn.py", line 483, in download_media
    pool.starmap(download, product(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\OnlyFans-5.1\modules\starsavn.py", line 430, in download
    link = media["link"]
KeyError: 'link'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OnlyFans-5.1\start_ofd.py", line 9, in <module>
    main_datascraper.start_datascraper()
  File "F:\OnlyFans-5.1\datascraper\main_datascraper.py", line 206, in start_datascraper
    input()
KeyboardInterrupt

**Comment by DIGITALCRIMINAL** [comment]
I'll check what is wrong with it.

**Comment by DIGITALCRIMINAL** [comment]
Which user are you trying to scrape?

**Comment by ctrlcmdshft** [comment]
leilanilei

**Comment by DIGITALCRIMINAL** [comment]
Thanks, fixed in newest commit
