### ISSUE TITLE
Experiencing a bug

### ISSUE THREAD

**Issue by testuser46** [DIGITALCRIMINAL/OnlyFans#297]
> Traceback (most recent call last):
>  File "start_ofd.py", line 9, in <module>
>     main_datascraper.start_datascraper()
>   File "C:\...\datascraper\main_datascraper.py", line 33, in start_datascraper
>     json_config, json_config2 = main_helper.get_config(config_path)
>   File "C:\...r\helpers\main_helper.py", line 251, in get_config
>     json_config2 = json.loads(json.dumps(make_config.start(
>   File "C:\...\classes\make_config.py", line 171, in __init__
>     self.settings = Settings(**settings)
> TypeError: __init__() got an unexpected keyword argument 'global_user-agent'

I also noticed that the config.json file is no longer in the setting so the readme no longer makes sense. 

Cheers

**Comment by testuser46** [comment]
Ok I'm dumb, I was still using the old config file after having copied the new files in. Because of this it didn't generate the config file to fill out.
