### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by SRLJustin** [DIGITALCRIMINAL/OnlyFans#3]
When searching for someone, it will fail and output the following:

```
Traceback (most recent call last):
  File "OnlyFans.py", line 109, in <module>
    user_id = link_check(input_link)
  File "OnlyFans.py", line 38, in link_check
    temp_user_id = html.find("div", {"class": "b-users"}).find("a", attrs={"data-user", True})
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by DIGITALCRIMINAL** [comment]
Going to look into this now

**Comment by DIGITALCRIMINAL** [comment]
Updated the program, should throw my custom error message.
