### ISSUE TITLE
Scrape error on specific accounts | 100 Posts Skipped

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#304]
I'm running into the following error, which only seems to affect specific accounts.

Scrape Processing
Name: theredwoods2
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
2020-06-29 18:50:54,013 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:54,577 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:55,152 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:55,663 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:56,176 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:56,801 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:57,329 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:57,827 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:58,289 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:58,820 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:59,295 ERROR errors Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\helpers\main_helper.py", line 230, in json_request
    return json.loads(r.text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-06-29 18:50:59,318 ERROR errors argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-5.1\datascraper\main_datascraper.py", line 186, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\username\Desktop\OnlyFans-5.1\modules\onlyfans.py", line 92, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\username\Desktop\OnlyFans-5.1\modules\onlyfans.py", line 477, in prepare_scraper
    x = pool.starmap(media_scraper, product(
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\username\Desktop\OnlyFans-5.1\modules\onlyfans.py", line 255, in media_scraper
    if "error" in y:
TypeError: argument of type 'NoneType' is not iterable

**Comment by galaxianloop** [comment]
i'm getting this exact same error on a few accounts too

**Comment by avekifes** [comment]
This may be a platform-specific issue. I just checked the account on OnlyFans, and it's saying that "nothing was found," despite having hundreds of posts/photos/videos.

**Comment by WellSomething** [comment]
Having the same problem, it's why I tried to use the blacklist_name feature, but having trouble getting it to work for more than one account.

**Comment by jeremfg** [comment]
I just tried scrapping an account (first time in many days) and I got the same error. In my case it's 'aliciaamiraxxx' that throws these errors

And I've got other accounts still working.

**Comment by DIGITALCRIMINAL** [comment]
Were you guys given a free trial on the models you've subscribed too that aren't working or did you buy the subscription?

**Comment by DIGITALCRIMINAL** [comment]
I need to know more usernames that you're trying to scrape that breaks the script.

It's on OF's side btw.

**Comment by crackmanix** [comment]
same error for me when i scrape siswet19

**Comment by jeremfg** [comment]
I've since encountered a second account: "brithotwife".

Yeah, based on the stack trace it obviously is something missing in the response received from OF servers. I'm guessing it's some feature that a few models are turning on (or off) but not the majority. I haven't looked at the code though, since I haven't yet upgraded to the latest version anyway.
I was only downloading from paid accounts though, so I don't know if some free accounts could be affected. And yes, I am properly subscribed and can browse these accounts.

**Comment by avekifes** [comment]
myhotwifeadreena
kittyhotwife69

**Comment by ESurge** [comment]
Hi there, I'm getting an issue with the scraper too but I don't have the exact error as the first post states. I didn't want to make a new issue as its related to the scraper, so I decided to post the error here:

```md
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-06-30 01:19:04,593 ERROR errors invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "d:\OnlyFans\datascraper\main_datascraper.py", line 175, in start_datascraper
    result = x.start_datascraper(session, username, site_name, app_token, choice_type=value)
  File "d:\OnlyFans\modules\onlyfans.py", line 91, in start_datascraper
    results = prepare_scraper(session, site_name, only_links, *item[1], api_type, app_token)
  File "d:\OnlyFans\modules\onlyfans.py", line 480, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "d:\OnlyFans\helpers\main_helper.py", line 101, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 76, in start
    metadata.valid = fix_metadata(metadata.valid, json_settings, username)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 47, in fix_metadata
    reformat = prepare_reformat(model2)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 45, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''
```

Please note, I found that this only occurs on the second run of the script and does not occur with a fresh '.sites' folder. I found a quick workaround which is to remove the metadata files from each sub-folder (within .sites folder) before running the script.

**Comment by DIGITALCRIMINAL** [comment]
@ESurge make a new issue... I don't want to mix issues and send unrelated notifications to everyone's email

**Comment by ESurge** [comment]
> @ESurge make a new issue... I don't want to mix issues and send unrelated notifications to everyone's email

Will do. Thanks for the prompt reply.

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit. It's not a fix, but a bypass. You will be missing out on 100 posts.

**Comment by bollerdominik** [comment]
Do I understand your commit correctly that the OF API is broken and there is no way to view those missing posts right now even on their own website?

**Comment by DIGITALCRIMINAL** [comment]
Yeah, it's broken on their side as well.
I was looking at sachelamonte which has 314 posts, but I can only scroll down to around the 160th post.
When it tries to get the 161st post, their API returns nothing, thus ending the pagination.

Their pagination works by getting the last available post from the API feed, and with it returning nothing, it breaks the pagination.

**Comment by jeremfg** [comment]
I found a free account that does the same thing:

lydialuxy-free

@DIGITALCRIMINAL Are you saying that it's broken even while scrolling the web page in the browser? In that case, yeah I guess they're gonna fix this eventually.

**Comment by DIGITALCRIMINAL** [comment]
@jeremfg I believe they fixed it

**Comment by jeremfg** [comment]
@DIGITALCRIMINAL 
Granted I am not running your most recent code (I get the crash instead of the skipping message), but I just retried 'lydialuxy-free' and it failed.
Either you are mistaken, or there's something else going on causing the "TypeError: argument of type 'NoneType' is not iterable".

**Comment by DIGITALCRIMINAL** [comment]
> @DIGITALCRIMINAL
> Granted I am not running your most recent code (I get the crash instead of the skipping message), but I just retried 'lydialuxy-free' and it failed.
> Either you are mistaken, or there's something else going on causing the "TypeError: argument of type 'NoneType' is not iterable".

Then use the latest commit because that account is working for me.
