### ISSUE TITLE
Getting ValueError: invalid literal for int() with base 10: '' on second run of script.

### ISSUE THREAD

**Issue by ESurge** [DIGITALCRIMINAL/OnlyFans#305]
Hi there, I'm getting an issue with the scraper.

This only occurs on the second run of the script and does not occur with a fresh '.sites' folder. A quick workaround I found is to remove the metadata files from each sub-folder (within .sites folder) before running the script.

Note: This error occurs for any user that I select.

Here is the console output:

```md
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-06-30 01:19:04,593 ERROR errors invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "d:\OnlyFans\datascraper\main_datascraper.py", line 175, in start_datascraper
    result = x.start_datascraper(session, username, site_name, app_token, choice_type=value)
  File "d:\OnlyFans\modules\onlyfans.py", line 91, in start_datascraper
    results = prepare_scraper(session, site_name, only_links, *item[1], api_type, app_token)
  File "d:\OnlyFans\modules\onlyfans.py", line 480, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "d:\OnlyFans\helpers\main_helper.py", line 101, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 76, in start
    metadata.valid = fix_metadata(metadata.valid, json_settings, username)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 47, in fix_metadata
    reformat = prepare_reformat(model2)
  File "d:\OnlyFans\extras\OFRenamer\start.py", line 45, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''
```

Edit: Note 2: I'm running script version 5.1

**Comment by DIGITALCRIMINAL** [comment]
Have you seen this issue
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/293

**Comment by ESurge** [comment]
This worked. Sorry to waste your time.

Note: I swear I searched for the error on this github, but I guess I didn't do a well enough search.

Thanks!
