### ISSUE TITLE
Error when trying to DL from SAVN

### ISSUE THREAD

**Issue by theyuvir** [DIGITALCRIMINAL/OnlyFans#312]
Getting the following error: 

2020-07-01 23:04:53,917 ERROR errors 'link'
Traceback (most recent call last):
  File "C:\Users\<username>\Documents\OnlyFans-5.1\datascraper\main_datascraper.py", line 192, in start_datascraper
    x.download_media(*arg)
  File "C:\Users\<username>\Documents\OnlyFans-5.1\modules\starsavn.py", line 483, in download_media
    pool.starmap(download, product(
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\<username>\Documents\OnlyFans-5.1\modules\starsavn.py", line 430, in download
    link = media["link"]
KeyError: 'link'

Profile is TheCandyGlitter

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit

**Comment by theyuvir** [comment]
<removed>

**Comment by DIGITALCRIMINAL** [comment]
Download the latest commit, not the latest release

**Comment by theyuvir** [comment]
<removed>

**Comment by DIGITALCRIMINAL** [comment]
Are you subscribed to the user?

**Comment by theyuvir** [comment]
<removed>
