### ISSUE TITLE
pip install -r requirements.txt not working after 5.1 update

### ISSUE THREAD

**Issue by Dalla-maker** [DIGITALCRIMINAL/OnlyFans#315]
C:\Temp\OnlyFans-master>start_ofd.py
Traceback (most recent call last):
  File "C:\Temp\OnlyFans-master\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\Temp\OnlyFans-master\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\Temp\OnlyFans-master\helpers\main_helper.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

way too fix this problem/bug?

**Comment by DIGITALCRIMINAL** [comment]
You haven't installed bs4.
