### ISSUE TITLE
Thread Resource Leak

### ISSUE THREAD

**Issue by herefromrdt** [DIGITALCRIMINAL/OnlyFans#317]
The module scripts keep making multiprocessing.dummy.Pool objects without closing the old ones, which eventually leads to the system running out of threads. I don't know a lot about Python's threading implementation, but it seems like the thread pool spins up a new thread when it is created, so every time a new one gets created, another thread gets taken up. If the pool doesn't get closed manually, it probably doesn't get closed until it's garbage collected, so they just stack up until there aren't any threads left.

Stack Trace (with local paths removed)
```
2020-07-03 22:39:42,288 ERROR errors can't start new thread
Traceback (most recent call last):
  File "OnlyFans\datascraper\main_datascraper.py", line 188, in start_datascraper
    session, username, site_name, app_token, choice_type=value)
  File "OnlyFans\modules\onlyfans.py", line 93, in start_datascraper
    session, site_name, only_links, *item[1], api_type, app_token)
  File "OnlyFans\modules\onlyfans.py", line 368, in prepare_scraper
    pool = ThreadPool()
  File "Python37-32\lib\multiprocessing\dummy\__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "Python37-32\lib\multiprocessing\pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "Python37-32\lib\multiprocessing\dummy\__init__.py", line 51, in start
    threading.Thread.start(self)
  File "Python37-32\lib\threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8
