### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#32]
I'm encountering the following with iamsweette:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\OnlyFans-master\Start Datascraper.py", line 20, in 
    result = start_datascraper(session, app_token, username)
  File "C:\Users\USER\Desktop\OnlyFans-master\modules\onlyfans.py", line 47, in start_datascraper
    response = media_scraper(session, *item[1])
  File "C:\Users\USER\Desktop\OnlyFans-master\modules\onlyfans.py", line 163, in media_scraper
    media_set = pool.starmap(scrape_array, product(offset_array, [session]))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\USER\Desktop\OnlyFans-master\modules\onlyfans.py", line 135, in scrape_array
    if "ca2.convert" in file:
TypeError: argument of type 'NoneType' is not iterable

**Comment by avekifes** [comment]
Same issue with mixedmagazine.

**Comment by DIGITALCRIMINAL** [comment]
It was because the account had paid for view posts. Download the latest commit. It's been fixed c:
