### ISSUE TITLE
Scrape error

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#333]
Scrape Processing
Name: stefiedrew
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-07-17 00:52:51,247 ERROR errors Expecting ',' delimiter: line 1 column 578100 (char 578099)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 221, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 92, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 519, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 100, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\username\Desktop\OnlyFans-master\extras\OFRenamer\start.py", line 85, in start
    metadatas = json.load(open(metadata_filepath))
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 578100 (char 578099)

**Comment by avekifes** [comment]
This appears to be account specific. I just blacklisted stefiedrew out of 100+ accounts; only that one was stalling the scraper.
