### ISSUE TITLE
bug with auth fix ?

### ISSUE THREAD

**Issue by anonCoder123** [DIGITALCRIMINAL/OnlyFans#343]
this happened after pulling the most recent push to fix auth

```
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-07-27 02:37:26,573 ERROR errors invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "Z:\github-folders\OnlyFans\datascraper\main_datascraper.py", line 221, in start_datascraper
    result = x.start_datascraper(
  File "Z:\github-folders\OnlyFans\modules\onlyfans.py", line 92, in start_datascraper
    results = prepare_scraper(
  File "Z:\github-folders\OnlyFans\modules\onlyfans.py", line 519, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "Z:\github-folders\OnlyFans\helpers\main_helper.py", line 104, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "Z:\github-folders\OnlyFans\extras\OFRenamer\start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "Z:\github-folders\OnlyFans\extras\OFRenamer\start.py", line 50, in fix_metadata
    reformat = prepare_reformat(model2)
  File "Z:\github-folders\OnlyFans\extras\OFRenamer\start.py", line 47, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by DIGITALCRIMINAL** [comment]
what does the "text_length" in the config say?

**Comment by anonCoder123** [comment]
`"text_length": "",`

just the default

**Comment by DIGITALCRIMINAL** [comment]
Dang, all that time it was me setting it to "" by default.
It should be 255

**Comment by anonCoder123** [comment]
@DIGITALCRIMINAL will changing it from empty string to 255 cause any problems for existing downloads/names?

**Comment by DIGITALCRIMINAL** [comment]
Only if you had "text" in your filename format, otherwise, nope.

**Comment by anonCoder123** [comment]
nah mine is just `"file_name_format": "{file_name}.{ext}",` which i assume is the default since i haven't changed it.

Most of my stuff is default other than specifying onlyfans and auto_choice.

**Comment by DIGITALCRIMINAL** [comment]
Ye, then you're all good

**Comment by anonCoder123** [comment]
yeah it looks like it is working now that i changed it to 255.
