### ISSUE TITLE
ERROR errors string indices must be integers

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#348]
> Auth (V1)
> Auth Attempt 1/10
> Welcome user
> 2020-07-29 01:55:37,832 ERROR errors string indices must be integers
> Traceback (most recent call last):
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 119, in start_datascraper
> array = x.get_subscriptions(
> File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 796, in get_subscriptions
> identifier = result["username"]
> TypeError: string indices must be integers

Anyone else getting this?

**Comment by avekifes** [comment]
I'm no longer encountering this (must have been an issue from their side), so I'm closing it.
