### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by wanyek43** [DIGITALCRIMINAL/OnlyFans#360]
I keep getting this error that halts the whole process and I'm not quite sure what's causing it. I deleted all of the metadata files and folders, set the config to use the sort option and delete legacy metadata files (I was using the previous version of this scraper). This issue comes up with different usernames at random times. When I delete the metadata files, it seems to work just fine on the first pass after the deletion. When I run again, it starts randomly running into this error. I have not modified any of the base code or files other than the ones for the credentials and settings.

"Traceback (most recent call last):
  File "/Users/USER/Developer/Python/OnlyFans/datascraper/main_datascraper.py", line 221, in start_datascraper
    result = x.start_datascraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 100, in start_datascraper
    results = prepare_scraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 527, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/helpers/main_helper.py", line 105, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 50, in fix_metadata
    reformat = prepare_reformat(model2)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 47, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''
^CTraceback (most recent call last):
  File "/Users/USER/Developer/Python/OnlyFans/datascraper/main_datascraper.py", line 221, in start_datascraper
    result = x.start_datascraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 100, in start_datascraper
    results = prepare_scraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 527, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/helpers/main_helper.py", line 105, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 50, in fix_metadata
    reformat = prepare_reformat(model2)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 47, in __init__
    self.maximum_length = int(text_length)
ValueError: invalid literal for int() with base 10: ''"

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues?q=ValueError%3A+invalid+literal+for+int%28%29+with+base+10

**Comment by wanyek43** [comment]
Thanks for the response. I don't know how I missed that in the closed issues.
