### ISSUE TITLE
AVN Stars not archiving some content

### ISSUE THREAD

**Issue by docholllidae2** [DIGITALCRIMINAL/OnlyFans#367]
I'm running on the most recent Master, and when trying to archive content for a model I'm subscribed to on stars.avn.com I get the following error. Also, the first time running it for the model was error free, but did not archive any content prior to July 13 (10 posts:  12 images and 2 videos); now I get this error when trying to run again

```
Scraping [photo]. Should take less than a minute.
FOUND: D:\Downloads\.tools\OnlyFans\downloads\StarsAVN\celesteestrella\Posts\Videos
2020-08-04 13:21:42,732 ERROR errors [Errno 2] No such file or directory: 'D:\\Downloads\\.tools\\OnlyFans\\download
s\\StarsAVN\\celesteestrella\\Posts\\Videos\\celesteestrella\\2020-07-30_~__~_5f2263de2e4e22ce376b5_source.mp4'
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\shutil.py", line 781, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Downloads\\.tools\\OnlyFans\\downloa
ds\\StarsAVN\\celesteestrella\\Posts\\Videos\\2020-07-30_~__~_5f2263de2e4e22ce376b5_source.mp4' -> 'D:\\Downloads\\.
tools\\OnlyFans\\downloads\\StarsAVN\\celesteestrella\\Posts\\Videos\\celesteestrella\\2020-07-30_~__~_5f2263de2e4e2
2ce376b5_source.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\.tools\OnlyFans\datascraper\main_datascraper.py", line 226, in start_datascraper
    result = x.start_datascraper(
  File "D:\Downloads\.tools\OnlyFans\modules\starsavn.py", line 95, in start_datascraper
    results = prepare_scraper(
  File "D:\Downloads\.tools\OnlyFans\modules\starsavn.py", line 358, in prepare_scraper
    export_archive([results], archive_directory, json_settings)
  File "D:\Downloads\.tools\OnlyFans\helpers\main_helper.py", line 105, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "D:\Downloads\.tools\OnlyFans\extras\OFRenamer\start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "D:\Downloads\.tools\OnlyFans\extras\OFRenamer\start.py", line 79, in fix_metadata
    filepath = update(filepath)
  File "D:\Downloads\.tools\OnlyFans\extras\OFRenamer\start.py", line 59, in update
    shutil.move(filepath, new_format)
  File "C:\Program Files\Python38\lib\shutil.py", line 795, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Downloads\\.tools\\OnlyFans\\downloads\\StarsAVN\\celes
teestrella\\Posts\\Videos\\celesteestrella\\2020-07-30_~__~_5f2263de2e4e22ce376b5_source.mp4'
```

It looks like either the main downloader or the renamer is looking a level deeper than it should be for the files (looking for directory `D:/Downloads/.tools/OnlyFans/downloads/SrarsAVN/celesteestrella/Posts/Videos/celesteestrella` when instead it should be looking for `D:/Downloads/.tools/OnlyFans/downloads/SrarsAVN/celesteestrella/Posts/Videos/` )

**Comment by DIGITALCRIMINAL** [comment]
Can't fix it atm since I'm not subscribed to any accounts
