### ISSUE TITLE
AttributeError: module 'helpers' has no attribute 'main_helper'

### ISSUE THREAD

**Issue by palmtreefever** [DIGITALCRIMINAL/OnlyFans#368]
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\Users\USER\Desktop\OnlyFans-master\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\Users\USER\\Desktop\OnlyFans-master\helpers\main_helper.py", line 20, in <module>
    import extras.OFRenamer.start as ofrenamer
  File "C:\Users\USER\\Desktop\OnlyFans-master\extras\OFRenamer\start.py", line 3, in <module>
    import helpers.main_helper as main_helper
AttributeError: module 'helpers' has no attribute 'main_helper'

**Comment by edgar1016** [comment]
You did not run `pip install -r requirements.txt` before running "start_ofd.py".

**Comment by bdsmgeek** [comment]
Same issue:

```
PS C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2> python --version                                                 Python 3.6.5
PS C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2> pip install -r requirements.txt                                  Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 1)) (2.18.4)
Requirement already satisfied: beautifulsoup4 in c:\users\bdsmg\appdata\roaming\python\python36\site-packages (from -r requirements.txt (line 2)) (4.9.1)
Requirement already satisfied: urllib3 in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 3)) (1.22)
Requirement already satisfied: win32-setctime in c:\users\bdsmg\appdata\roaming\python\python36\site-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: lxml in c:\users\bdsmg\appdata\roaming\python\python36\site-packages (from -r requirements.txt (line 5)) (4.5.2)
Requirement already satisfied: pysocks in c:\users\bdsmg\appdata\roaming\python\python36\site-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: idna<2.7,>=2.5 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\bdsmg\appdata\roaming\python\python36\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0.1)
PS C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2> python .\start_ofd.py                                            Traceback (most recent call last):
  File ".\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2\helpers\main_helper.py", line 20, in <module>
    import extras.OFRenamer.start as ofrenamer
  File "C:\Users\Public\Projects\OnlyFans\5.2\OnlyFans-5.2\extras\OFRenamer\start.py", line 3, in <module>
    import helpers.main_helper as main_helper
AttributeError: module 'helpers' has no attribute 'main_helper'
```

```
SystemDirectory : C:\WINDOWS\system32
Organization    : Microsoft
BuildNumber     : 18363
SerialNumber    : 00325-95800-00000-AAOEM
Version         : 10.0.18363
```

**Comment by bdsmgeek** [comment]
So my issue was with using Python 3.6 bc it was defaulted from another account on my pc.  Upgraded to 3.8 and everything works.
