### ISSUE TITLE
StarsAVN errors 

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#374]
Getting these errors with newest release on starsavn

`Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
1
2020-08-09 14:05:27,866 ERROR errors can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "F:\OnlyFans-5.1\datascraper\main_datascraper.py", line 176, in start_datascraper
    session = x.create_session()
  File "F:\OnlyFans-5.1\modules\starsavn.py", line 506, in create_session
    proxies = {'http': 'socks5://'+proxy,
TypeError: can only concatenate str (not "list") to str`

**Comment by DIGITALCRIMINAL** [comment]
Try now

**Comment by evlsmurf** [comment]
working great now thanks

**Comment by ctrlcmdshft** [comment]
Working as intended now thanks
