### ISSUE TITLE
Error in 5.2 downloader

### ISSUE THREAD

**Issue by monkjew** [DIGITALCRIMINAL/OnlyFans#377]
It logs in fine and pulls the names of everybody I'm subbed to. But just after it finishes scraping content I get this

2020-08-10 14:35:17,446 ERROR errors HTTPSConnectionPool(host='onlyfans.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

In my config I have:
username: "uXXXXXXX"
auth_id: "XXXXXX"
auth_hash: ""
auth_uniq_: ""
sess: "XXXXXXXXXXXXXXXXX"
fp: ""
app_token: "XXXXXXXXXXXXXXXXXXXXXX"
user_agent: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
support_2fa: false

**Comment by Telandriq** [comment]
Reporting same issue, will try most recent changes in master and see if that resolves it.

**Comment by DIGITALCRIMINAL** [comment]
I added a new commit, try download from there

**Comment by Telandriq** [comment]
@DIGITALCRIMINAL Thank you. It is working properly now.
