### ISSUE TITLE
ERROR errors list index out of range

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINAL/OnlyFans#381]
`Scrape Processing
Name: XX
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
NOT FOUND: /Volumes/XXDRIVE/My Drive/new/OnlyFans/XX/Highlights/Images`

`Traceback (most recent call last):
  File "/Users/THEXX/Downloads/OnlyFans-master/datascraper/main_datascraper.py", line 232, in start_datascraper
    result = x.start_datascraper(
  File "/Users/THEXX/Downloads/OnlyFans-master/modules/onlyfans.py", line 100, in start_datascraper
    results = prepare_scraper(
  File "/Users/THEXX/Downloads/OnlyFans-master/modules/onlyfans.py", line 531, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "/Users/THEXX/Downloads/OnlyFans-master/helpers/main_helper.py", line 107, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/Users/THEXX/Downloads/OnlyFans-master/extras/OFRenamer/start.py", line 91, in start
    metadata.valid = fix_metadata(
  File "/Users/THEXX/Downloads/OnlyFans-master/extras/OFRenamer/start.py", line 69, in fix_metadata
    last_path = folder.split(username+"\\")[1]
IndexError: list index out of range`

**Comment by DIGITALCRIMINAL** [comment]
Delete the metadata from the folder
