### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by stayupthetree** [DIGITALCRIMINAL/OnlyFans#394]
I auth just fine, get a list of people on OF I sub to. It does the initial scrape and makes the folders just fine. Once it goes to download I get this:

```
Download Processing
Name: redacted | Type: Posts | Directory: /mnt/e/OnlyFans/
Downloading 267 Images

2020-08-20 19:52:13,986 ERROR errors [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/home/tree/OnlyFans/datascraper/main_datascraper.py", line 241, in start_datascraper
    x.download_media(*arg)
  File "/home/tree/OnlyFans/modules/onlyfans.py", line 657, in download_media
    pool.starmap(download, product(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/tree/OnlyFans/modules/onlyfans.py", line 643, in download
    format_image(download_path, timestamp)
  File "/home/tree/OnlyFans/helpers/main_helper.py", line 98, in format_image
    os.utime(directory, (timestamp, timestamp))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by stayupthetree** [comment]
I thought it might be 'multithreading' because I tried 2 different girls and they both got 30-31 images before crashing. So I turned it off, and only got 4 images before crashing.

**Comment by stayupthetree** [comment]
Note to self, use Windows. Switched it over to Windows and works perfectly. Now when does the patreon bit go live?
