### ISSUE TITLE
4chan read time out. Maybe rate limiting?

### ISSUE THREAD

**Issue by RuneDemomn** [DIGITALCRIMINAL/OnlyFans#400]
2020-08-27 11:12:40,950 ERROR errors HTTPSConnectionPool(host='i.4cdn.org', port=443): Read timed out.
 Tries: 0
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='i.4cdn.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\DIGITALCRIMINAL\modules\fourchan.py", line 219, in download
    for chunk in r.iter_content(chunk_size=1024):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 758, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='i.4cdn.org', port=443): Read timed out.

**Comment by DIGITALCRIMINAL** [comment]
Fixed with the latest commit
