### ISSUE TITLE
'charmap' codec can't decode byte error

### ISSUE THREAD

**Issue by pmd006** [DIGITALCRIMINAL/OnlyFans#407]
Script logs in and begins scraping through subscriptions. Gets to a specific account and outputs this to the CMD prompt:

Scrape Processing
Name: <would be here>
Type: Profile
Scraping [photo]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-09-08 12:37:05,316 ERROR errors 'charmap' codec can't decode byte 0x81 in position 421955: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\plex\Downloads\OnlyFans-master\datascraper\main_datascraper.py", line 236, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\plex\Downloads\OnlyFans-master\modules\onlyfans.py", line 104, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\plex\Downloads\OnlyFans-master\modules\onlyfans.py", line 583, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "C:\Users\plex\Downloads\OnlyFans-master\helpers\main_helper.py", line 115, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\plex\Downloads\OnlyFans-master\extras\OFRenamer\start.py", line 87, in start
    metadatas = json.load(open(metadata_filepath))
  File "C:\Users\plex\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\plex\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 421955: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\plex\Downloads\OnlyFans-master\start_ofd.py", line 9, in <module>
    main_datascraper.start_datascraper()
  File "C:\Users\plex\Downloads\OnlyFans-master\datascraper\main_datascraper.py", line 256, in start_datascraper
    input()
KeyboardInterrupt

**Comment by pmd006** [comment]
There were two content creators that were causing the error. I was able to blacklist them as a workaround and the rest of the scrapping went through and the script is now downloading files just fine.

**Comment by DIGITALCRIMINAL** [comment]
What are the two creators?

**Comment by pmd006** [comment]
@sarahferguson and @sarahbaby5454. Is there any additional debugging I can enable or logging I can turn on that can help narrow down the issue?

**Comment by DIGITALCRIMINAL** [comment]
What is the filename format

**Comment by pmd006** [comment]
"file_name_format": "{date}_{file_name}.{ext}",

**Comment by DIGITALCRIMINAL** [comment]
@pmd006 open start.py in extras/OFRenamer and replace line 87 with `metadatas = json.load(open(metadata_filepath, encoding='utf-8'))`

Should work.

You can do that or wait for the next commit which will be in a few hours.

**Comment by pmd006** [comment]
I edited the line as you suggested, still seeing an error though:

Scrape Processing
Name: sarahbaby5454
Type: Profile
Scraping [photo]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-09-10 13:12:21,495 ERROR errors 'utf-8' codec can't decode byte 0x9c in position 421890: invalid start byte
Traceback (most recent call last):
  File "C:\Users\plex\Downloads\OnlyFans-master\datascraper\main_datascraper.py", line 236, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\plex\Downloads\OnlyFans-master\modules\onlyfans.py", line 104, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\plex\Downloads\OnlyFans-master\modules\onlyfans.py", line 583, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "C:\Users\plex\Downloads\OnlyFans-master\helpers\main_helper.py", line 115, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\plex\Downloads\OnlyFans-master\extras\OFRenamer\start.py", line 87, in start
    metadatas = json.load(open(metadata_filepath, encoding='utf-8'))
  File "C:\Users\plex\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\plex\AppData\Local\Programs\Python\Python38-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 421890: invalid start byte

**Comment by pmd006** [comment]
I think it was maybe an issue with the .json files in the Metadata folder under each creator. 

Poking around at those files, two of them under those creators looked like they had errors (viewed using Notepad++ showed a ton of red)

I renamed the two files that looked like they had errors so the scraper would recreate them, and now its working.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, it's most likely an emoji or something that wasn't encoded properly.
