### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#41]
This is what I get when I try to install requirements in Linux:

>Requirement already satisfied: requests in /media/sdw1/holonet81/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.22.0)
Collecting beautifulsoup4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f9/d9/183705a87492249b212d88eef740995f55076195bcf45ed59306c146e42d/beautifulsoup4-4.8.1-py2-none-any.whl
Requirement already satisfied: urllib3 in /media/sdw1/holonet81/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.25.6)
Collecting win32-setctime (from -r requirements.txt (line 4))
  ERROR: Could not find a version that satisfies the requirement win32-setctime (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for win32-setctime (from -r requirements.txt (line 4))

What am I doing wrong here?

**Comment by DIGITALCRIMINAL** [comment]
You're using Python 2.7. You need Python 3.7.

**Comment by ElusiveZatchmo** [comment]
Fixed that, not I'm getting this:

> Traceback (most recent call last):
  File "Start Datascraper.py", line 55, in <module>
    result = x.start_datascraper(session, username, app_token)
  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 58, in start_datascraper
    pool.starmap(download_media, product(media_set, [session], [directory], [username]))
  File "/media/sdw1/holonet81/python3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/media/sdw1/holonet81/python3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/media/sdw1/holonet81/python3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/media/sdw1/holonet81/python3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 216, in download_media
    setctime(directory, timestamp)
  File "/media/sdw1/holonet81/python3/lib/python3.7/site-packages/win32_setctime.py", line 44, in setctime
    raise OSError("This function is only available for the Windows platform.")
OSError: This function is only available for the Windows platform.

**Comment by DIGITALCRIMINAL** [comment]
Ohh are you using windows, linux or macos?

**Comment by ElusiveZatchmo** [comment]
Yes I am, is it not compatible with Linux?

**Comment by DIGITALCRIMINAL** [comment]
It is
Refer to this issue here:
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/28#issue-497772144
I will push a fix for it later this week.

**Comment by ElusiveZatchmo** [comment]
Cool; thanks!
