### ISSUE TITLE
Failure to start due to AttributeError

### ISSUE THREAD

**Issue by Thepenguin9** [DIGITALCRIMINAL/OnlyFans#411]
After installing the requirements, the start script errors immediately 
```
D:\yeahnah\OnlyFans-5.3>python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "D:\yeahnah\OnlyFans-5.3\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "D:\yeahnah\OnlyFans-5.3\helpers\main_helper.py", line 21, in <module>
    import extras.OFRenamer.start as ofrenamer
  File "D:\yeahnah\OnlyFans-5.3\extras\OFRenamer\start.py", line 3, in <module>
    import helpers.main_helper as main_helper
AttributeError: module 'helpers' has no attribute 'main_helper'
```

And the results of pip to show I have installed requirements
```
D:\yeahnah\OnlyFans-5.3>pip install -r requirements.txt
Requirement already satisfied: requests in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: beautifulsoup4 in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 2)) (4.9.1)
Requirement already satisfied: urllib3 in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 3)) (1.25.10)
Requirement already satisfied: win32-setctime in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: lxml in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 5)) (4.5.2)
Requirement already satisfied: pysocks in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: idna<3,>=2.5 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program files\python36\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python36\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0.1)
```

**Comment by Thepenguin9** [comment]
Whilst the console shows it running in 3.6, I have tried in IDLE as well to the same effect. Though I am removing the 3.6 instance in case that was the issue

**Comment by Thepenguin9** [comment]
An outdated Windows Terminal instance seemed to be the problem
