### ISSUE TITLE
ERROR errors 'text"

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#412]
Scrape Processing
Name: Profile
Type: Profile
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
2020-09-11 02:42:42,209 ERROR errors 'text'
Traceback (most recent call last):
File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 236, in start_datascraper
result = x.start_datascraper(
File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 103, in start_datascraper
results = prepare_scraper(
File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 551, in prepare_scraper
media_set = pool.starmap(media_scraper, product(
File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
return self._map_async(func, iterable, starmapstar, chunksize).get()
File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
raise self._value
File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 377, in media_scraper
text = media_api["rawText"] if media_api["rawText"] else media_api["text"]
KeyError: 'text'

**Comment by avekifes** [comment]
This is with the latest commits.

**Comment by DIGITALCRIMINAL** [comment]
Use the latest
