### ISSUE TITLE
cant seem to get it to start after installation

### ISSUE THREAD

**Issue by stuffnstuffx** [DIGITALCRIMINAL/OnlyFans#415]
Hello there, so I just managed to install this on my system but now I cant start it. i have tried time and again but to no avail. So below is what I'm getting.

*******@user:/mnt/shared/onlyfans$ python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/mnt/shared/onlyfans/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/mnt/shared/onlyfans/helpers/main_helper.py", line 153
    writer.writerow({**{media_type: "valid"}, **item})
                      ^
SyntaxError: invalid syntax
*******@user:/mnt/shared/onlyfans$

**Comment by stuffnstuffx** [comment]
found out i was having issues with my python version which was **3.5**, upgraded to **python 3.8**
used _**pip3.8 install -r requirements.txt**_
afterwards started it using **_python3.8 start_ofd.py_**
