### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by DMCK96** [DIGITALCRIMINAL/OnlyFans#43]
Stack trace below, Python 3.7.1 on Windows 64bit.

`Scraping Images. Should take less than a minute.
Traceback (most recent call last):
  File "start.py", line 55, in <module>
    result = x.start_datascraper(session, username, app_token)
  File "D:\OFRip\modules\onlyfans.py", line 49, in start_datascraper
    response = media_scraper(session, *item[1])
  File "D:\OFRip\modules\onlyfans.py", line 168, in media_scraper
    media_set = pool.starmap(scrape_array, product(offset_array, [session]))
  File "C:\Users\halo6\AppData\Local\Programs\Python\Python35-32\lib\multiprocessing\pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\halo6\AppData\Local\Programs\Python\Python35-32\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Users\halo6\AppData\Local\Programs\Python\Python35-32\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\halo6\AppData\Local\Programs\Python\Python35-32\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\OFRip\modules\onlyfans.py", line 148, in scrape_array
    dt = datetime.fromisoformat(media_api["postedAt"]).replace(tzinfo=None).strftime(
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'`

**Comment by DIGITALCRIMINAL** [comment]
Python isn't using the "Python37" directory, it's using the "Python35-32".
Type "Python" in CMD to check what the default version is
