### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'min_drive_space'

### ISSUE THREAD

**Issue by dharbigt** [DIGITALCRIMINAL/OnlyFans#430]
I'm seeing this under 5.4 under macOS and CentOS.  I'm concerned it must be something with the config, but I've tried a lot of things. 

- CentOS Linux release 7.8.2003
- Python 3.8.3

```=> 0
hostname; ./start_ofd.py -m
Exporting Metadata Only
Traceback (most recent call last):
  File "./start_ofd.py", line 9, in <module>
    main_datascraper.start_datascraper()
  File "/home/username/OnlyFans-5.4/datascraper/main_datascraper.py", line 33, in start_datascraper
    json_config, json_config2 = main_helper.get_config(config_path)
  File "/home/username/OnlyFans-5.4/helpers/main_helper.py", line 331, in get_config
    json_config2 = json.loads(json.dumps(make_config.start(
  File "/home/username/OnlyFans-5.4/classes/make_config.py", line 226, in __init__
    self.settings = Settings(**settings)
TypeError: __init__() got an unexpected keyword argument 'min_drive_space'
```

**Comment by dharbigt** [comment]
Using the latest (648f00bbd759f9c84eb6f44b601fa9a7432e7e21) I have a different error that persists on both platforms:

```=> 0
hostname; ./start_ofd.py
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
2020-10-01 11:50:38,176 ERROR errors [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/home/username/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    x.assign_vars(json_auth, json_config,
  File "/home/username/OnlyFans/modules/onlyfans.py", line 51, in assign_vars
    j_directory = main_helper.get_directory(
  File "/home/username/OnlyFans/helpers/main_helper.py", line 234, in get_directory
    directory = check_space(new_directories, min_size=min_drive_space)
  File "/home/username/OnlyFans/helpers/main_helper.py", line 244, in check_space
    obj_Disk = psutil.disk_usage(drive)
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/local/lib/python3.8/site-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by DIGITALCRIMINAL** [comment]
I'm guessing your download_paths is empty?

**Comment by dharbigt** [comment]
My apologies, that may be what I am confused about. I've tried a few values in the download_paths field but I am not sure what really goes there or if it needs to be modified at all.

```"settings": {
        "auto_choice": "",
        "auto_scrape_names": true,
        "auto_scrape_apis": true,
        "download_paths": [
          "{site_name}"
        ],
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""
      },```

**Comment by DIGITALCRIMINAL** [comment]
Ahh, you're on Linux so it's different. I'll sort it.

**Comment by dharbigt** [comment]
Much obliged. FYI, the same thing seems to be happening under macsOS (`10.15.6 (19G2021)`). Probably doesn't help much, but here is the message from that:

```=> 0
hostname; fg
./start_ofd.py
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
2020-10-01 12:00:43,717 ERROR errors [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/Users/username/lib/src/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    x.assign_vars(json_auth, json_config,
  File "/Users/username/lib/src/OnlyFans/modules/onlyfans.py", line 51, in assign_vars
    j_directory = main_helper.get_directory(
  File "/Users/username/lib/src/OnlyFans/helpers/main_helper.py", line 234, in get_directory
    directory = check_space(new_directories, min_size=min_drive_space)
  File "/Users/username/lib/src/OnlyFans/helpers/main_helper.py", line 244, in check_space
    obj_Disk = psutil.disk_usage(drive)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/psutil/__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''```

**Comment by DIGITALCRIMINAL** [comment]
Only way I can fix this right now is if you edit helpers/main_helper and add

`print(drive,download_path)`

Under line 243
![image](https://user-images.githubusercontent.com/21285176/94835353-7ccda200-0409-11eb-8c62-c1e06637a472.png)

**Comment by DIGITALCRIMINAL** [comment]
Nvm, ima fix it

**Comment by dharbigt** [comment]
It doesn't seem to have. Here's what I get after pulling the latest commit (`b5096555b7b367038de9b1c86ee264f7e09d0eea`):

```=> 0
hostname; ./start_ofd.py
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
 /home/username/OnlyFans/.sites/OnlyFans
2020-10-01 12:39:10,551 ERROR errors [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/home/username/OnlyFans/datascraper/main_datascraper.py", line 104, in start_datascraper
    x.assign_vars(json_auth, json_config,
  File "/home/username/OnlyFans/modules/onlyfans.py", line 51, in assign_vars
    j_directory = main_helper.get_directory(
  File "/home/username/OnlyFans/helpers/main_helper.py", line 233, in get_directory
    directory = check_space(new_directories, min_size=min_drive_space)
  File "/home/username/OnlyFans/helpers/main_helper.py", line 244, in check_space
    obj_Disk = psutil.disk_usage(drive)
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/local/lib/python3.8/site-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''```

**Comment by dharbigt** [comment]
Greetings,
I edited 243 of main_helper.py to use `download_path` instead of `drive` which seems to work under UN*X systems. 

It might work to use `download_path` if  `drive` is empty or zero.

```            obj_Disk = psutil.disk_usage(download_path)```

**Comment by dharbigt** [comment]
Well, it's off and running on my end. Hope this helps you a little. Rock on!

**Comment by DIGITALCRIMINAL** [comment]
Smh I meant to do that in the same commit.

The script has to create the folder first before checking space otherwise it will get another error.
Thanks for reminding me.
