### ISSUE TITLE
Weird file name issues

### ISSUE THREAD

**Issue by valdearg** [DIGITALCRIMINAL/OnlyFans#435]
Not sure if this is a bug, but getting a bit of strange behaviour after changing the filename format.

I downloaded the users before, but wanted to change the filename format to help with sorting albums. Initially the filename format was the default: `"{file_name}.{ext}"` but I've changed this to `"{post_id} ({date})/{file_name}.{ext}"`.

If I run with this going on, it reports the "No such file or directory" error:

```
2020-10-03 11:36:19,384 ERROR errors [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans\\<OnlyFans Username>\\Posts\\Images\\53537805 (29-09-2020)\\1440x1920_3d2d93c5b60658e00b0385597652ed06.jpg'
Traceback (most recent call last):
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans\\<OnlyFans Username>\\Posts\\Images\\1440x1920_3d2d93c5b60658e00b0385597652ed06.jpg' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans\\<OnlyFans Username>\\Posts\\Images\\53537805 (29-09-2020)\\1440x1920_3d2d93c5b60658e00b0385597652ed06.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 483, in prepare_scraper
    main_helper.export_archive(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 158, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 94, in start
    metadata.valid = fix_metadata(
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_metadata
    pool.starmap(start, product(
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 62, in start
    filepath = update(filepath)
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 59, in update
    shutil.move(filepath, new_format)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans\\<OnlyFans Username>\\Posts\\Images\\53537805 (29-09-2020)\\1440x1920_3d2d93c5b60658e00b0385597652ed06.jpg'
```

I thought I'd then change the `download_paths` to a new location just in case. Weirdly, this time it downloads into the previous default location, e.g.

`2020-10-03 11:39:23,853 INFO downloads Path: G:\Scripts\OnlyFans\.sites\OnlyFans2\<OnlyFans Username>\Messages\Images\1080x1647_6d6e97f463bc89cfcee3dfb619943d55.jpg`

But if I then run the script a second time, I get the same error as previously:

```
2020-10-03 11:41:30,837 ERROR errors [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans2\\<OnlyFans Username>\\Posts\\Images\\50764541 (20-09-2020)\\1080x1593_f1f3ffbf5da3382bb4e4de8c75d14a04.jpg'
Traceback (most recent call last):
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans2\\<OnlyFans Username>\\Posts\\Images\\1080x1593_f1f3ffbf5da3382bb4e4de8c75d14a04.jpg' -> 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans2\\<OnlyFans Username>\\Posts\\Images\\50764541 (20-09-2020)\\1080x1593_f1f3ffbf5da3382bb4e4de8c75d14a04.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 483, in prepare_scraper
    main_helper.export_archive(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 158, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 94, in start
    metadata.valid = fix_metadata(
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 82, in fix_metadata
    pool.starmap(start, product(
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 62, in start
    filepath = update(filepath)
  File "G:\Scripts\OnlyFans\extras\OFRenamer\start.py", line 59, in update
    shutil.move(filepath, new_format)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\valdearg.NEKO\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans2\\<OnlyFans Username>\\Posts\\Images\\50764541 (20-09-2020)\\1080x1593_f1f3ffbf5da3382bb4e4de8c75d14a04.jpg'
```

**Comment by DIGITALCRIMINAL** [comment]
Can't do folder structure in the file_name_paths atm

**Comment by DIGITALCRIMINAL** [comment]
Downloaded latest commit and put ``{post_id} ({date})`` into  file_directory_format in the config and it will work.
