### ISSUE TITLE
SyntaxError: invalid syntax. 

### ISSUE THREAD

**Issue by Badvibesforever** [DIGITALCRIMINAL/OnlyFans#436]
####@####MacBook-Pro onlyfans-5.4 % python start_ofd.py                                                                              
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/Users/####/Desktop/OnlyFans-5.4/tests/main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "/Users/#####/Desktop/OnlyFans-5.4/helpers/main_helper.py", line 153
    writer.writerow({**{media_type: "valid"}, **item})
                      ^
SyntaxError: invalid syntax
####@###-MacBook-Pro onlyfans-5.4 % 

can't create config file

**Comment by DIGITALCRIMINAL** [comment]
Download from Master
