### ISSUE TITLE
Error message while scraping

### ISSUE THREAD

**Issue by dkwtfigo** [DIGITALCRIMINAL/OnlyFans#437]
Just installed the latest version, getting this error now. No idea what any of it means tho...maybe someone here does and can help out. Thanks.
(Folder is called 5.3 because I haven't renamed it since. I'm running 5.4 with all the latest commits.)

> Type: Profile
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
Found: Posts
2020-10-06 00:34:55,884 ERROR errors find_between() missing 1 required positional argument: 'end'
Traceback (most recent call last):
  File "/Users/XY/Downloads/OnlyFans-5.3/datascraper/main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "/Users/XY/Downloads/OnlyFans-5.3/modules/onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "/Users/XY/Downloads/OnlyFans-5.3/modules/onlyfans.py", line 486, in prepare_scraper
    main_helper.export_archive(
  File "/Users/XY/Downloads/OnlyFans-5.3/helpers/main_helper.py", line 159, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/Users/XY/Downloads/OnlyFans-5.3/extras/OFRenamer/start.py", line 136, in start
    metadata.valid = fix_metadata(
  File "/Users/XY/Downloads/OnlyFans-5.3/extras/OFRenamer/start.py", line 113, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/XY/Downloads/OnlyFans-5.3/extras/OFRenamer/start.py", line 20, in start
    q = main_helper.find_between(
TypeError: find_between() missing 1 required positional argument: 'end'

**Comment by DIGITALCRIMINAL** [comment]
What's your filename format

**Comment by dkwtfigo** [comment]
You mean this part? I didn't change anything in the settings other than adding my auth data

> "file_directory_format": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": "",
        "webhook": true

**Comment by DIGITALCRIMINAL** [comment]
Who were you scraping?

**Comment by dkwtfigo** [comment]
it's tsunderebean

**Comment by kervala** [comment]
I updated source from Git and I have the same message: 

`Scrape Processing
Name: kervala
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Profile
Scraping [photo]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scrape Attempt: 1/100
No Posts Found.
2020-10-06 12:39:31,797 ERROR errors find_between() missing 1 required positional argument: 'end'
Traceback (most recent call last):
  File "/mnt/e/onlyfans/OnlyFans/datascraper/main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "/mnt/e/onlyfans/OnlyFans/modules/onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "/mnt/e/onlyfans/OnlyFans/modules/onlyfans.py", line 486, in prepare_scraper
    main_helper.export_archive(
  File "/mnt/e/onlyfans/OnlyFans/helpers/main_helper.py", line 159, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/mnt/e/onlyfans/OnlyFans/extras/OFRenamer/start.py", line 136, in start
    metadata.valid = fix_metadata(
  File "/mnt/e/onlyfans/OnlyFans/extras/OFRenamer/start.py", line 113, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/e/onlyfans/OnlyFans/extras/OFRenamer/start.py", line 20, in start
    q = main_helper.find_between(
TypeError: find_between() missing 1 required positional argument: 'end'`

**Comment by kervala** [comment]
I tried to check what user was causing the issue and even with my own account it's reproducible :)

So if you want to test, you can test with me : https://onlyfans.com/kervala (my account is free)

**Comment by kervala** [comment]
I reverted to commit https://github.com/DIGITALCRIMINAL/OnlyFans/commit/9780043b3af9305d310dcfcfcc7a0958d032acde and it didn't have any issue :)

**Comment by DIGITALCRIMINAL** [comment]
Dang, I can't recreate the issue, but I have an idea of what is it. I'm currently redoing the whole directory coding.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by incogrito** [comment]
Still happening for me on adde1bd with Python 3.8.6

**Comment by choadrocker** [comment]
same problem with adde1bd20ad3fbece763a7c30f1be6b9ba44ea47

**Comment by DIGITALCRIMINAL** [comment]
Should work for Mac and Linux now with the latest commit
