### ISSUE TITLE
Scraped folders are erroring out with tailing "\" causing download failure due to improper folder name

### ISSUE THREAD

**Issue by clydachpugsley** [DIGITALCRIMINAL/OnlyFans#438]
`Going in to the Posts folder the folders are ending with "\" erroneously causing the scraper to look for "Images"  and "Videos" when the generated folders are "Images\" and "Videos\"`

Using ceaa391

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by eggman-lab** [comment]
Tried this morning, and I'm still seeing this error.

```
**[dude@USBLINUXGW9M4M2 OnlyFans]$** date
Wed 07 Oct 2020 08:53:40 AM MDT
**[dude@USBLINUXGW9M4M2 OnlyFans]$** git pull
Already up to date.
**[dude@USBLINUXGW9M4M2 OnlyFans]$** python start_ofd.py 
Auth (V1)
Auth Attempt 1/10
Welcome Dude
Names: Username = username | 0 = All | 1 = lolasland | 2 = pasteljellies | 3 = feelingeuphoric | 4 = stormixlane
3
Scrape Processing
Name: feelingeuphoric
Scrape: a = Everything | b = Images | c = Videos | d = Audios
c
Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scrape Attempt: 1/100
Scraping [video | stream | gif]. Should take less than a minute.
No Posts Found.
2020-10-07 08:54:08,721 ERROR errors [Errno 22] Invalid argument: '/run/media/dude/exhd/.of/OnlyFans/.sites/OnlyFans/feelingeuphoric/Posts/Free/Videos\\'
Traceback (most recent call last):
  File "/run/media/dude/exhd/.of/OnlyFans/datascraper/main_datascraper.py", line 242, in start_datascraper
    session, username, site_name, app_token, choice_type=value)
  File "/run/media/dude/exhd/.of/OnlyFans/modules/onlyfans.py", line 117, in start_datascraper
    sessions, site_name, item)
  File "/run/media/dude/exhd/.of/OnlyFans/modules/onlyfans.py", line 461, in prepare_scraper
    media_set = main_helper.format_media_set(media_set)
  File "/run/media/dude/exhd/.of/OnlyFans/helpers/main_helper.py", line 134, in format_media_set
    os.makedirs(location_directory+"\\", exexhdist_ok=True)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/run/media/dude/exhd/.of/OnlyFans/.sites/OnlyFans/feelingeuphoric/Posts/Free/Videos\\'
^CTraceback (most recent call last):
  File "/run/media/dude/exhd/.of/OnlyFans/datascraper/main_datascraper.py", line 242, in start_datascraper
    session, username, site_name, app_token, choice_type=value)
  File "/run/media/dude/exhd/.of/OnlyFans/modules/onlyfans.py", line 117, in start_datascraper
    sessions, site_name, item)
  File "/run/media/dude/exhd/.of/OnlyFans/modules/onlyfans.py", line 461, in prepare_scraper
    media_set = main_helper.format_media_set(media_set)
  File "/run/media/dude/exhd/.of/OnlyFans/helpers/main_helper.py", line 134, in format_media_set
    os.makedirs(location_directory+"\\", exist_ok=True)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/run/media/dude/exhd/.of/OnlyFans/.sites/OnlyFans/feelingeuphoric/Posts/Free/Videos\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start_ofd.py", line 10, in <module>
    main_datascraper.start_datascraper()
  File "/run/media/dude/exhd/.of/OnlyFans/datascraper/main_datascraper.py", line 271, in start_datascraper
    input()
KeyboardInterrupt
```

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by clydachpugsley** [comment]
I have been using 3.8.5 and pip is latest.
It seems the changes have made datascraper break
```
`Traceback (most recent call last):
  File "/home/OnlyFans/datascraper/main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "/home/OnlyFans/modules/onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "/home/OnlyFans/modules/onlyfans.py", line 475, in prepare_scraper
    main_helper.export_archive(
  File "/home/OnlyFans/helpers/main_helper.py", line 162, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/home/OnlyFans/extras/OFRenamer/start.py", line 134, in start
    metadata.valid = fix_metadata(
  File "/home/OnlyFans/extras/OFRenamer/start.py", line 114, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, 
chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/OnlyFans/extras/OFRenamer/start.py", line 20, in start
    q = main_helper.find_between(
TypeError: find_between() missing 1 required positional argument: 'end'
```

**Comment by DIGITALCRIMINAL** [comment]
Sorry, I was replying to the guy before you but they deleted their comment... So the original issue has been fixed right?

**Comment by clydachpugsley** [comment]
I cant be for certain as im not sure if the scraper is getting to the part where it makes the folders. Because it errors out  after picking username to rip. I dont know if it is reaching the folder creation spot as the entire scraper is broken at the moment

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/437
