### ISSUE TITLE
Specifying another download path causes error

### ISSUE THREAD

**Issue by edwardsdean** [DIGITALCRIMINAL/OnlyFans#439]
When setting a download path it will error out with the bellow

Error:
C:\Users\Administrator\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/Administrator/PycharmProjects/untitled/OnlyFans-master/start_ofd.py
Site: 0 = onlyfans | 1 = starsavn | 2 = fourchan | 3 = bbwchan | x = Exit
0
Auth (V1)
Auth Attempt 1/10
Welcome Dean Edwards
Names: Username = username | 0 = All | 1 = camille_lalalal | 2 = deric777 | 3 = jenandfreddie | 4 = ywzzz
4
Scrape Processing
Name: ywzzz
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Profile
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scrape Attempt: 1/100
No Posts Found.
2020-10-06 14:55:40,563 ERROR errors [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\#torrents\\manual\\OnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg' -> 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\datascraper\main_datascraper.py", line 242, in start_datascraper
    session, username, site_name, app_token, choice_type=value)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 117, in start_datascraper
    sessions, site_name, item)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 487, in prepare_scraper
    metadata_set, archive_directory, json_settings)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\helpers\main_helper.py", line 159, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 137, in start
    metadata.valid, json_settings, username, site_name, category)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 114, in fix_metadata
    posts, [metadata_categories]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 87, in start
    filepath, old_filepath = update(filepath)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 84, in update
    shutil.move(filepath, new_format)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'

Config:
"onlyfans": {
      "auth": {
        "username": "REDACTED",
        "auth_id": "REDACTED",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "REDACTED",
        "fp": "REDACTED",
        "app_token": "REDACTED",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_paths": [
          "x:/#torrents/manual/OnlyFans_rips/"
        ],
        "file_directory_format": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": "",
        "webhook": true
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    },

**Comment by Sociopaat** [comment]
Seems like on linux it's creating directories like "Videos\/" for me, a "windows slash" on folders.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by edwardsdean** [comment]
still having the same issue

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by edwardsdean** [comment]
i am not getting a diferent error now, and seems to be stuck on the Scraping [photo]. section

Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scrape Attempt: 1/100
2020-10-07 16:48:24,992 ERROR errors Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 443, in prepare_scraper
    media_set2 = pool.starmap(media_scraper, product(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 575, in media_scraper
    text = main_helper.clean_text(text)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\helpers\main_helper.py", line 106, in clean_text
    string = BeautifulSoup(string, 'lxml').get_text()
  File "C:\Users\Administrator\PycharmProjects\untitled\venv\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Scraping [photo]. Should take less than a minute.

**Comment by DIGITALCRIMINAL** [comment]
You need to install the requirements to 3.8

**Comment by edwardsdean** [comment]
Hey Back to the orignal error now


Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
No Posts Found.
2020-10-08 09:18:03,215 ERROR errors [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\1280x720_172fcf06a11f76ae3536921d67fa64f7.jpg'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 781, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\#torrents\\manual\\OnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\1280x720_172fcf06a11f76ae3536921d67fa64f7.jpg' -> 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\1280x720_172fcf06a11f76ae3536921d67fa64f7.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 475, in prepare_scraper
    main_helper.export_archive(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\helpers\main_helper.py", line 162, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 134, in start
    metadata.valid = fix_metadata(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 114, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 88, in start
    filepath, old_filepath = update(filepath)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 85, in update
    shutil.move(filepath, new_format)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 795, in move
    copy_function(src, real_dst)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\1280x720_172fcf06a11f76ae3536921d67fa64f7.jpg'

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/437

**Comment by edwardsdean** [comment]
still seem to be getting the same error


Name: ywzzz
Scrape: a = Everything | b = Images | c = Videos | d = Audios
a
Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
No Highlights Found.
Type: Posts
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
No Posts Found.
2020-10-08 16:08:59,637 ERROR errors [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 781, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\#torrents\\manual\\OnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg' -> 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 116, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\modules\onlyfans.py", line 475, in prepare_scraper
    main_helper.export_archive(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\helpers\main_helper.py", line 162, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 134, in start
    metadata.valid = fix_metadata(
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 114, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 87, in start
    filepath, old_filepath = update(filepath)
  File "C:\Users\Administrator\PycharmProjects\untitled\OnlyFans-master\extras\OFRenamer\start.py", line 84, in update
    shutil.move(filepath, new_format)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 795, in move
    copy_function(src, real_dst)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\#torrentsmanualOnlyFans_rips\\ywzzz\\Posts\\Free\\Images\\453x734_04c3d574ce08e33202c29253c73814d6.jpg'

**Comment by DIGITALCRIMINAL** [comment]
What's your download path

**Comment by edwardsdean** [comment]
should be going to here `x:/#torrents/manual/OnlyFans_rips/` it was working on a previous build, thats attached from 2020-08-13 10:13:00 AEST so not sure what has changed since then
[OnlyFans-master.zip](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5345515/OnlyFans-master.zip)

**Comment by DIGITALCRIMINAL** [comment]
Try this file name format
`x:/#torrents/manual/OnlyFans_rips`

**Comment by edwardsdean** [comment]
i have figured out what i causing the issue, in the metadata folder the directrory was like this `"directory": "X:/#torrents/manual/OnlyFans_rips\\ywzzz\\Posts\\Free\\Images/"` and i changed to to be like this `"directory": ""directory": "x:\\#torrents\\manual\\OnlyFans_rips\\ywzzz\\Posts\\Free\\Images"` i did this for both Archived.json and Posts.json

i also changed the config file to have the have the bellow
`"settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_paths": [
          "x:\\#torrents\\manual\\OnlyFans_rips\\"
        ],
        "file_directory_format": "",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": "",
        "webhook": true
      },`

**Comment by DIGITALCRIMINAL** [comment]
Hmm, strange... at least it works now.

**Comment by OnlyAFan2** [comment]
I'm encountering this error now as a well. On current build. Nothing has changed on my end and the download path used to work fine in older builds

Running on macOS with Python 3.8.5

Error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/OnlyFans/VolumeshomewhateverOnlyFansfallingdevilPostsFreeImages/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg'
```

Config file:

```
        "download_paths": [
                "/Volumes/home/whatever/OnlyFans/"
        ],
```

It would appear to me that for whatever reason, the path from the config file is being read but is having all forward-slashes stripped from it. Additionally the script appears to be reading the `download_path` variable at least partially but then prepending it's own path regardless

**Comment by DIGITALCRIMINAL** [comment]
> I'm encountering this error now as a well. On current build. Nothing has changed on my end and the download path used to work fine in older builds
> 
> Running on macOS with Python 3.8.5
> 
> Error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/OnlyFans/VolumeshomewhateverOnlyFansfallingdevilPostsFreeImages/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg'
> ```
> 
> Config file:
> 
> ```
>         "download_paths": [
>                 "/Volumes/home/whatever/OnlyFans/"
>         ],
> ```
> 
> It would appear to me that for whatever reason, the path from the config file is being read but is having all forward-slashes stripped from it. Additionally the script appears to be reading the `download_path` variable at least partially but then prepending it's own path regardless.
> 
> Edit: Found the log file, posting the full stacktrace now
> 
> ```
> 2020-10-12 17:58:18,981 ERROR errors [Errno 2] No such file or directory: '/Users/user/OnlyFans/VolumeshomewhateverOnlyFansfallingdevilPostsFreeImages/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg'
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 788, in move
>     os.rename(src, real_dst)
> FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/home/whatever/OnlyFans/fallingdevil/Posts/Free/Images/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg' -> '/Users/user/OnlyFans/VolumeshomewhateverOnlyFansfallingdevilPostsFreeImages/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/user/OnlyFans/datascraper/main_datascraper.py", line 241, in start_datascraper
>     result = x.start_datascraper(
>   File "/Users/user/OnlyFans/modules/onlyfans.py", line 116, in start_datascraper
>     results = prepare_scraper(
>   File "/Users/user/OnlyFans/modules/onlyfans.py", line 478, in prepare_scraper
>     main_helper.export_archive(
>   File "/Users/user/OnlyFans/helpers/main_helper.py", line 165, in export_archive
>     datas2 = ofrenamer.start(archive_path, json_settings)
>   File "/Users/user/OnlyFans/extras/OFRenamer/start.py", line 136, in start
>     metadata.valid = fix_metadata(
>   File "/Users/user/OnlyFans/extras/OFRenamer/start.py", line 116, in fix_metadata
>     old_folders = pool.starmap(start, product(
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
>     raise self._value
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/Users/user/OnlyFans/extras/OFRenamer/start.py", line 87, in start
>     filepath, old_filepath = update(filepath)
>   File "/Users/user/OnlyFans/extras/OFRenamer/start.py", line 84, in update
>     shutil.move(filepath, new_format)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 802, in move
>     copy_function(src, real_dst)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 432, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/OnlyFans/VolumeshomewhateverOnlyFansfallingdevilPostsFreeImages/3024x4032_3bb3f2f9fa6db5bc30ace7b71e0ead06.jpg'
> ```

Are you on Mac or Linux?

**Comment by OnlyAFan2** [comment]
macOS as mentioned in the post

**Comment by DIGITALCRIMINAL** [comment]
> macOS as mentioned in the post

Lol, my bad I skimmed through and just went straight to the error.

I don't have a Mac, but I think the error is coming from line 20 since it replaces all the slashes.

![image](https://user-images.githubusercontent.com/21285176/95805235-ccab4380-0cfc-11eb-9fb1-b4c144a5a412.png)

It might be because of the slash at the end of the path

**Comment by OnlyAFan2** [comment]
> > macOS as mentioned in the post
> 
> Lol, my bad I skimmed through and just went straight to the error.
> 
> I don't have a Mac, but I think the error is coming from line 20/21 since it replaces all the slashes.
> 
> ![image](https://user-images.githubusercontent.com/21285176/95805235-ccab4380-0cfc-11eb-9fb1-b4c144a5a412.png)
> 
> It might be because of the slash at the end of the path

I've tried it both with and without the slash at the end and neither seem to change the outcome.

The initial line in the traceback is showing an `os.rename(src, real_dst)` which has the source list showing the proper path to the downloaded content as it should be but the mangled directory (assuming this is `real_dst`) as the path it was trying to move things to. Definitely looks like some weirdness going on with possibly the renaming module/helper

**Comment by DIGITALCRIMINAL** [comment]
> > > macOS as mentioned in the post
> > 
> > 
> > Lol, my bad I skimmed through and just went straight to the error.
> > I don't have a Mac, but I think the error is coming from line 20/21 since it replaces all the slashes.
> > ![image](https://user-images.githubusercontent.com/21285176/95805235-ccab4380-0cfc-11eb-9fb1-b4c144a5a412.png)
> > It might be because of the slash at the end of the path
> 
> I've tried it both with and without the slash at the end and neither seem to change the outcome.
> 
> The initial line in the traceback is showing an `os.rename(src, real_dst)` which has the source list showing the proper path to the downloaded content as it should be but the mangled directory (assuming this is `real_dst`) as the path it was trying to move things to. Definitely looks like some weirdness going on with possibly the renaming module/helper

To check if it's replacing the slashes, put this under line 21


            print(model_folder,q)
            input()

![image](https://user-images.githubusercontent.com/21285176/95806043-b1413800-0cfe-11eb-8923-fa9735d6739e.png)

**Comment by OnlyAFan2** [comment]
Adding those lines to the renamer gave me the following output

```
Found: Posts
/Volumes/home/whatever/OnlyFans/fallingdevil/Posts/Free/Images/ Free
/Volumes/home/whatever/OnlyFans/fallingdevil/Posts/Free/Images/ Free
/Volumes/home/whatever/OnlyFans/fallingdevil/Posts/Free/Images/ Free
```

It looks like the path is normal there so things must be messing up later on in the script during an attempted rename

**Comment by OnlyAFan2** [comment]
Super weird, I decided to try renaming my old folder and having `start_ofd.py` start fresh. When I did this the script started downloading things just fine. It'll take a while to rescrape all the content from the different models but at least it's working now.

Super strange bug but worth mentioning in case others run into a similar issue.

**Comment by DIGITALCRIMINAL** [comment]
Yeah since you changed the folder name it won't find the original metadata files and it will just start anew. 

The script reconstructs the path from the metadata file and tries to find your old content.
