### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by NotMyMainOne** [DIGITALCRIMINAL/OnlyFans#453]
Haven't had any issues in a long while now but just updated to the latest commit and got this error. I updated the requirements and they're all installed and python has been updated to 3.9 as well.

Z:\onlyfans>py start_ofd.py
Traceback (most recent call last):
  File "Z:\onlyfans\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "Z:\onlyfans\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "Z:\onlyfans\helpers\main_helper.py", line 16, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by DIGITALCRIMINAL** [comment]
You haven't installed the requirements properly
