### ISSUE TITLE
Help / issue?

### ISSUE THREAD

**Issue by jamesp132** [DIGITALCRIMINAL/OnlyFans#456]
Hi I have downloaded the latest version attempted to run it as it was working fine before. 

I receive this error

> python E:\OnlyFans-master\start_ofd.py
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "E:\OnlyFans-master\tests\main_test.py", line 20, in check_config
    json_config, json_config2 = main_helper.get_con
fig(path)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 461, in get_config
    json_config = json.load(open(config_path))
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 9 (char 318)

then cmd crashes, please can someone advise where I have gone wrong? (I 
<img width="903" alt="Screenshot 2020-10-19 at 01 20 33" src="https://user-images.githubusercontent.com/16858684/96389804-4afa6080-11a9-11eb-95d2-6c9ccb217bde.png">
have tried run it on admin / standard user account - I have also updated python to 3.9.0

[OF5.5.zip - downloaded files from the GitHub.](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5398429/OF5.5.zip)

I've attached the files I have downloaded other than my settings file as it contains information from chrome. 

thanks for any support.

**Comment by James-MF-Thomas** [comment]
read the last line... check(fill in) line 16 of the config file if i'm not mistaken.

**Comment by jamesp132** [comment]
<img width="682" alt="Screenshot 2020-10-19 at 01 38 07" src="https://user-images.githubusercontent.com/16858684/96390265-be9d6d00-11ab-11eb-85f3-22e3700844de.png">
Hey @James-MF-Thomas line 16 is blank

**Comment by DIGITALCRIMINAL** [comment]
Remove the extra { } characters inside the auth

**Comment by James-MF-Thomas** [comment]
i leave you in much better hands

**Comment by jamesp132** [comment]
@James-MF-Thomas thanks for your help 👍 
@DIGITALCRIMINAL I've just tried this no joy it still crashes

> C:\Users\james patten>python E:\OnlyFans-master\start_ofd.py
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "E:\OnlyFans-master\tests\main_test.py", line 20, in check_config
    json_config, json_config2 = main_helper.get_config(path)
  File "E:\OnlyFans-master\helpers\main_helper.py", line 461, in get_config
    json_config = json.load(open(config_path))
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\james patten\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 9 (char 318)

**Comment by DIGITALCRIMINAL** [comment]
What does the auth look like then

**Comment by jamesp132** [comment]
<img width="677" alt="Screenshot 2020-10-19 at 01 45 41" src="https://user-images.githubusercontent.com/16858684/96390475-ce698100-11ac-11eb-9df2-28cb16e451ff.png">

**Comment by DIGITALCRIMINAL** [comment]
Just delete the whole config

**Comment by jamesp132** [comment]
same thing happens, I have just downloaded the master as a fresh install. 
crashes on launch

**Comment by DIGITALCRIMINAL** [comment]
Then you're doing something wrong because it's working for me

**Comment by jamesp132** [comment]
I've just tested it on another pc with python installed same issue

**Comment by DIGITALCRIMINAL** [comment]
Did you fill in anything

**Comment by jamesp132** [comment]
Nope I ran the script like normal to get the hidden settings file to appear but it just crashes before it even gets to this

**Comment by jp1151419** [comment]
I get that error occasionally too, I haven't look into it further than noticing that restarting the script generally works. The couple times a simple restart didn't fix it a new config file from a known working backup did.

**Comment by jamesp132** [comment]
ah mine didn't work at all so I reinstalled my windows vm and it fixed it eventually :)
