### ISSUE TITLE
ERROR errors Expecting ',' delimiter: line 1 column 578100 (char 578099)

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#466]
Scrape Processing
Name: stefiedrew
Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
Found: Highlights
Type: Posts
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Found: Posts
2020-10-25 03:27:14,762 ERROR errors Expecting ',' delimiter: line 1 column 578100 (char 578099)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 117, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 473, in prepare_scraper
    main_helper.export_archive(
  File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 165, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "C:\Users\username\Desktop\OnlyFans-master\extras\OFRenamer\start.py", line 127, in start
    metadatas = json.load(open(metadata_filepath, encoding='utf-8'))
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 578100 (char 578099)

**Comment by DIGITALCRIMINAL** [comment]
It's probably a corrupt JSON file.

**Comment by avekifes** [comment]
Interesting. I only get the error when I try to scrape that particular account, though.

**Comment by Telandriq** [comment]
Receiving same error on a single account. 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:\\Telandriq\\Files\\onlyfans\\gothspvt\\Posts\\Images\\3840x2880_82a0aae27e931760e3f86f8097c3f32b.jpg' -> 'Z:\\TelandriqFilesonlyfans\\gothspvt\\Posts\\Free\\Images\\3840x2880_82a0aae27e931760e3f86f8097c3f32b.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\OnlyFans-master (2)\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "F:\Downloads\OnlyFans-master (2)\OnlyFans-master\modules\onlyfans.py", line 117, in start_datascraper
    results = prepare_scraper(
  File "F:\Downloads\OnlyFans-master (2)\OnlyFans-master\modules\onlyfans.py", line 473, in prepare_scraper
    main_helper.export_archive(
  File "F:\Downloads\OnlyFans-master (2)\OnlyFans-master\helpers\main_helper.py", line 165, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "F:\Downloads\OnlyFans-master (2)\OnlyFans-master\extras\OFRenamer\start.py", line 136, in start
    metadata.valid = fix_metadata(

**Comment by DIGITALCRIMINAL** [comment]
What accounts

**Comment by avekifes** [comment]
stefiedrew

**Comment by Telandriq** [comment]
gothspvt

**Comment by Telandriq** [comment]
> Scrape Processing
> Name: stefiedrew
> Type: Profile
> Type: Stories
> Scrape Attempt: 1/100
> No Stories Found.
> Type: Highlights
> Scrape Attempt: 1/100
> Found: Highlights
> Type: Posts
> Scrape Attempt: 1/100
> Scraping [photo]. Should take less than a minute.
> Scraping [video | stream | gif]. Should take less than a minute.
> Scraping [photo]. Should take less than a minute.
> Scraping [video | stream | gif]. Should take less than a minute.
> Scraping [photo]. Should take less than a minute.
> Scraping [video | stream | gif]. Should take less than a minute.
> Found: Posts
> 2020-10-25 03:27:14,762 ERROR errors Expecting ',' delimiter: line 1 column 578100 (char 578099)
> Traceback (most recent call last):
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
> result = x.start_datascraper(
> File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 117, in start_datascraper
> results = prepare_scraper(
> File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 473, in prepare_scraper
> main_helper.export_archive(
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 165, in export_archive
> datas2 = ofrenamer.start(archive_path, json_settings)
> File "C:\Users\username\Desktop\OnlyFans-master\extras\OFRenamer\start.py", line 127, in start
> metadatas = json.load(open(metadata_filepath, encoding='utf-8'))
> File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json__init__.py", line 293, in load
> return loads(fp.read(),
> File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json__init__.py", line 357, in loads
> return _default_decoder.decode(s)
> File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 578100 (char 578099)

So we had the same issue, deleted the problematic user folder and then it fully scraped. Something might have gotten corrupted with the user but redownloaded everything now.
