### ISSUE TITLE
UnboundLocalError: local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by thatoneguy206** [DIGITALCRIMINAL/OnlyFans#472]
Cleared out the .json files in the directory for the model.   Get this error message:

Scrape Processing
Name: alittlecutie
Type: Profile
Type: Stories
Scrape Attempt: 1/100
No Stories Found.
Type: Highlights
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Found: Highlights
Type: Posts
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Found: Posts
Type: Archived
Scrape Attempt: 1/100
Found: Archived
Type: Messages
Scrape Attempt: 1/100
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
2020-10-26 15:09:51,431 ERROR errors local variable 'url' referenced before assignment
Traceback (most recent call last):
  File "C:\OnlyFans-master\datascraper\main_datascraper.py", line 241, in start_datascraper
    result = x.start_datascraper(
  File "C:\OnlyFans-master\modules\onlyfans.py", line 117, in start_datascraper
    results = prepare_scraper(
  File "C:\OnlyFans-master\modules\onlyfans.py", line 440, in prepare_scraper
    media_set2 = pool.starmap(media_scraper, product(
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\OnlyFans-master\modules\onlyfans.py", line 531, in media_scraper
    url = urlparse(link)
  File "C:\Program Files\Python39\lib\urllib\parse.py", line 389, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
UnboundLocalError: local variable 'url' referenced before assignment

**Comment by DIGITALCRIMINAL** [comment]
I dunno how that's even possible lol. Are you using the latest commit?

**Comment by thatoneguy206** [comment]
upon further investigation it may have been due to a corrupt system file or possibly some faulty hardware.  i'll test things on my end.  thank you.
