### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by sjfer** [DIGITALCRIMINAL/OnlyFans#483]
I'm getting the following issue with the new scraper;

```
Auth (V1) Attempt 1/10
Welcome 
2020-11-07 00:20:58,690 ERROR errors 'author'
Traceback (most recent call last):
  File "/OnlyFans/datascraper/main_datascraper.py", line 115, in start_datascraper
    paid_content = module.paid_content_scraper(api)
  File "/OnlyFans/modules/onlyfans.py", line 270, in paid_content_scraper
    author = paid_content["author"]
KeyError: 'author'
```

**Comment by DIGITALCRIMINAL** [comment]
Does this always happen?

**Comment by Kurosaki22** [comment]
Pulled the latest changes, updated the requirements and also re-created the settings files.
Exact same issue for me.

**Comment by DIGITALCRIMINAL** [comment]
You've paid for content right?

**Comment by Kurosaki22** [comment]
Yes

**Comment by DIGITALCRIMINAL** [comment]
It's probably one that I haven't caught. The script handles paid messages and posts.


        try:
            author = paid_content["author"]
        except Exception as e:
            input(e)

Add this to line 270 in onlyfans.py so we can see what type of content it is

![image](https://user-images.githubusercontent.com/21285176/98428987-ff4a2100-209b-11eb-99d2-b7216cc2db74.png)

**Comment by galaxianloop** [comment]
Having the same issue as the other two users. The script throws the same error every time I launch it.

Putting in the code above produces this for me:
```
Auth (V1) Attempt 1/10
Welcome ******
'author'
```

**Comment by DIGITALCRIMINAL** [comment]
my bad... I meant input(paid_content)

**Comment by galaxianloop** [comment]
I redacted some of the values to clean up the output and maintain privacy so if you need it uncensored, just give me an email address to send it to.
```
Auth (V1) Attempt 1/10
Welcome ******
{
 'responseType': 'message',
 'text': '***',
 'lockedText': False,
 'isFree': False,
 'price': 20,
 'isMediaReady': True,
 'mediaCount': 1,
 'media': 
 [
     {
         'id': 96494780,
         'canView': True,
         'type': 'video',
         'src': '***',
         'preview': '***',
         'thumb': '***',
         'locked': None,
         'duration': 179,
         'hasError': False,
         'squarePreview': '***',
         'video': {'mp4': '***'},
         'videoSources': {'720': '***', '240': '***'},
         'source': {'source': '***'},
         'info':
         {
            'source': {'width': 1916, 'height': 1042, 'size': 0}, 
            'preview': {'width': 760, 'height': 414, 'size': 0} 
         }
     }
 ,
 'previews': [],
 'isTip': False,
 'fromUser': {
     'view': 's',
     'avatar': '***',
     'avatarThumbs': 
     {
         'c50': '***',
         'c144': '***'
     },
     'header': '***',
     'headerSize': 
     {
         'width': 750,
         'height': 1624
     },
     'headerThumbs': 
     {
         'w480': '***',
         'w760': '***'
     },
     'id': 20150917,
     'name': '***',
     'username': '***',
     'canLookStory': False,
     'canCommentStory': False,
     'hasNotViewedStory': False,
     'isVerified': False,
     'canPayInternal': True,
     'hasScheduledStream': False,
     'hasStream': False,
     'hasStories': False,
     'tipsEnabled': False,
     'tipsMin': 5,
     'tipsMax': 100,
     'bookmarked': False,
     'canBeBookmarked': True,
     'canEarn': True,
     'canAddSubscriber': True,
     'subscribePrice': 14.99,
     'subscriptionBundles': 
     [
         {
             'id': 123650,
             'discount': 40,
             'duration': 3,
             'price': 26.98,
             'canBuy': True
         },
         {
             'id': 1238461,
             'discount': 50,
             'duration': 12,
             'price': 89.94,
             'canBuy': True
         }
     ],
     'isPaywallRestriction': False,
     'unprofitable': True,
     'listsStates': 
     [
         {
             'id': 928261,
             'type': 'fans',
             'name': 'Fans',
             'hasUser': False,
             'canAddUser': False
         },
         {
             'id': 928283,
             'type': 'following',
             'name': 'Following',
             'hasUser': False,
             'canAddUser': False
         },
         {
             'id': 928312,
             'type': 'favorites',
             'name': 'Favorites',
             'hasUser': False,
             'canAddUser': True
         },
         {
             'id': 928340,
             'type': 'bookmarks',
             'name': 'Bookmarks',
             'hasUser': False,
             'canAddUser': True
         },
         {
             'id': 308454824,
             'type': 'close_friends',
             'name': 'Close Friends',
             'hasUser': False,
             'canAddUser': False
         }
     ],
     'isMuted': False,
     'subscribedBy': None,
     'subscribedByExpire': None,
     'subscribedByExpireDate': '2020-09-05T07:27:44+00:00',
     'subscribedByAutoprolong': None,
     'subscribedIsExpiredNow': True,
     'currentSubscribePrice': None,
     'subscribedOn': None,
     'subscribedOnExpiredNow': None,
     'subscribedOnDuration': None,
     'callPrice': 0,
     'lastSeen': None,
     'canReport': False
 },
 'isFromQueue': True,
 'queueId': 411199215,
 'canUnsendQueue': True,
 'unsendSecondsQueue': 1000000,
 'id': 5172123513,
 'isOpened': True,
 'isNew': False,
 'createdAt': '2020-08-11T18:45:09+00:00',
 'changedAt': '2020-08-11T18:45:09+00:00',
 'cancelSeconds': 0,
 'isLiked': False,
 'canPurchase': False
 }
```

**Comment by DIGITALCRIMINAL** [comment]
Thank you, the latest commit should fix it. The problem was you bought something from their mass messages and the API returns "fromUser" instead of "author"
