### ISSUE TITLE
Scrape OF posts with text only

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#484]
Currently, in the metadata file posts that don't have an image or video don't seem to be included

**Comment by DIGITALCRIMINAL** [comment]
Which user only has text?

**Comment by whateverman91** [comment]
Quite a few... gracemyscreen is one

**Comment by DIGITALCRIMINAL** [comment]
She has images

**Comment by whateverman91** [comment]
Not all of her posts. Some are text-only

**Comment by DIGITALCRIMINAL** [comment]
Oh; in the latest commit the script scrapes text

**Comment by whateverman91** [comment]
Got it, after updating it did start. But it crashes all times now:

```
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
2020-11-07 07:27:34,294 ERROR errors 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
Traceback (most recent call last):
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 119, in start_datascraper
    x = main_helper.process_names(
  File "/root/OnlyFans/helpers/main_helper.py", line 504, in process_names
    result = module.start_datascraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 128, in start_datascraper
    results = prepare_scraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 540, in prepare_scraper
    metadata_set2 = legacy_metadata_fixer(
  File "/root/OnlyFans/modules/onlyfans.py", line 557, in legacy_metadata_fixer
    metadata_type = import_archive(legacy_metadata_path)
  File "/root/OnlyFans/helpers/main_helper.py", line 179, in import_archive
    metadata = json.load(open(archive_path))
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

**Comment by DIGITALCRIMINAL** [comment]
Which user is this?

**Comment by whateverman91** [comment]
gracemyscreen

**Comment by DIGITALCRIMINAL** [comment]
Delete the metadata; it's probably empty

**Comment by whateverman91** [comment]
The metadata files weren't empty. Anyways, I tried deleting them (well, renaming the folder) and it didn't fix it

**Comment by DIGITALCRIMINAL** [comment]
It's the old metadata that's causing the problems.

**Comment by whateverman91** [comment]
Another piece of info: it seems that the error happens while creating the Posts.json file. The file is created, but its contents are just `{}`

**Comment by whateverman91** [comment]
Yes I did delete the old Metadata folder. And the error still happens

**Comment by DIGITALCRIMINAL** [comment]
Did you delete the images.json file?

**Comment by whateverman91** [comment]
I did delete the delete the Metadata folder so yes, also Images.json.

Here's the full log (omitted irrelevant parts):

```
root@cebb60e776ca:/# ls /mnt/gracemyscreen/
Archived  Highlights  Messages  Metadata-old  Posts  Profile  Stories
root@cebb60e776ca:/# /start.sh
Auth (V1) Attempt 1/10
Welcome ***

[...]

Scrape Processing
Name: gracemyscreen
Type: Profile
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
2020-11-08 19:17:00,434 ERROR errors 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
Traceback (most recent call last):
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 119, in start_datascraper
    x = main_helper.process_names(
  File "/root/OnlyFans/helpers/main_helper.py", line 504, in process_names
    result = module.start_datascraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 128, in start_datascraper
    results = prepare_scraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 541, in prepare_scraper
    metadata_set2 = legacy_metadata_fixer(
  File "/root/OnlyFans/modules/onlyfans.py", line 558, in legacy_metadata_fixer
    metadata_type = import_archive(legacy_metadata_path)
  File "/root/OnlyFans/helpers/main_helper.py", line 179, in import_archive
    metadata = json.load(open(archive_path))
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
^CTraceback (most recent call last):
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 119, in start_datascraper
    x = main_helper.process_names(
  File "/root/OnlyFans/helpers/main_helper.py", line 504, in process_names
    result = module.start_datascraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 128, in start_datascraper
    results = prepare_scraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 541, in prepare_scraper
    metadata_set2 = legacy_metadata_fixer(
  File "/root/OnlyFans/modules/onlyfans.py", line 558, in legacy_metadata_fixer
    metadata_type = import_archive(legacy_metadata_path)
  File "/root/OnlyFans/helpers/main_helper.py", line 179, in import_archive
    metadata = json.load(open(archive_path))
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/OnlyFans/start_ofd.py", line 10, in <module>
    main_datascraper.start_datascraper()
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 174, in start_datascraper
    input()
KeyboardInterrupt

root@cebb60e776ca:/# ls /mnt/gracemyscreen/
Archived  Highlights  Messages  Metadata  Metadata-old  Posts  Profile  Stories
root@cebb60e776ca:/# ls /mnt/gracemyscreen/Metadata
Posts.json  Stories.json
root@cebb60e776ca:/# ls -alh /mnt/gracemyscreen/Metadata
total 12K
drwxr-xr-x  4 root root  128 Nov  8 19:17 .
drwx------ 11 root root  352 Nov  8 19:16 ..
-rw-r--r--  1 root root    2 Nov  8 19:17 Posts.json
-rw-r--r--  1 root root 7.7K Nov  8 19:16 Stories.json
root@cebb60e776ca:/# cat /mnt/gracemyscreen/Metadata/Posts.json
{}
root@cebb60e776ca:/#
```

As you can see, before running the command the /mnt/gracemyscreen/Metadata folder doesn't exist (I renamed it to "Metadata - old"). Then the script starts. It crashes. I stop it with CTRL+C. The Metadata folder is created, it contains "Stores.json" and a "Posts.json". The Stories file is ok. The Posts file contains only `{}`

**Comment by whateverman91** [comment]
I'm on Ubuntu 20.04 if it helps

**Comment by DIGITALCRIMINAL** [comment]
I dunno why it's not working. It's working for me.

**Comment by DIGITALCRIMINAL** [comment]
You can the latest commit

**Comment by whateverman91** [comment]
Updated with `git pull`. Still not working, same error.

Does it work for you with the same user?

**Comment by DIGITALCRIMINAL** [comment]
Yes, I downloaded the model you provided.

Are you only scraping text?

**Comment by whateverman91** [comment]
no I tried to scrape everything.

Because this data folder contained some older data (scraped with a months-old version of this script), I went through and deleted JSON files in other sub-folders, such as inside the "Posts" folder, etc.

Not sure exactly what I deleted, but after that it started working again.

**Comment by DIGITALCRIMINAL** [comment]
Yeah, that's the old metadata folder I was talking about.  My script should have handled those files and updated them but I guess we will never know now.
