### ISSUE TITLE
Exception after script update

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#486]
After updating the script, I get an exception every time I try to run this:

```
# python3 start_ofd.py
Auth (V1) Attempt 1/10
Welcome ******
2020-11-06 23:48:54,269 ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 107, in start_datascraper
    setup = module.account_setup(api)
  File "/root/OnlyFans/modules/onlyfans.py", line 78, in account_setup
    subscriptions = api.get_subscriptions()
  File "/root/OnlyFans/apis/onlyfans/onlyfans.py", line 395, in get_subscriptions
    results += pool.starmap(multi, product(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/OnlyFans/apis/onlyfans/onlyfans.py", line 386, in multi
    subscription = subscription | subscription2
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.9

**Comment by whateverman91** [comment]
Python 3.9 isn't available everywhere. I'm on Ubuntu 20.04 and I can only get 3.8

**Comment by DIGITALCRIMINAL** [comment]
Search how to install Python 3.9 for Ubuntu
