### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by drobb0690** [DIGITALCRIMINAL/OnlyFans#488]
Since the newest update whenever i attempt to run the script i get this error

Traceback (most recent call last):
  File "G:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "G:\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "G:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 19, in <module>
    import psutil
  File "C:\Python3\lib\site-packages\psutil\__init__.py", line 145, in <module>
    from . import _pswindows as _psplatform
  File "C:\Python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'psutil._psutil_windows'

ive check and made sure psutil is installed, ive updated/installed python 3.9 and still cant figure it out.  Im on windows 10.

**Comment by DIGITALCRIMINAL** [comment]
It says you're using Python 3 and not 3.9

**Comment by drobb0690** [comment]
it is indeed 3.9
G:\OnlyFans-master\OnlyFans-master> py -V
Python 3.9.0

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements again

**Comment by drobb0690** [comment]
i fixed it, not sure how, i uninstalled and reinstalled both 3.8 and 3.9 and now it seems to work just fine.
