### ISSUE TITLE
Unsupported operand type(s) for |: 'dict' and 'dict"

### ISSUE THREAD

**Issue by SunsparcSolaris** [DIGITALCRIMINAL/OnlyFans#490]
From latest pull:

`2020-11-07 15:17:31,408 ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "M:\OnlyFans-3.9\OnlyFans-3.9\datascraper\main_datascraper.py", line 107, in start_datascraper
    setup = module.account_setup(api)
  File "M:\OnlyFans-3.9\OnlyFans-3.9\modules\onlyfans.py", line 78, in account_setup
    subscriptions = api.get_subscriptions()
  File "M:\OnlyFans-3.9\OnlyFans-3.9\apis\onlyfans\onlyfans.py", line 395, in get_subscriptions
    results += pool.starmap(multi, product(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "M:\OnlyFans-3.9\OnlyFans-3.9\apis\onlyfans\onlyfans.py", line 386, in multi
    subscription = subscription | subscription2
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'`

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.9
