### ISSUE TITLE
ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#500]
Hey there,

Just updated to the latest release, ran the requirements command and then ran the script and I'm getting the following error?

2020-11-10 17:40:58,124 ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "C:\Users\name\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 107, in start_datascraper
    setup = module.account_setup(api)
  File "C:\Users\name\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 78, in account_setup
    subscriptions = api.get_subscriptions()
  File "C:\Users\name\Documents\GitHub\OnlyFans\apis\onlyfans\onlyfans.py", line 396, in get_subscriptions
    results += pool.starmap(multi, product(
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\name\Documents\GitHub\OnlyFans\apis\onlyfans\onlyfans.py", line 387, in multi
    subscription = subscription | subscription2
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by incogrito** [comment]
You need to update to Python 3.9
