### ISSUE TITLE
metadata_locations

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#506]
Hey, just downloaded the latest commits and I'm getting the following error.

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 117, in start_datascraper
    paid_content = module.paid_content_scraper(api)
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 309, in paid_content_scraper
    x = download_media(api, subscription)
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 820, in __init__
    metadata_locations = download_info["metadata_locations"]
KeyError: 'metadata_locations'

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit
