### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by RomakaV** [DIGITALCRIMINAL/OnlyFans#513]
Issue happens right after successful auth (welcome message).
```
Traceback (most recent call last):
  File "D:\Onlyfans_Scraper\OnlyFans-5.6.1\datascraper\main_datascraper.py", line 107, in start_datascraper
    setup = module.account_setup(api)
  File "D:\Onlyfans_Scraper\OnlyFans-5.6.1\modules\onlyfans.py", line 78, in account_setup
    subscriptions = api.get_subscriptions()
  File "D:\Onlyfans_Scraper\OnlyFans-5.6.1\apis\onlyfans\onlyfans.py", line 396, in get_subscriptions
    results += pool.starmap(multi, product(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\Onlyfans_Scraper\OnlyFans-5.6.1\apis\onlyfans\onlyfans.py", line 387, in multi
    subscription = subscription | subscription2
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.9

**Comment by MinaroShikuchi** [comment]
I get this error executing the script with Python 3.9 

```
Execute the script with Python 3.9 
Press enter to continue
Site: 0 = onlyfans | x = Exit
0
Auth (V1) Attempt 1/10
Welcome XXX
2020-11-17 19:06:35,167 ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'
```
