### ISSUE TITLE
unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by rabea98** [DIGITALCRIMINAL/OnlyFans#516]
Welcome **********
2020-11-16 15:05:28,441 ERROR errors unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 107, in start_datascraper
    setup = module.account_setup(api)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 79, in account_setup
    subscriptions = api.get_subscriptions()
  File "E:\OnlyFans-master\apis\onlyfans\onlyfans.py", line 392, in get_subscriptions
    results += pool.starmap(multi, product(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\OnlyFans-master\apis\onlyfans\onlyfans.py", line 383, in multi
    subscription = subscription | subscription2
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by unpleasantallium** [comment]
Same error here since I had to install 'visual studio build tools' to install 'deepdiff[murmur]' per the requirements.

**Comment by unpleasantallium** [comment]
@rabea98   Update to python 3.9

I also had to uninstall python 3.8 and remove it from the PATH and add the 3.9 directories.

Then run `pip install -r requirements.txt` again.
