### ISSUE TITLE
Issue with directory of archived posts

### ISSUE THREAD

**Issue by galaxianloop** [DIGITALCRIMINAL/OnlyFans#520]
The script seems to expect the "Images" and "Videos" folders to be in the root of the "Archived" folder, but those folders actually get placed inside "Archived\Posts". When the script scrapes the same account again, it throws this error. I can work around this temporarily by copying the contents of the "Posts" folder and putting them into the root of "Archived", but I imagine this will break the next time the script downloads a new archived post from that account.

```
2020-11-17 04:22:19,637 ERROR errors [Errno 2] No such file or directory: 'F:\\OnlyFans-5.7\\.sites\\OnlyFans\\***\\Archived\\Images\\2020-07-01 2221x2956_5fa471651858d0d1a6d55cc72e08d828.jpg'
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\OnlyFans-5.7\\.sites\\OnlyFans\\***\\Archived\\Posts\\Images\\2020-07-01 2221x2956_5fa471651858d0d1a6d55cc72e08d828.jpg' -> 'F:\\OnlyFans-5.7\\.sites\\OnlyFans\\***\\Archived\\Images\\2020-07-01 2221x2956_5fa471651858d0d1a6d55cc72e08d828.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OnlyFans-5.7\datascraper\main_datascraper.py", line 120, in start_datascraper
    x = main_helper.process_names(
  File "F:\OnlyFans-5.7\helpers\main_helper.py", line 511, in process_names
    result = module.start_datascraper(
  File "F:\OnlyFans-5.7\modules\onlyfans.py", line 130, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans-5.7\modules\onlyfans.py", line 566, in prepare_scraper
    main_helper.export_archive(
  File "F:\OnlyFans-5.7\helpers\main_helper.py", line 200, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "F:\OnlyFans-5.7\extras\OFRenamer\start.py", line 144, in start
    metadata.valid = fix_metadata(
  File "F:\OnlyFans-5.7\extras\OFRenamer\start.py", line 122, in fix_metadata
    old_folders = pool.starmap(start, product(
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\OnlyFans-5.7\extras\OFRenamer\start.py", line 115, in start
    filepath, old_filepath = update(filepath)
  File "F:\OnlyFans-5.7\extras\OFRenamer\start.py", line 87, in update
    shutil.move(filepath, new_format)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\OnlyFans-5.7\\.sites\\OnlyFans\\***\\Archived\\Images\\2020-07-01 2221x2956_5fa471651858d0d1a6d55cc72e08d828.jpg'
```

**Comment by galaxianloop** [comment]
My bad, didn't realize this issue was already open!
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/497
