### ISSUE TITLE
Random I/O crashes

### ISSUE THREAD

**Issue by whateverman91** [DIGITALCRIMINAL/OnlyFans#524]
Once in a while, the scraper (v5.7) crashes with these I/O errors:

```
(LINK HERE - CAN'T POST BECAUSE OF COPYRIGHT)
2020-11-19 03:12:08,710 INFO downloads Path: /mnt/***/Posts/Free/Images/62611884-P1000607.JPG
2020-11-19 03:12:08,715 ERROR errors [Errno 5] Input/output error
Traceback (most recent call last):
  File "/root/OnlyFans/datascraper/main_datascraper.py", line 122, in start_datascraper
    x = main_helper.process_downloads(apis,module)
  File "/root/OnlyFans/helpers/main_helper.py", line 521, in process_downloads
    module.download_media(api, subscription)
  File "/root/OnlyFans/modules/onlyfans.py", line 854, in __init__
    pool.starmap(self.download, product(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/OnlyFans/modules/onlyfans.py", line 925, in download
    main_helper.format_image(download_path, timestamp)
  File "/root/OnlyFans/helpers/main_helper.py", line 172, in format_image
    os.utime(filepath, (timestamp, timestamp))
OSError: [Errno 5] Input/output error
```

In all cases, restarting the scraper successfully downloads the file, so the failure is transient.

Failures happen when downloading files, but maybe the app could re-try the download rather than crashing?

**Comment by DIGITALCRIMINAL** [comment]
Download the latest commit
