### ISSUE TITLE
macOS - requirements.txt: multiple package issues. 

### ISSUE THREAD

**Issue by hawktank** [DIGITALCRIMINAL/OnlyFans#531]
I saw it's developed on Windows 10 - so I figured this might help in the future if there's any macOS or Linux development. 
I've only used it successfully on Windows in the past. 

<img width="762" alt="Screen Shot 2020-11-21 at 11 43 55 AM" src="https://user-images.githubusercontent.com/54247989/99883751-138b3380-2bef-11eb-9c6a-865fb439d04c.png">

<img width="1261" alt="Screen Shot 2020-11-21 at 11 54 09 AM" src="https://user-images.githubusercontent.com/54247989/99883976-4a157e00-2bf0-11eb-82bd-916f18c7921a.png">

<img width="1265" alt="Screen Shot 2020-11-21 at 11 55 49 AM" src="https://user-images.githubusercontent.com/54247989/99884005-8517b180-2bf0-11eb-9770-c9484eadcb41.png">

<img width="1263" alt="Screen Shot 2020-11-21 at 11 55 11 AM" src="https://user-images.githubusercontent.com/54247989/99883991-6ca79700-2bf0-11eb-9a7f-bd9f9e0c64a6.png">

<img width="1261" alt="Screen Shot 2020-11-21 at 11 56 22 AM" src="https://user-images.githubusercontent.com/54247989/99884015-9660be00-2bf0-11eb-8402-d6081dd41050.png">

```
Building wheels for collected packages: psutil, ujson
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.7.3-cp27-cp27m-macosx_11_0_x86_64.whl size=233799 sha256=876b5b2cbe8fd6d55967a9233c14930605dae974a62f20025411d33fabf9424b
  Stored in directory: /Users/hawktank/Library/Caches/pip/wheels/3b/8a/d2/25b4aa99bf70907f2db25db3b6f1ce0ae24080a79bef48503c
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/hawktank/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/tmpkl4zIY
       cwd: /private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-install-71fTDg/ujson
  Complete output (79 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  creating build
  creating build/temp.macosx-11.0-x86_64-2.7
  creating build/temp.macosx-11.0-x86_64-2.7/deps
  creating build/temp.macosx-11.0-x86_64-2.7/deps/double-conversion
  creating build/temp.macosx-11.0-x86_64-2.7/deps/double-conversion/double-conversion
  creating build/temp.macosx-11.0-x86_64-2.7/lib
  creating build/temp.macosx-11.0-x86_64-2.7/python
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/bignum.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/bignum.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/fixed-dtoa.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/fixed-dtoa.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/strtod.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/strtod.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/fast-dtoa.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/fast-dtoa.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/cached-powers.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/cached-powers.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/double-conversion.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/double-conversion.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/diy-fp.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/diy-fp.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./deps/double-conversion/double-conversion/bignum-dtoa.cc -o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/bignum-dtoa.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./lib/dconv_wrapper.cc -o build/temp.macosx-11.0-x86_64-2.7/./lib/dconv_wrapper.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./python/ujson.c -o build/temp.macosx-11.0-x86_64-2.7/./python/ujson.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./python/objToJSON.c -o build/temp.macosx-11.0-x86_64-2.7/./python/objToJSON.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./python/JSONtoObj.c -o build/temp.macosx-11.0-x86_64-2.7/./python/JSONtoObj.o -D_GNU_SOURCE
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./lib/ultrajsonenc.c -o build/temp.macosx-11.0-x86_64-2.7/./lib/ultrajsonenc.o -D_GNU_SOURCE
  ./lib/ultrajsonenc.c:76:21: warning: unused variable 'g_pow10' [-Wunused-const-variable]
  static const double g_pow10[] = {1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000, 10000000000, 100000000000, 1000000000000, 10000000000000, 100000000000000, 1000000000000000};
                      ^
  1 warning generated.
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./python -I./lib -I./deps/double-conversion/double-conversion -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./lib/ultrajsondec.c -o build/temp.macosx-11.0-x86_64-2.7/./lib/ultrajsondec.o -D_GNU_SOURCE
  creating build/lib.macosx-11.0-x86_64-2.7
  c++ -bundle -undefined dynamic_lookup -Wl,-F. -L/AppleInternal/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.Internal.sdk/usr/local/libressl/lib build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/bignum.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/fixed-dtoa.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/strtod.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/fast-dtoa.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/cached-powers.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/double-conversion.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/diy-fp.o build/temp.macosx-11.0-x86_64-2.7/./deps/double-conversion/double-conversion/bignum-dtoa.o build/temp.macosx-11.0-x86_64-2.7/./lib/dconv_wrapper.o build/temp.macosx-11.0-x86_64-2.7/./python/ujson.o build/temp.macosx-11.0-x86_64-2.7/./python/objToJSON.o build/temp.macosx-11.0-x86_64-2.7/./python/JSONtoObj.o build/temp.macosx-11.0-x86_64-2.7/./lib/ultrajsonenc.o build/temp.macosx-11.0-x86_64-2.7/./lib/ultrajsondec.o -o build/lib.macosx-11.0-x86_64-2.7/ujson.so -lstdc++ -lm
  ld: warning: directory not found for option '-L/AppleInternal/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.Internal.sdk/usr/local/libressl/lib'
  installing to build/bdist.macosx-11.0-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-11.0-x86_64
  creating build/bdist.macosx-11.0-x86_64/wheel
  copying build/lib.macosx-11.0-x86_64-2.7/ujson.so -> build/bdist.macosx-11.0-x86_64/wheel
  running install_egg_info
  running egg_info
  writing ujson.egg-info/PKG-INFO
  writing top-level names to ujson.egg-info/top_level.txt
  writing dependency_links to ujson.egg-info/dependency_links.txt
  reading manifest file 'ujson.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'tests/tests.py'
  writing manifest file 'ujson.egg-info/SOURCES.txt'
  Copying ujson.egg-info to build/bdist.macosx-11.0-x86_64/wheel/ujson-2.0.3-py2.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/Users/hawktank/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/hawktank/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/hawktank/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 88, in <module>
      classifiers=[x for x in CLASSIFIERS.split("\n") if x],
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/yp/2lw3tpk56nd21dm3n9m_r23r0000gn/T/pip-build-env-OE2THK/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp27', 'cp27m', 'macosx_11_0_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for ujson
Successfully built psutil
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
```

**Comment by DIGITALCRIMINAL** [comment]
Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9 Use. Python. 3.9
