### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 23 column 3 (char 551)

### ISSUE THREAD

**Issue by DarkDownloader** [DIGITALCRIMINAL/OnlyFans#540]
Getting this error after updating to the latest version of your script. pip install -r requirements.txt states that everything is satisfied.

```
Traceback (most recent call last):
  File "C:\Users\Devin\Documents\GitHub\OnlyFans\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "C:\Users\Devin\Documents\GitHub\OnlyFans\tests\main_test.py", line 22, in check_config
    json_config, json_config2 = main_helper.get_config(path)
  File "C:\Users\Devin\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 374, in get_config
    json_config = json.load(open(config_path))
  File "C:\Users\Devin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Devin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Devin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Devin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 23 column 3 (char 551)
```

**Comment by DIGITALCRIMINAL** [comment]
Delete the config.
