### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by InsulT** [DIGITALCRIMINAL/OnlyFans#542]
Hello,

first, thank you for your awesome work :) I found an issue, not sure if it is only me or something with the script...

Traceback (most recent call last):
  File "C:\temp\OnlyFans-master_new\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "C:\temp\OnlyFans-master_new\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "C:\temp\OnlyFans-master_new\helpers\main_helper.py", line 5, in <module>
    from classes.prepare_metadata import format_variables, prepare_metadata, prepare_reformat
  File "C:\temp\OnlyFans-master_new\classes\prepare_metadata.py", line 217, in <module>
    class prepare_reformat(object):
  File "C:\temp\OnlyFans-master_new\classes\prepare_metadata.py", line 251, in prepare_reformat
    def reformat(self, unformatted_list) -> list[str]:
TypeError: 'type' object is not subscriptable
>>>

**Comment by DIGITALCRIMINAL** [comment]
Thank, you. Does this always happen?

**Comment by cyclone463** [comment]
I actually got this  error until I updated python from 3.8 to 3.9. however , after updating I get a different error. I just made a separate submission for it.
