### ISSUE TITLE
ValueError on only one user

### ISSUE THREAD

**Issue by globalgossamer** [DIGITALCRIMINAL/OnlyFans#544]
So I'm getting this error whenever the script reaches one particular user. In previous versions I would just scrape individually, but now it seems to scrape metadata for everyone before I can input anything

auto_scrape_names is set to false

I also added the user in question to a group and blacklisted it, but the script still gets tripped up when scraping 

```
ERROR errors Expected object or value
Traceback (most recent call last):
  File "D:\OF Scraper\DigitalCriminal Onlyfans\datascraper\main_datascraper.py", line 119, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "D:\OF Scraper\DigitalCriminal Onlyfans\modules\onlyfans.py", line 317, in paid_content_scraper
    new_metadata_object = process_metadata(
  File "D:\OF Scraper\DigitalCriminal Onlyfans\modules\onlyfans.py", line 480, in process_metadata
    old_metadata_set = import_archive(archive_path)
  File "D:\OF Scraper\DigitalCriminal Onlyfans\helpers\main_helper.py", line 190, in import_archive
    metadata = ujson.load(outfile)
ValueError: Expected object or value
```

edit: forgot to mention, I'm running python 3.9 and all requirements are installed

**Comment by DIGITALCRIMINAL** [comment]
You can either delete the metadata folder of the model, or delete the metadata file that is broken

**Comment by globalgossamer** [comment]
Yep that worked, thanks
