### ISSUE TITLE
Error when downloading from a specific creator

### ISSUE THREAD

**Issue by zeldatp151** [DIGITALCRIMINAL/OnlyFans#545]
Whenever I try to use this for 1 specific creator, I always get this error. This is the only creator where I get the "Missing 600 Posts... Retrying..." and when I let it run to completion as you mentioned here: https://github.com/DIGITALCRIMINAL/OnlyFans/issues/528#issuecomment-731350450 I get the exception at the bottom. I am running your OnlyFans version 5.8 with python version 3.9, and I have verified that the requirements are all installed. 

This happens consistently with 1 specific creator

I have also tried to remove any identifying information such as user and creator names from this submission
```
./start_ofd.py 
Site: 0 = onlyfans | x = Exit
0
Auth (V1) Attempt 1/10
Welcome 
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping - 
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Names: Username = username  |  0 = All | 1 =  | 2 =  | 3 =  | 4 =  | 5 =  | 6 =  | 7 =  | 8 =  | 9 = 
8
Scrape Processing
Name: 
Scrape: a = Everything | b = Images | c = Videos | d = Audios | e = Texts
a
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Missing 600 Posts... Retrying...
Scrape Attempt: 2/100
Missing 600 Posts... Retrying...
Scrape Attempt: 3/100
Missing 600 Posts... Retrying...
. . . skip to save space
Scrape Attempt: 98/100
Missing 100 Posts... Retrying...
Scrape Attempt: 99/100
Missing 100 Posts... Retrying...
Scrape Attempt: 100/100
Missing 100 Posts... Retrying...
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
2020-11-24 06:02:28,262 ERROR errors string indices must be integers
Traceback (most recent call last):
  File "/media/place/OnlyFans/datascraper/main_datascraper.py", line 121, in start_datascraper
    x = main_helper.process_names(
  File "/media/place/OnlyFans/helpers/main_helper.py", line 463, in process_names
    result = module.start_datascraper(
  File "/media/place/OnlyFans/modules/onlyfans.py", line 137, in start_datascraper
    results = prepare_scraper(
  File "/media/place/OnlyFans/modules/onlyfans.py", line 597, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/place/OnlyFans/modules/onlyfans.py", line 790, in media_scraper
    if not media_api["media"] and "rawText" in media_api:
TypeError: string indices must be integers
```

**Comment by zeldatp151** [comment]
Idk if it is relevant, but this creator has over 36k posts.

**Comment by DIGITALCRIMINAL** [comment]
Can't do anything without the username

**Comment by vdb1975** [comment]
Same Issue.
It first scrap all the creator I followed not only the one I'm currently folliwing and then whatever is the creator I choose, it scrappes all the creator listed.
It worked perfectly with V5.6

**Comment by zeldatp151** [comment]
> Can't do anything without the username

invadernoodles

**Comment by DIGITALCRIMINAL** [comment]
Try with the latest commit

**Comment by zeldatp151** [comment]
I just downloaded the latest master and am trying it, it is saying Missing 700 Posts, but I will let it finish its 100 attempts and see if it actually downloads, this will probably take a few hours to complete, and I'll reply with the results.

**Comment by DIGITALCRIMINAL** [comment]
Are you using a proxy?

**Comment by zeldatp151** [comment]
no

**Comment by zeldatp151** [comment]
It did work now after going through the 100 missing posts attempts.
