### ISSUE TITLE
object is not iterable

### ISSUE THREAD

**Issue by AkgunFatih** [DIGITALCRIMINAL/OnlyFans#55]
```python
root@ip:~/OnlyFans# python3 StartDatascraper.py
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Welcome u****
Some OnlyFans' video links have SLOW download (Blame OF). I suggest importing the metadata json content to a Download Manager like IDM or JDownloader, or you could be waiting for 1HR+ for 300 videos to be finished.
Names: 0 = All | 1 = someonesusername
1
Invalid Choice
Traceback (most recent call last):
  File "StartDatascraper.py", line 92, in <module>
    session[0], username, site_name, app_token)
  File "/root/OnlyFans/modules/onlyfans.py", line 51, in start_datascraper
    for item in array:
TypeError: 'bool' object is not iterable
root@ip:~/OnlyFans# python3 --version
Python 3.6.8
root@ip:~/OnlyFans# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
root@ip:~/OnlyFans#
```

**Comment by AkgunFatih** [comment]
Same with python3.8

```python
root@ip:~/OnlyFans# python3 StartDatascraper.py
Auth (V1) Attempt 1/10
Welcome u****
Some OnlyFans' video links have SLOW download (Blame OF). I suggest importing the metadata json content to a Download Manager like IDM or JDownloader, or you could be waiting for 1HR+ for 300 videos to be finished.
Names: 0 = All | 1 = someonesusername
1
Invalid Choice
Traceback (most recent call last):
  File "StartDatascraper.py", line 91, in <module>
    result = x.start_datascraper(
  File "/root/OnlyFans/modules/onlyfans.py", line 52, in start_datascraper
    for item in array:
TypeError: 'bool' object is not iterable
root@ip:~/OnlyFans# python3 --version
Python 3.8.0
root@ip:~/OnlyFans# pip --version
pip 19.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
root@ip:~/OnlyFans#
```

**Comment by AkgunFatih** [comment]
hmm it works by changing 
```
"settings": {
        "auto_choice": "Everything",
```
to

```
"settings": {
        "auto_choice": "",
```

**Comment by DIGITALCRIMINAL** [comment]
Oh, everything is not a valid choice.
If you want everythinng, it should be the following: 
"auto_choice": "a"
