### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#564]
Hey, just updated to the latest commit and I'm not getting the following error??

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 114, in start_datascraper
    array = module.manage_subscriptions(
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 1027, in manage_subscriptions
    if item["usersCount"] > 2:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by DIGITALCRIMINAL** [comment]
Smh OnlyFans probably changed something in their API.

**Comment by DIGITALCRIMINAL** [comment]
You can try the latest commit then

**Comment by Kurosaki22** [comment]
Working for me again. Thanks for the quick fix :)

**Comment by Code4Win** [comment]
Thanks!
