### ISSUE TITLE
I can't start the application

### ISSUE THREAD

**Issue by McBurrito404** [DIGITALCRIMINAL/OnlyFans#573]
I can't start the application with: python start_ofd.py 
when performing the action, this happens: 
root@Cornfed:/home/cornfed/OnlyFans# python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/home/cornfed/OnlyFans/tests/main_test.py", line 7
    python_version = f"{version_info.major}.{version_info.minor}"
                                                                ^
SyntaxError: invalid syntax

**Comment by McBurrito404** [comment]
Hi :) y I can't access the tool, this is the error

root@Cornfed:/home/cornfed/OnlyFans# python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "/home/cornfed/OnlyFans/tests/main_test.py", line 7
    python_version = f"{version_info.major}.{version_info.minor}"
                                                                ^
SyntaxError: invalid syntax
