### ISSUE TITLE
Issue whilst downloading files

### ISSUE THREAD

**Issue by jamesp132** [DIGITALCRIMINAL/OnlyFans#579]
Scrape Attempt: 1/100
Found: Archived_posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Type: Messages
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
2020-12-07 22:41:59,068 ERROR errors Trailing data
Traceback (most recent call last):
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\datascraper\main_datascraper.py", line 125, in start_datascraper
    x = main_helper.process_names(
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\helpers\main_helper.py", line 464, in process_names
    result = module.start_datascraper(
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\modules\onlyfans.py", line 150, in start_datascraper
    results = prepare_scraper(
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\modules\onlyfans.py", line 631, in prepare_scraper
    new_metadata_object = process_metadata(
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\modules\onlyfans.py", line 506, in process_metadata
    old_metadata_set = import_archive(archive_path)
  File "\\MYCLOUDPR4100\Personal\OnlyFans-master\helpers\main_helper.py", line 190, in import_archive
    metadata = ujson.load(outfile)
ValueError: Trailing data

I receive this error mor and more recently although I haven't made any changes to the settings file any ideas? 

It's been working flawlessly up until about a week ago where this error was appearing.

**Comment by jamesp132** [comment]
I have seen on closed tickets deleting the metadata might resolve this? 

Where can I find the metadata location?

**Comment by DIGITALCRIMINAL** [comment]
Delete the metadata file that's related to the user and is crashing.
