### ISSUE TITLE
getting "TypeError: expected str, bytes or os.PathLike object, not NoneType" when doing python start_ofd.py

### ISSUE THREAD

**Issue by frgmntdmmrs** [DIGITALCRIMINAL/OnlyFans#588]
after running `python start_ofd.py`, i get this

Here's my error message 

```
Traceback (most recent call last):
  File "C:\OnlyFans\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "C:\OnlyFans\tests\main_test.py", line 21, in check_config
    json_config, json_config2 = main_helper.get_config(path)
  File "C:\OnlyFans\helpers\main_helper.py", line 378, in get_config
    json_config, string = make_settings.fix(json_config)
  File "C:\OnlyFans\classes\make_settings.py", line 58, in fix
    c = x.check_unique()
  File "C:\OnlyFans\classes\prepare_metadata.py", line 199, in check_unique
    value = os.path.normpath(value)
  File "C:\Users\myPC\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
python version is 

```
$ python --version
Python 3.9.0
```

my `config.json` is located in `.settings`

this is what's in it

```
{
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "multithreading": true,
    "exit_on_completion": true,
    "infinite_loop": true,
    "loop_timeout": "0",
    "socks5_proxy": "",
    "cert": "",
    "max_threads": "-1",
    "global_user_agent": ""
  },
  "supported": {
    "onlyfans": {
      "auth": {
        "username": "REDACTED",
        "auth_id": "REDACTED",
        "auth_hash": "",
        "auth_uniq_": "",
        "sess": "REDACTED",
        "fp": "REDACTED",
        "app_token": "REDACTED",
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x Safari/537.36",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "a",
        "auto_scrape_names": true,
        "auto_scrape_apis": true,
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    },
    "patreon": {
      "auth": {
        "cf_clearance": "",
        "session_id": "",
        "user_agent": "",
        "support_2fa": true
      },
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "{site_name}",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    },
    "starsavn": {
      "auth": {
        "username": "",
        "sess": "",
        "user_agent": ""
      },
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "{site_name}",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "blacklist_name": ""
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
      }
    },
    "fourchan": {
      "auth": {},
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "download_path": "{site_name}",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "boards": [],
        "ignored_keywords": []
      }
    },
    "bbwchan": {
      "auth": {},
      "settings": {
        "auto_choice": "",
        "auto_scrape_names": false,
        "download_path": "{site_name}",
        "file_name_format": "{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "boards": [],
        "ignored_keywords": []
      }
    }
  }
}
```

**Comment by DIGITALCRIMINAL** [comment]
Is this your first time running the script?

**Comment by frgmntdmmrs** [comment]
No. The last version I used was from here : https://github.com/DIGITALCRIMINAL/OnlyFans/commit/43603d827a6204e5eb8ec07da4dda099afc8cea6

I was getting an error today when trying to use the script and noticed I was getting  

```
.C:\Users\myPC\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py:332: MarkupResemblesLocatorWarning: "....." looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
```

and realized the last time my archives updated itself was in December 1 2020, so I decided to do a git fetch. I updated my python to 3.9. Was getting the original error. Did a git clone on a clean dir - same issue.

**Comment by frgmntdmmrs** [comment]
I'm not familiar with how to properly debug in Python, but maybe this might help where I tried to trace by using `print()` statements to check what values were stored

```
line 32 (make_setting.py, reformats): {'date_format': '%d-%m-%Y', 'metadata_directory_format': '{site_name}/{username}/Metadata', 'filename_format': '{file_name}.{ext}'}
line 36 (make_setting.py, reformats): {'metadata_directory_format': '{site_name}/{username}/Metadata', 'filename_format': '{file_name}.{ext}'}
line 47 (make_setting.py, x): <classes.prepare_metadata.format_types object at 0x00000240078AFD90>
line 182 (prepare_metadata.py, key): file_directory_format  value: None
```

**Comment by DIGITALCRIMINAL** [comment]
Delete the config
