### ISSUE TITLE
ERROR errors 'create_auth' object has no attribute 'username'

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINAL/OnlyFans#595]
Hi there,
I am receiving the following error since your latest changes.
I also created a new config but im getting the same error.

2020-12-12 19:09:41,224 ERROR errors 'create_auth' object has no attribute 'username'
Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 98, in start_datascraper
    api = OnlyFans.start(
  File "G:\Photo\_OF_Scraper\OnlyFans\apis\onlyfans\onlyfans.py", line 460, in __init__
    self.auth = create_auth(init=True)
  File "G:\Photo\_OF_Scraper\OnlyFans\apis\onlyfans\onlyfans.py", line 190, in __init__
    if not self.username:
AttributeError: 'create_auth' object has no attribute 'username'

**Comment by DIGITALCRIMINAL** [comment]
Download the latest commit

**Comment by DIGITALCRIMINAL** [comment]
Download latest commit

**Comment by Kurosaki22** [comment]
Fixed and working again.  Thanks :)
