### ISSUE TITLE
File Rename error 

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/OnlyFans#602]
On CMD the tongue out emoji shows as a question mark symbol 
![image](https://user-images.githubusercontent.com/20603861/102408454-98355b80-3fbb-11eb-886d-4403ffc85675.png)

```
2020-12-16 16:20:15,085 ERROR errors [Errno 22] Invalid argument: 'I:\\OnlyFans-6.0\\.sites\\OnlyFans\\zoeyssweettea\\Messages\\Images\\[2020-09-05][How’d you wake up ?😛](112448724).jpg'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'I:\\OnlyFans-6.0\\.sites\\OnlyFans\\zoeyssweettea\\Messages\\Images\\[2020-09-05] (768x1024_1af987704cd81f5810849099439090d9).jpg' -> 'I:\\OnlyFans-6.0\\.sites\\OnlyFans\\zoeyssweettea\\Messages\\Images\\[2020-09-05][How’d you wake up ?😛](112448724).jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\OnlyFans-6.0\datascraper\main_datascraper.py", line 122, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "I:\OnlyFans-6.0\modules\onlyfans.py", line 345, in paid_content_scraper
    new_metadata_object = process_metadata(
  File "I:\OnlyFans-6.0\modules\onlyfans.py", line 533, in process_metadata
    new_metadata_object = ofrenamer.start(
  File "I:\OnlyFans-6.0\extras\OFRenamer\start.py", line 138, in start
    fixed2 = fix_metadata(
  File "I:\OnlyFans-6.0\extras\OFRenamer\start.py", line 90, in fix_metadata
    old_filepath, new_filepath = update(old_filepath, new_filepath)
  File "I:\OnlyFans-6.0\extras\OFRenamer\start.py", line 86, in update
    shutil.move(old_filepath, new_filepath)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'I:\\OnlyFans-6.0\\.sites\\OnlyFans\\zoeyssweettea\\Messages\\Images\\[2020-09-05][How’d you wake up ?😛](112448724).jpg'
```

**Comment by TSlyCooper** [comment]
I have the exact same issue. I suspect it has to do with the ? and emoji, but I need the text in the file name for what I'm working on.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by bobsage123** [comment]
In the latest commit there's nowhere in the config to put my user-agent, sess, auth-id, etc. After I hit enter after creating the config I get the below. Pasting in my user agent or hitting enter closes the CMD.

![image](https://user-images.githubusercontent.com/20603861/102546278-64bf0380-4085-11eb-9813-172b5506fd21.png)

**Comment by DIGITALCRIMINAL** [comment]
It's in the .profiles folder.

**Comment by bobsage123** [comment]
Got it.

I eventually ran into an error on another file.

![image](https://user-images.githubusercontent.com/20603861/102580147-0d905180-40cc-11eb-9cb1-542c97ddff10.png)


```
Renaming files.
2020-12-18 00:55:41,245 ERROR errors [Errno 22] Invalid argument: 'I:\\OnlyFans-6.1\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2019-04-04][Let\'s do, "we shouldn\'t be doing this" things  🐱💦](21320024).jpg'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'I:\\OnlyFans-6.1\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2019-04-04] (66128435-IMG-20180811-110538).jpg' -> 'I:\\OnlyFans-6.1\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2019-04-04][Let\'s do, "we shouldn\'t be doing this" things 🐱💦](21320024).jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\OnlyFans-6.1\datascraper\main_datascraper.py", line 150, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "I:\OnlyFans-6.1\modules\onlyfans.py", line 346, in paid_content_scraper
    new_metadata_object = process_metadata(
  File "I:\OnlyFans-6.1\modules\onlyfans.py", line 536, in process_metadata
    new_metadata_object = ofrenamer.start(
  File "I:\OnlyFans-6.1\extras\OFRenamer\start.py", line 138, in start
    fixed2 = fix_metadata(
  File "I:\OnlyFans-6.1\extras\OFRenamer\start.py", line 90, in fix_metadata
    old_filepath, new_filepath = update(old_filepath, new_filepath)
  File "I:\OnlyFans-6.1\extras\OFRenamer\start.py", line 86, in update
    shutil.move(old_filepath, new_filepath)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'I:\\OnlyFans-6.1\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2019-04-04][Let\'s do, "we shouldn\'t be doing this" things 🐱💦](21320024).jpg'
```

**Comment by DIGITALCRIMINAL** [comment]
What's your filename format

**Comment by DIGITALCRIMINAL** [comment]
You can try the latest commit.

**Comment by TSlyCooper** [comment]
I'm getting the same error on the latest commit. Has anyone had better luck?

**Comment by bobsage123** [comment]
I got stuck on a different file from kimmygranger on newest commit.

```
2020-12-18 15:24:04,216 ERROR errors [Errno 22] Invalid argument: 'I:\\OnlyFans-6.2\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2018-11-29][Good morning : ) about to jump in the car to go get Starbucks : ) are you buying  Shoot me a tip](21234460).jpg'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'I:\\OnlyFans-6.2\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2018-11-29] (37531924-IMG-20181128-WA0028).jpg' -> 'I:\\OnlyFans-6.2\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2018-11-29][Good morning : ) about to jump in the car to go get Starbucks : ) are you buying  Shoot me a tip](21234460).jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\OnlyFans-6.2\datascraper\main_datascraper.py", line 150, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "I:\OnlyFans-6.2\modules\onlyfans.py", line 346, in paid_content_scraper
    new_metadata_object = process_metadata(
  File "I:\OnlyFans-6.2\modules\onlyfans.py", line 536, in process_metadata
    new_metadata_object = ofrenamer.start(
  File "I:\OnlyFans-6.2\extras\OFRenamer\start.py", line 138, in start
    fixed2 = fix_metadata(
  File "I:\OnlyFans-6.2\extras\OFRenamer\start.py", line 90, in fix_metadata
    old_filepath, new_filepath = update(old_filepath, new_filepath)
  File "I:\OnlyFans-6.2\extras\OFRenamer\start.py", line 86, in update
    shutil.move(old_filepath, new_filepath)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'I:\\OnlyFans-6.2\\.sites\\OnlyFans\\kimmygrangerxxx\\Messages\\Images\\[2018-11-29][Good morning : ) about to jump in the car to go get Starbucks : ) are you buying  Shoot me a tip](21234460).jpg'
```

**Comment by DIGITALCRIMINAL** [comment]
You can try the latest.

**Comment by bobsage123** [comment]
Got past the last error but ran into another - Reason I asked if I could temp skip errors, is so I can collect all the scenarios where I run into them and post them at once.


2020-12-18 17:39:30,879 ERROR errors [Errno 22] Invalid argument: 'I:\\OnlyFans-6.3\\.sites\\OnlyFans\\daphnedare\\Posts\\Images\\[2020-12-03][I’m sorry I haven’t posted in awhile<3 I have stuff coming tomorrow  )](178153510).jpg'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'I:\\OnlyFans-6.3\\.sites\\OnlyFans\\daphnedare\\Posts\\Images\\[2020-12-03] (1172x657_f1daf66d3e4eb53b8637b67e567eb448).jpg' -> 'I:\\OnlyFans-6.3\\.sites\\OnlyFans\\daphnedare\\Posts\\Images\\[2020-12-03][I’m sorry I haven’t posted in awhile<3 I have stuff coming tomorrow  )](178153510).jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\OnlyFans-6.3\datascraper\main_datascraper.py", line 119, in start_datascraper
    x = main_helper.process_names(
  File "I:\OnlyFans-6.3\helpers\main_helper.py", line 506, in process_names
    result = module.start_datascraper(
  File "I:\OnlyFans-6.3\modules\onlyfans.py", line 148, in start_datascraper
    results = prepare_scraper(
  File "I:\OnlyFans-6.3\modules\onlyfans.py", line 647, in prepare_scraper
    new_metadata_object = process_metadata(
  File "I:\OnlyFans-6.3\modules\onlyfans.py", line 532, in process_metadata
    new_metadata_object = ofrenamer.start(
  File "I:\OnlyFans-6.3\extras\OFRenamer\start.py", line 138, in start
    fixed2 = fix_metadata(
  File "I:\OnlyFans-6.3\extras\OFRenamer\start.py", line 90, in fix_metadata
    old_filepath, new_filepath = update(old_filepath, new_filepath)
  File "I:\OnlyFans-6.3\extras\OFRenamer\start.py", line 86, in update
    shutil.move(old_filepath, new_filepath)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'I:\\OnlyFans-6.3\\.sites\\OnlyFans\\daphnedare\\Posts\\Images\\[2020-12-03][I’m sorry I haven’t posted in awhile<3 I have stuff coming tomorrow  )](178153510).jpg'

**Comment by bobsage123** [comment]
@DIGITALCRIMINAL please let me know when to test again. Saw some recent commits so wasn't sure if they were related to this issue and should test.

**Comment by DIGITALCRIMINAL** [comment]
Just take out text from the filename format

**Comment by bobsage123** [comment]
> Just take out text from the filename format

I know that would work but I thought we were on a role fixing all instances where text ran into issues and could get it working once and for all. Would make a lot of people happy 😁

**Comment by bobsage123** [comment]
I just dled 6.1 release and it got past my error files. But it looks like it didn't DL those files it couldn't rename with text at all. Perhaps a quick fix so it does dl these files is to this is to add a "secondary" naming format without "text" for files that it can't rename?

**Comment by TSlyCooper** [comment]
> Just take out text from the filename format

I really hope this doesn't end up being the fix. For lots of OF people, the text of the clip is part of the content itself. Sometimes the action on video is only hot because it's contextualized. Thank you for the good work you do though. 

Maybe text could just remove emojis ? No idea.

**Comment by DIGITALCRIMINAL** [comment]
> > Just take out text from the filename format
> 
> I really hope this doesn't end up being the fix. For lots of OF people, the text of the clip is part of the content itself. Sometimes the action on video is only hot because it's contextualized. Thank you for the good work you do though.
> 
This is the fix for now until I decide to have another attempt at this. 
I'm not even subscribed to the models who have cause text to break so I couldn't fix it if I wanted to.
If you want to know the context of the videos just open metadata and read it or create a script that fixes the text format. or just create some application that shows videos with the context.
> Maybe text could just remove emojis ? No idea.
>
Removing emojis is technically infeasible. You'd have to download the entire database of emojis every run, and I don't want to put that into the script.

The warning not to use text is there for a reason. Just take it out if it doesn't work.

**Comment by bobsage123** [comment]
Can I get clarification that if it runs into an error now it totally skips the file and doesn't download it at all? That seems to be the behavior in 6.1.

**Comment by DIGITALCRIMINAL** [comment]
> Can I get clarification that if it runs into an error now it totally skips the file and doesn't download it at all? That seems to be the behavior in 6.1.

I didn't change anything specific to the text

**Comment by bobsage123** [comment]
> > Can I get clarification that if it runs into an error now it totally skips the file and doesn't download it at all? That seems to be the behavior in 6.1.
> 
> I didn't change anything specific to the text

Odd, if it encounters an error for me now it totally skips the file. Could this be related? 
![image](https://user-images.githubusercontent.com/20603861/102936924-1475e600-4477-11eb-9cfd-d312bb9e128c.png)

**Comment by DIGITALCRIMINAL** [comment]
> > > Can I get clarification that if it runs into an error now it totally skips the file and doesn't download it at all? That seems to be the behavior in 6.1.
> > 
> > 
> > I didn't change anything specific to the text
> 
> Odd, if it encounters an error for me now it totally skips the file. Could this be related?
> ![image](https://user-images.githubusercontent.com/20603861/102936924-1475e600-4477-11eb-9cfd-d312bb9e128c.png)

That's specifically for handling errors from the API. OFRenamer handles all filenaming
