### ISSUE TITLE
Unable to auth under new profile

### ISSUE THREAD

**Issue by valdearg** [DIGITALCRIMINAL/OnlyFans#603]
Running into some issues with the new profile system stuff. Tried changing the profile dir to be my username, e.g. from .profiles\onlyfans\default to .profiles\onlyfans\valdearg = the username entry in the auth.json, but still didn't auth.

```
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
2020-12-16 22:20:52,098 ERROR errors 'NoneType' object has no attribute 'profile_directory'
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 137, in start_datascraper
    api.auth.profile_directory, "auth.json")
AttributeError: 'NoneType' object has no attribute 'profile_directory'
```

**Comment by captainjelou** [comment]
same

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by DoublePipe** [comment]
I previously got the same error mentioned above. With the latest commit, I'm getting this instead: 

```
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
2020-12-17 11:26:44,718 ERROR errors 'start' object has no attribute 'auth_details'
Traceback (most recent call last):
  File "/Users/foo/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 135, in start_datascraper
    api.auth_details.active = False
AttributeError: 'start' object has no attribute 'auth_details'
```

**Comment by DIGITALCRIMINAL** [comment]
Fixed

**Comment by valdearg** [comment]
Error has gone in the latest version but I'm not getting authed. 

```
Session IP: <IP>

Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Now exiting.
```

**Comment by DIGITALCRIMINAL** [comment]
Fix your credentials
