### ISSUE TITLE
issues starting with latest version with/without settings

### ISSUE THREAD

**Issue by oferchen** [DIGITALCRIMINAL/OnlyFans#605]
I'm seeing some issues starting with latest version with/without settings

$ ./OnlyFans/start_ofd.py
Site: 0 = onlyfans | x = Exit
0
Session IP: xx.xx.xxx.xx

Names: Username = username  |  0 = All | 1 = default
0
2020-12-17 14:19:17,617 ERROR errors 'auto_choice'
Traceback (most recent call last):
  File "./OnlyFans/datascraper/main_datascraper.py", line 129, in start_datascraper
    module.assign_vars(api.auth.auth_details, json_config,
  File "./OnlyFans/modules/onlyfans.py", line 57, in assign_vars
    auto_choice = json_settings["auto_choice"]
KeyError: 'auto_choice'

$ ./OnlyFans/start_ofd.py
Traceback (most recent call last):
  File "./OnlyFans/start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "./OnlyFans/tests/main_test.py", line 24, in check_config
    json_config, json_config2 = main_helper.get_config(path)
  File "./OnlyFans/helpers/main_helper.py", line 376, in get_config
    json_config = json.loads(json.dumps(make_settings.config(
  File "./OnlyFans/classes/make_settings.py", line 300, in __init__
    self.settings = Settings(**settings)
TypeError: __init__() got an unexpected keyword argument 'auto_profile_choice'

**Comment by ChillyP** [comment]
Seeing the same issue.

**Comment by DIGITALCRIMINAL** [comment]
Thanks, fixed
