### ISSUE TITLE
ERROR errors Unmatched ''"' when when decoding 'string'

### ISSUE THREAD

**Issue by oferchen** [DIGITALCRIMINAL/OnlyFans#619]
with latest snapshot I encountered the following while scraping.

Merging new metadata with legacy metadata.
2020-12-22 10:34:23,541 ERROR errors Unmatched ''"' when when decoding 'string'
Traceback (most recent call last):
  File "/OnlyFans/start_ofd.py", line 46, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/OnlyFans/datascraper/main_datascraper.py", line 81, in start_datascraper
    if jobs["scrape_names"]:
  File "/OnlyFans/helpers/main_helper.py", line 506, in process_names
    result = module.start_datascraper(
  File "/OnlyFans/modules/onlyfans.py", line 146, in start_datascraper
    results = prepare_scraper(
  File "/OnlyFans/modules/onlyfans.py", line 645, in prepare_scraper
    new_metadata_object = process_metadata(
  File "/OnlyFans/modules/onlyfans.py", line 516, in process_metadata
    old_metadata_set = import_archive(archive_path)
  File "/OnlyFans/helpers/main_helper.py", line 187, in import_archive
    metadata = ujson.load(outfile)
ValueError: Unmatched ''"' when when decoding 'string'

**Comment by DIGITALCRIMINAL** [comment]
You can either delete the old metadata or send it to me via email so I can try to fix it.

If you do decide to delete the old metadata you'll end up losing support for old files.

**Comment by oferchen** [comment]
deleted the old metadata, seems to be ok.
thanks
