### ISSUE TITLE
InvalidProxyURL error

### ISSUE THREAD

**Issue by memailtest2** [DIGITALCRIMINAL/OnlyFans#620]
First off amazing work on this and many many thanks.  Been using this off and on for a bit but when I updated and tried today I ran into this error;

````
$ python start_ofd.py                                                            
Site: 0 = onlyfans \| x = Exit                                                    
0                                                                                
2020-12-22 06:47:04,950 ERROR errors Please check proxy URL. It is malformed and  could be missing the host.
Traceback (most recent call last):
File "D:\PROC\DigitalCriminal\OnlyFans\apis\api_helper.py", line 81, in json_request
r = session.request(
File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python39\lib\site-packages\ requests\sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python39\lib\site-packages\ requests\sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python39\lib\site-packages\ requests\adapters.py", line 412, in send
conn = self.get_connection(request.url, proxies)
File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python39\lib\site-packages\ requests\adapters.py", line 307, in get_connection
raise InvalidProxyURL("Please check proxy URL. It is malformed"
requests.exceptions.InvalidProxyURL: Please check proxy URL. It is malformed and  could be missing the host.

````

It repeats like that for a while. I checked that I'm up to date w/the script and python, that the python requirements are installed, and that I don't have a proxy set at the system level.

![pyerr2](https://user-images.githubusercontent.com/76483297/102897713-b1a82e80-4425-11eb-874f-5a6bc3de8794.jpg)

![pyerr1](https://user-images.githubusercontent.com/76483297/102897732-b79e0f80-4425-11eb-89ba-ce74dee4a99b.jpg)

Any idea what it is I might be screwing up on here?

**Comment by DIGITALCRIMINAL** [comment]
Remove the proxies in the config

**Comment by memailtest2** [comment]
Sometimes it's a wonder I can get dressed in the morning.

Fixed, thank you very much.
