### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by lemonpillow** [DIGITALCRIMINAL/OnlyFans#628]
Execute the script with Python 3.9
Press enter to continue
Traceback (most recent call last):
  File "start_ofd.py", line 8, in <module>
    main_test.check_config()
  File "C:\Users\X\Desktop\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 20, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\X\Desktop\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 6, in <module>
    from classes.prepare_metadata import format_variables, prepare_reformat
  File "C:\Users\X\Desktop\OnlyFans-master\OnlyFans-master\classes\prepare_metadata.py", line 1, in <module>
    from apis.onlyfans.onlyfans import media_types
  File "C:\Users\X\Desktop\OnlyFans-master\OnlyFans-master\apis\onlyfans\onlyfans.py", line 458, in <module>
    class start():
  File "C:\Users\X\Desktop\OnlyFans-master\OnlyFans-master\apis\onlyfans\onlyfans.py", line 600, in start
    def get_subscriptions(self, resume=None, refresh=True, identifiers: list = [], extra_info=True, limit=20, offset=0) -> list[Union[create_subscription, None]]:
TypeError: 'type' object is not subscriptable

i get this error when i try to open start_ofd

all requirements were installed successful and i cannot seem te get rid of this problem

**Comment by rursache** [comment]
having the same issue on windows 10, python 3.9 or 3.8 installed from the store
