### ISSUE TITLE
New install pronlems.

### ISSUE THREAD

**Issue by RonnieBlaze** [DIGITALCRIMINAL/OnlyFans#632]
I did a brand new install to a new folder did the requirements install got that all worked out. 
I do not see a .settings or .profiles folder/file I have show hidden files/folders turned on.

so i thought maybe it would create them on first run of the script, So i tread that and this is what it does. 

F:\Users\xxx\Downloads\OnlyFans-6.1.1>python start_ofd.py
Traceback (most recent call last):
  File "start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "F:\Users\xxx\Downloads\OnlyFans-6.1.1\tests\main_test.py", line 1, in <module>
    from apis.onlyfans.onlyfans import auth_details
  File "F:\Users\xxx\Downloads\OnlyFans-6.1.1\apis\onlyfans\onlyfans.py", line 457, in <module>
    class start():
  File "F:\Users\xxx\Downloads\OnlyFans-6.1.1\apis\onlyfans\onlyfans.py", line 599, in start
    def get_subscriptions(self, resume=None, refresh=True, identifiers: list = [], extra_info=True, limit=20, offset=0) -> list[Union[create_subscription, None]]:
TypeError: 'type' object is not subscriptable

**Comment by DIGITALCRIMINAL** [comment]
Read the FAQ
