### ISSUE TITLE
Not a directory

### ISSUE THREAD

**Issue by goldendeercardinal** [DIGITALCRIMINAL/OnlyFans#642]
Hi

I get this error after ip authentication:

2020-12-29 23:08:06,266 ERROR errors [Errno 20] Not a directory: '/Users/$user/Downloads/OnlyFans-master/.profiles/OnlyFans/.DS_Store/auth.json'
Traceback (most recent call last):
  File "/Users/$user/Downloads/OnlyFans-master/start_ofd.py", line 46, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/$user/Downloads/OnlyFans-master/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/Users/$user/Downloads/OnlyFans-master/helpers/main_helper.py", line 496, in process_profiles
    export_json(
  File "/Users/$user/Downloads/OnlyFans-master/helpers/main_helper.py", line 555, in export_json
    with open(path, 'w', encoding=encoding) as outfile:
NotADirectoryError: [Errno 20] Not a directory: '/Users/$user/Downloads/OnlyFans-master/.profiles/OnlyFans/.DS_Store/auth.json'

**Comment by nowtp** [comment]
Not the only one with the same error, tried both locally and in Docker on the macOS and pulls the same error in both instances.

Any points on fixing this one would be handy

**Comment by 97bats** [comment]
I too am having this issue -

`2021-01-03 19:52:15,619 ERROR errors [Errno 20] Not a directory: '/usr/src/app/.profiles/OnlyFans/.DS_Store/auth.json'
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 46, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/usr/src/app/helpers/main_helper.py", line 496, in process_profiles
    export_json(
  File "/usr/src/app/helpers/main_helper.py", line 555, in export_json
    with open(path, 'w', encoding=encoding) as outfile:
NotADirectoryError: [Errno 20] Not a directory: '/usr/src/app/.profiles/OnlyFans/.DS_Store/auth.json'
`

**Comment by mikebatnz** [comment]
You need to delete the .DS_Store file created by macOS

Eg.
rm /usr/src/app/.profiles/OnlyFans/.DS_Store

**Comment by nowtp** [comment]
Hmm, strange on that one, so the rm function doesn't work for me to delete the .DS_Store file, but as always your milage may very.

Whats does work for me from thinking about it would be running find and delete instead in the sites profile folder. so the "./profiles/Onlyfans" for example, where the Default folder would be.

`find . -name ".DS_Store" -delete`

This then seems to work though, not sure after a few reboots, but for now seems to function after closing the terminal window a few times and re-running a couple times.

Anyone understand why this occures? Would be good to understand what causes this.

**Comment by 97bats** [comment]
OK, this worked. I changed to the root OnlyFans directory that stores all the files (which I am just running within documents). I then ran (there was no feedback during this process): -

`find . -name ".DS_Store" -delete`

And then ran the docker build (I've installed Docker locally), as described here: -

`docker build -t only-fans . && docker run -it --rm --name onlyfans -v ${PWD}/.settings:/usr/src/app/.settings -v ${PWD}/.profiles:/usr/src/app/.profiles -v ${PWD}/.sites:/usr/src/app/.sites only-fan`
