### ISSUE TITLE
bool object is not iterable

### ISSUE THREAD

**Issue by ModernAesthetics** [DIGITALCRIMINAL/OnlyFans#66]
Invalid Choice
Traceback (most recent call last):
  File "C:\PyScripts\OnlyFans\StartDatascraper.py", line 97, in <module>
    result = x.start_datascraper(
  File "C:\PyScripts\OnlyFans\modules\onlyfans.py", line 55, in start_datascraper
    for item in array:
TypeError: 'bool' object is not iterable

**Comment by DIGITALCRIMINAL** [comment]
What's the Python Version?

**Comment by DIGITALCRIMINAL** [comment]
I see the error. You didn't input the right format for a choice.
