### ISSUE TITLE
 'process_json_metadata' is not defined

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINAL/OnlyFans#666]
Hi there,

Im receiving the following error from the latest commit:

Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 82, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 343, in paid_content_scraper
    new_metadata_object, delete_metadatas = process_json_metadata(
NameError: name 'process_json_metadata' is not defined

**Comment by DIGITALCRIMINAL** [comment]
Set scrape_paid_content to false for now

**Comment by Kurosaki22** [comment]
When I set it to false it will continue for a short time until this error shows up:

Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 85, in start_datascraper
    x = main_helper.process_names(
  File "G:\Photo\_OF_Scraper\OnlyFans\helpers\main_helper.py", line 519, in process_names
    result = module.start_datascraper(
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 148, in start_datascraper
    results = prepare_scraper(
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 665, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\oehy2\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\oehy2\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\oehy2\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\oehy2\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 892, in media_scraper
    new_post["text"] = media_api["rawText"]
KeyError: 'rawText'

**Comment by DIGITALCRIMINAL** [comment]
Yee, I've fixed that on my end but I haven't pushed the commit yet

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed in the latest commit. You can turn it back on.

**Comment by Kurosaki22** [comment]
Receiving this error now:

Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 82, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 343, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 903, in media_scraper
    if not media_api["canPurchase"]:
KeyError: 'canPurchase'

**Comment by DIGITALCRIMINAL** [comment]
Which model was it scraping and do you know if it was a post or an image?

**Comment by Kurosaki22** [comment]
not sure if the lines directly above it are the right one

Scraping - jessicanigri | 10 / 24
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 82, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 343, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 903, in media_scraper
    if not media_api["canPurchase"]:
KeyError: 'canPurchase'

**Comment by DIGITALCRIMINAL** [comment]
Have you bought any of her paid posts?

**Comment by DIGITALCRIMINAL** [comment]
Nevermind, I've got the error

**Comment by Kurosaki22** [comment]
Ok had to check.
Was pretty long ago that i bought one of her posts

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit

**Comment by Kurosaki22** [comment]
Sorry had dinner.
Working again.  Thanks :)

**Comment by DIGITALCRIMINAL** [comment]
Just noticed the issue was #666 lul
