### ISSUE TITLE
ValueError: time data '' does not match format '%d-%m-%Y %H:%M:%S'

### ISSUE THREAD

**Issue by hammerheaddf** [DIGITALCRIMINAL/OnlyFans#668]
Running latest release as of now on Raspbian Linux and Python 3.9.
Creator _lovegiavanna_ fails with the following traceback:
```
Processing metadata.
Merging new metadata with legacy metadata.
Merging new metadata with old metadata.
Finished processing metadata.
Traceback (most recent call last):
  File "/home/felipe/OnlyFans/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/home/felipe/OnlyFans/datascraper/main_datascraper.py", line 85, in start_datascraper
    x = main_helper.process_names(
  File "/home/felipe/OnlyFans/helpers/main_helper.py", line 520, in process_names
    result = module.start_datascraper(
  File "/home/felipe/OnlyFans/modules/onlyfans.py", line 148, in start_datascraper
    results = prepare_scraper(
  File "/home/felipe/OnlyFans/modules/onlyfans.py", line 681, in prepare_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "/home/felipe/OnlyFans/modules/onlyfans.py", line 556, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "/home/felipe/OnlyFans/helpers/main_helper.py", line 149, in make_metadata
    date_object = datetime.strptime(
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%d-%m-%Y %H:%M:%S'
```

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit.

**Comment by DIGITALCRIMINAL** [comment]
Lmao nvm, I haven't pushed it yet...

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit.
