### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characte

### ISSUE THREAD

**Issue by dharbigt** [DIGITALCRIMINAL/OnlyFans#67]
I saw something similar to this before but this looks slightly different. This is the latest version of the master branch.

```Traceback (most recent call last):
  File "./StartDatascraper.py", line 61, in <module>
    session = x.create_session(
  File "/Users/ajax/Sites/OnlyFans/modules/onlyfans.py", line 276, in create_session
    session.head("https://onlyfans.com")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1271, in _send_request
    self.putheader(hdr, value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1203, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 30: ordinal not in range(256)```

**Comment by DIGITALCRIMINAL** [comment]
Make sure there's no special characters in their cookies

**Comment by dharbigt** [comment]
Thanks, the user agent was not correct, however I was also unable to continue without manually inserting the sess cookie.

**Comment by dharbigt** [comment]
It worked, thank you again. Not sure if that is a new change for "sess" but I did not see it in the config for OF.

**Comment by DIGITALCRIMINAL** [comment]
@dharbigt np.
What error were you seeing before you added the sess?

**Comment by dharbigt** [comment]
The encoding issue was due to the user agent string. Once I got beyond that it just looped. It would go through all ten attempts and then loop back again. It did not say "Access denied" or whatever message it gives when the auth tokens are incorrect.

**Comment by DIGITALCRIMINAL** [comment]
Ahh, it might have been because you have 2AuthFactor on your account
