### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by headphonia** [DIGITALCRIMINAL/OnlyFans#675]
I'm getting the following error with the latest commit.

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/OF Scrapper/.sites/OnlyFans/filipinaxo/Archived/Posts/Free/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg' -> '/OF Scrapper/.sites/OnlyFans/filipinaxo/Posts/Paid/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/OF Scrapper/extras/OFRenamer/start.py", line 81, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/OF Scrapper/.sites/OnlyFans/filipinaxo/Posts/Paid/Images/1240x1654_ab343e8fe8a6198bc4710b6e02522259.jpg'

**Comment by Gamma-Velorum** [comment]
I can reproduce

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OnlyFans-master\extras\OFRenamer\start.py", line 81, in fix_directories
    moved = shutil.move(old_filepath, new_filepath)
  File "C:\Users\iwoul\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "C:\Users\iwoul\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\iwoul\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\OnlyFans-master\\.sites\\OnlyFans\\duchamprivate\\Messages\\Paid\\Images\\1836x2448_3712cb1311298b270fce01100e96a60e.jpg'

Traceback (most recent call last):
  File "C:\Users\iwoul\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\OnlyFans-master\\.sites\\OnlyFans\\duchamprivate\\Posts\\Free\\Images\\1836x2448_3712cb1311298b270fce01100e96a60e.jpg' -> 'F:\\OnlyFans-master\\.sites\\OnlyFans\\duchamprivate\\Messages\\Paid\\Images\\1836x2448_3712cb1311298b270fce01100e96a60e.jpg'

```

**Comment by DIGITALCRIMINAL** [comment]
Try latest

**Comment by headphonia** [comment]
I get this error now...

> Traceback (most recent call last):
  File "/OF Scrapper/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/OF Scrapper/datascraper/main_datascraper.py", line 82, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "/OF Scrapper/modules/onlyfans.py", line 352, in paid_content_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "/OF Scrapper/modules/onlyfans.py", line 556, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "/OF Scrapper/helpers/main_helper.py", line 209, in make_metadata
    x = legacy_database_fixer(database_path, database, database_name)
  File "/OF Scrapper/helpers/main_helper.py", line 162, in legacy_database_fixer
    post_db = result.all()
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: messages
[SQL: SELECT messages.id AS messages_id, messages.text AS messages_text, messages.price AS messages_price, messages.paid AS messages_paid, messages.created_at AS messages_created_at 
FROM messages]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by DIGITALCRIMINAL** [comment]
> I get this error now...
> 
> > Traceback (most recent call last):
> > File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> > self.dialect.do_execute(
> > File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
> > cursor.execute(statement, parameters)
> > sqlite3.OperationalError: no such table: messages
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "/OF Scrapper/start_ofd.py", line 40, in
> main_datascraper.start_datascraper(json_config, site_name_lower)
> File "/OF Scrapper/datascraper/main_datascraper.py", line 82, in start_datascraper
> paid_content = module.paid_content_scraper(apis)
> File "/OF Scrapper/modules/onlyfans.py", line 352, in paid_content_scraper
> w = process_metadata(metadata_path, new_metadata,
> File "/OF Scrapper/modules/onlyfans.py", line 556, in process_metadata
> Session, api_type, folder = main_helper.make_metadata(
> File "/OF Scrapper/helpers/main_helper.py", line 209, in make_metadata
> x = legacy_database_fixer(database_path, database, database_name)
> File "/OF Scrapper/helpers/main_helper.py", line 162, in legacy_database_fixer
> post_db = result.all()
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3373, in all
> return list(self)
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in **iter**
> return self._execute_and_instances(context)
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
> result = conn.execute(querycontext.statement, self._params)
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
> return meth(self, multiparams, params)
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
> return connection._execute_clauseelement(self, multiparams, params)
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
> ret = self._execute_context(
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
> self._handle_dbapi_exception( File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception util.raise_( File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> raise exception
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> self.dialect.do_execute(
> File "/Users/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
> cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: messages
> [SQL: SELECT messages.id AS messages_id, messages.text AS messages_text, messages.price AS messages_price, messages.paid AS messages_paid, messages.created_at AS messages_created_at
> FROM messages]
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

There should be an empty "messages.db" file, delete it

**Comment by headphonia** [comment]
Had to delete all the database files: "Archived.db", "Messages.db", "Posts.db", and "Stories.db", but it ran smoothly! Thanks!
