### ISSUE TITLE
'db locked' error when scraping names

### ISSUE THREAD

**Issue by sonicshake** [DIGITALCRIMINAL/OnlyFans#680]
Now trying to use latest commit to scrape names (`"scrape_names": true`) but now routinely hitting this error:

> Scrape Processing
Name: paulinajcandy
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Merging new metadata with legacy metadata.
Merging new metadata with old metadata.
Finished processing metadata.
Renaming files.
Traceback (most recent call last):
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
  File "/home/admin/Downloads/projects/OFDS3/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/home/admin/Downloads/projects/OFDS3/datascraper/main_datascraper.py", line 85, in start_datascraper
    x = main_helper.process_names(
  File "/home/admin/Downloads/projects/OFDS3/helpers/main_helper.py", line 521, in process_names
    result = module.start_datascraper(
  File "/home/admin/Downloads/projects/OFDS3/modules/onlyfans.py", line 148, in start_datascraper
    results = prepare_scraper(
  File "/home/admin/Downloads/projects/OFDS3/modules/onlyfans.py", line 681, in prepare_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "/home/admin/Downloads/projects/OFDS3/modules/onlyfans.py", line 564, in process_metadata
    new_metadata_object = ofrenamer.start(
  File "/home/admin/Downloads/projects/OFDS3/extras/OFRenamer/start.py", line 140, in start
    fixed, new_directories = fix_directories(
  File "/home/admin/Downloads/projects/OFDS3/extras/OFRenamer/start.py", line 96, in fix_directories
    pool.starmap(fix_directories, product(
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/admin/Downloads/projects/OFDS3/extras/OFRenamer/start.py", line 92, in fix_directories
    database_session.commit()
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE medias SET filename=? WHERE medias.id = ?]
[parameters: ('2020-12-03-1373400525.jpg', 1373400525)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Using a fresh install of commit (775df64) in a new python venv on linux with an empty target directory, so there are no pre-existing downloads or db files.

**Comment by stayupthetree** [comment]
Running into same issue

**Comment by sonicshake** [comment]
Ctrl-C to leave the script revealed a further exception/traceback as follows:

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/home/admin/Downloads/projects/OFDS3/start_ofd.py", line 52, in <module>
    input()
KeyboardInterrupt
Exception during reset or similar
Traceback (most recent call last):
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 559, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140262718285568 and this is thread id 140263885374080.
Exception closing connection <sqlite3.Connection object at 0x7f9191e227b0>
Traceback (most recent call last):
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 559, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140262718285568 and this is thread id 140263885374080.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/admin/Downloads/.venv/OFDS3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 565, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140262718285568 and this is thread id 140263885374080.

**Comment by DIGITALCRIMINAL** [comment]
Try the latest commit
