### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by thatoneguy206** [DIGITALCRIMINAL/OnlyFans#687]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: messages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GitHub\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\GitHub\OnlyFans\datascraper\main_datascraper.py", line 82, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "C:\GitHub\OnlyFans\modules\onlyfans.py", line 352, in paid_content_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "C:\GitHub\OnlyFans\modules\onlyfans.py", line 556, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "C:\GitHub\OnlyFans\helpers\main_helper.py", line 209, in make_metadata
    x = legacy_database_fixer(database_path, database, database_name)
  File "C:\GitHub\OnlyFans\helpers\main_helper.py", line 162, in legacy_database_fixer
    post_db = result.all()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\query.py", line 3373, in all
    return list(self)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: messages
[SQL: SELECT messages.id AS messages_id, messages.text AS messages_text, messages.price AS messages_price, messages.paid AS messages_paid, messages.created_at AS messages_created_at
FROM messages]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by DIGITALCRIMINAL** [comment]
Delete the empty .db file in metadata

**Comment by thatoneguy206** [comment]
ok, the script made a messages.db in each metadata folder for each model, so I had to run the script multiple times and delete multiple messages.db and now it's working.  thanks!
