### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stories

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#690]
Running the latest commit and getting the following error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 85, in start_datascraper
    x = main_helper.process_names(
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 599, in process_names
    result = module.start_datascraper(
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 148, in start_datascraper
    results = prepare_scraper(
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 683, in prepare_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "C:\Users\user\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 556, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 209, in make_metadata
    x = legacy_database_fixer(database_path, database, database_name)
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 162, in legacy_database_fixer
    post_db = result.all()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3373, in all
    return list(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stories
[SQL: SELECT stories.id AS stories_id, stories.text AS stories_text, stories.price AS stories_price, stories.paid AS stories_paid, stories.created_at AS stories_created_at
FROM stories]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stories

**Comment by DIGITALCRIMINAL** [comment]
Delete the EMPTY -.db file

**Comment by ChillyP** [comment]
Cheers, working again
