### ISSUE TITLE
ValueError: Unexpected character found when decoding 'null'

### ISSUE THREAD

**Issue by hammerheaddf** [DIGITALCRIMINAL/OnlyFans#695]
Running latest commit `54e6cb0` on Raspbian and Python 3.9.
When scraping creator diandrasg:

`Processing metadata.
Merging new metadata with legacy metadata.
Traceback (most recent call last):
  File "/home/myuser/OnlyFans/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/home/myuser/OnlyFans/datascraper/main_datascraper.py", line 87, in start_datascraper
    x = main_helper.process_names(
  File "/home/myuser/OnlyFans/helpers/main_helper.py", line 570, in process_names
    result = module.start_datascraper(
  File "/home/myuser/OnlyFans/modules/onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "/home/myuser/OnlyFans/modules/onlyfans.py", line 680, in prepare_scraper
    old_metadata, delete_metadatas = process_legacy_metadata(
  File "/home/myuser/OnlyFans/modules/onlyfans.py", line 523, in process_legacy_metadata
    old_metadata_set = import_archive(archive_path)
  File "/home/myuser/OnlyFans/helpers/main_helper.py", line 135, in import_archive
    metadata = ujson.load(outfile)
ValueError: Unexpected character found when decoding 'null'`

**Comment by DIGITALCRIMINAL** [comment]
Delete the metadata that's bad
