### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by valdearg** [DIGITALCRIMINAL/OnlyFans#697]
```
Scrape Processing
Name: ribaibu
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Merging new metadata with legacy metadata.
Merging new metadata with old metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 87, in start_datascraper
    x = main_helper.process_names(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 570, in process_names
    result = module.start_datascraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 683, in prepare_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 555, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 252, in make_metadata
    filename=media["filename"], created_at=date_object).first()
KeyError: 'filename'
```
![image](https://user-images.githubusercontent.com/2789033/104108700-aaef3780-52be-11eb-8c1d-0a50f54cb350.png)

Not too sure if it's the journal file maybe?

**Comment by DIGITALCRIMINAL** [comment]
It's nothing to do with that, I'll fix it on my end.

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit, thanks
