### ISSUE TITLE
'NoneType' is not iterable - When using ignored_keywords

### ISSUE THREAD

**Issue by artyom2035** [DIGITALCRIMINAL/OnlyFans#700]
Running commit [[7e59200]](https://github.com/DIGITALCRIMINAL/OnlyFans/commit/7e59200b57a2fcd996e9d44a7b744408b41b0e39).  Getting this error while scraping a lot of models - not all models though. Only happens if I'm using `ignore_keywords`.  Runs successfully if I clear `ignored_keywords`.

 ```
Scrape Processing
Name: genericparadise
Type: Profile
Type: Stories
Scrape Attempt: 1/100
Found: Stories
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "/app/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/app/datascraper/main_datascraper.py", line 87, in start_datascraper
    x = main_helper.process_names(
  File "/app/helpers/main_helper.py", line 570, in process_names
    result = module.start_datascraper(
  File "/app/modules/onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "/app/modules/onlyfans.py", line 668, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/app/modules/onlyfans.py", line 953, in media_scraper
    matches = [s for s in ignored_keywords if s in final_text]
  File "/app/modules/onlyfans.py", line 953, in <listcomp>
    matches = [s for s in ignored_keywords if s in final_text]
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by DIGITALCRIMINAL** [comment]
Thanks, download latest commit
