### ISSUE TITLE
Rewrited auth.json after exception

### ISSUE THREAD

**Issue by pigger-nidoras** [DIGITALCRIMINAL/OnlyFans#702]
```
(env) [x@x OnlyFans]$ python start_ofd.py 
Site: 0 = onlyfans | x = Exit
0
Session IP: x.x.x.x

Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Traceback (most recent call last):
  File "~/OnlyFans/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "~/OnlyFans/datascraper/main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "~/OnlyFans/modules/onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'


Site: 0 = onlyfans | x = Exit
0
Session IP: x.x.x.x

Traceback (most recent call last):
  File "~/OnlyFans/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "~/OnlyFans/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "~/OnlyFans/helpers/main_helper.py", line 544, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'
```

**Comment by DIGITALCRIMINAL** [comment]
Download the latest release or commit

**Comment by DIGITALCRIMINAL** [comment]
Latest commit has fixed this completely
