### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by valdearg** [DIGITALCRIMINAL/OnlyFans#703]
I swear I've gone completely mad.

```
Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 52, in <module>
    input()
KeyboardInterrupt
```

If I delete the auth.json file it gets created in the format below:

```
{
  "auth": {
    "username": "default",
    "auth_id": "hidden",
    "auth_hash": "hidden",
    "auth_uniq_": "hidden",
    "sess": "hidden",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/88.0.4324.50 Safari\/537.36",
    "support_2fa": true,
    "active": true
  }
}
```

When I actually selected the profile, it seems to get reset to the old auth.json format:

```
{
  "username": "default",
  "auth_id": "hidden",
  "auth_hash": "hidden",
  "auth_uniq_": "hidden",
  "sess": "hidden",
  "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
  "user_agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/88.0.4324.50 Safari\/537.36",
  "support_2fa": true,
  "active": false
}
```

**Comment by DIGITALCRIMINAL** [comment]
Are you using the latest commit

**Comment by sintaxx** [comment]
i'm also having this issue as of today, i've tried the repo and the zip release both

**Comment by valdearg** [comment]
Yes, using the latest commit, Just ran again to be double sure.

```
PS G:\Scripts\OnlyFans> git pull
Already up to date.
```

**Comment by DIGITALCRIMINAL** [comment]
Latest commit has fixed this completely

**Comment by valdearg** [comment]
Sweet, tried that now but doesn't like the auth details. Any verbose options for the auth? It worked fine for ages before so wondering if it's the changes.

I'm not sure at which stage it sets the "active": false, but it happens after I run it.

I tried removing the auth.json file, letting it get created again, then added in the details from a copy of the old auth.json file.

**Comment by DIGITALCRIMINAL** [comment]
There's no extra information except for the one it provides. Your auth details are incorrect so it sets active to false.

**Comment by andradre** [comment]
help im new to this, i have downloaded newest version & followed the instruction but i got this error. and also everytime i reopen auth.json, active is set to false.

![image](https://user-images.githubusercontent.com/77492974/104729127-8d144d80-576a-11eb-85f7-d5a0537822b4.png)
