### ISSUE TITLE
Issue after full automated scrape

### ISSUE THREAD

**Issue by novalokhd** [DIGITALCRIMINAL/OnlyFans#707]
so setup my settings correctly... ran through a full scrape..... but now everytime i try to rerun to scrape new content i receive  the following error about 10 seconds after starting script

```
Name: USERNAMEREDACTED
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Archived
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Type: Messages
Traceback (most recent call last):
  File "D:\OF\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OF\datascraper\main_datascraper.py", line 88, in start_datascraper
    x = main_helper.process_names(
  File "D:\OF\helpers\main_helper.py", line 582, in process_names
    result = module.start_datascraper(
  File "D:\OF\modules\onlyfans.py", line 149, in start_datascraper
    results = prepare_scraper(
  File "D:\OF\modules\onlyfans.py", line 652, in prepare_scraper
    unrefined_set2 = process_mass_messages(api,
  File "D:\OF\modules\onlyfans.py", line 406, in process_mass_messages
    chats = import_archive(chats_path)
  File "D:\OF\helpers\main_helper.py", line 135, in import_archive
    metadata = ujson.load(outfile)
ValueError: Expected object or value
```

**Comment by DIGITALCRIMINAL** [comment]
Backup Chats.json in the metadata folder and then delete the original

**Comment by novalokhd** [comment]
> Backup Chats.json in the metadata folder and then delete the original Chats.json

Looks like that fixed it ... Thank you
