### ISSUE TITLE
Webhook Issue

### ISSUE THREAD

**Issue by novalokhd** [DIGITALCRIMINAL/OnlyFans#709]
I've created the webhook for a channel in my discord server..  put the url in the settings.json.... but receive an error when it finishes up a model and hangss here

`Traceback (most recent call last):
  File "D:\OF\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OF\datascraper\main_datascraper.py", line 92, in start_datascraper
    x = main_helper.process_webhooks(apis)
  File "D:\OF\helpers\main_helper.py", line 604, in process_webhooks
    send_webhook(subscription)
  File "D:\OF\helpers\main_helper.py", line 674, in send_webhook
    x = requests.post(webhook_link, json=message)
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\noval\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'd': No schema supplied. Perhaps you meant http://d?`

i tried with https & http not sure if webhooks are having issues or if this a bug currently. or maybe im formatting it wrong in the config

**Comment by DIGITALCRIMINAL** [comment]
You just have to copy and paste the discord server webhook into the script, that's all you have to do.

**Comment by novalokhd** [comment]
Had to do with formatting fixed it
