### ISSUE TITLE
start_datascraper error

### ISSUE THREAD

**Issue by olivechicago** [DIGITALCRIMINAL/OnlyFans#710]
This just started a few hours ago.  Updated to the latest release and it persists

Traceback (most recent call last):
  File "D:\ExePrograms\onlyfans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\ExePrograms\onlyfans\datascraper\main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "D:\ExePrograms\onlyfans\helpers\main_helper.py", line 549, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Unexpected character in found when decoding object value

**Comment by oferchen** [comment]
I had something similar. It turns out that the JSON in the metadata folder was of invalid structure so I deleted it and I never saw the issue again. I'm assuming that check for the validity of the JSON before continuing is possible.

**Comment by DIGITALCRIMINAL** [comment]
It was a mistake in an earlier commit, you have to delete the username's json file in .profiles.
