### ISSUE TITLE
v6.2.3 doen't load from a fresh download

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINAL/OnlyFans#716]
Opening start_ofd.py does not load from a fresh download.

> C:\Users\X\Desktop\OnlyFans-6.2.3>start_ofd.py
Traceback (most recent call last):
  File "C:\Users\XDesktop\OnlyFans-6.2.3\start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "C:\Users\X\Desktop\OnlyFans-6.2.3\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\X\Desktop\OnlyFans-6.2.3\helpers\main_helper.py", line 5, in <module>
    from sqlalchemy.ext.declarative import api
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by headphonia** [comment]
I think you need to run the requirements command again to get the sqlalchemy module.

pip install -r requirements.txt

**Comment by goodboi69** [comment]
Correct. Thanks.
