### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by deadcode0815** [DIGITALCRIMINAL/OnlyFans#719]
Site: 0 = onlyfans | x = Exit
0
Traceback (most recent call last):
  File "E:\OnlyFans-6.2.3\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-6.2.3\datascraper\main_datascraper.py", line 36, in start_datascraper
    original_sessions = api_helper.create_session(
  File "E:\OnlyFans-6.2.3\apis\api_helper.py", line 137, in create_session
    session = test_session()
  File "E:\OnlyFans-6.2.3\apis\api_helper.py", line 120, in test_session
    print("Proxy Not Set: "+proxy+"\n")
TypeError: can only concatenate str (not "NoneType") to str

I know this issue is alredy mentioned here https://github.com/DIGITALCRIMINAL/OnlyFans/issues/717 ,but I get the same error since today. I double checked (triple checked and more) the cookie data. It is not the first time for me setting up this nice scraper, but since today I can't get it to work. I also downloaded latest release (again) I did a new installation

**Comment by deadcode0815** [comment]
its working right now without changing anything. had similiar issue with cursebreaker. seems like a problem with some cloude service.
