### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by Kosmatik** [DIGITALCRIMINAL/OnlyFans#727]
Maybe a scrape issue rather then auth?
Getting an error, same error on both the current git commit and 6.2.3 release.
Python 3.9.1 and 3.9.0 Win 10 x64.

```
Site: 0 = onlyfans | x = Exit
0
Traceback (most recent call last):
  File "\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "\OnlyFans\datascraper\main_datascraper.py", line 36, in start_datascraper
    original_sessions = api_helper.create_session(
  File "\OnlyFans\apis\api_helper.py", line 137, in create_session
    session = test_session()
  File "\apis\api_helper.py", line 120, in test_session
    print("Proxy Not Set: "+proxy+"\n")
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Kosmatik** [comment]
Latest commit:

```
OnlyFans\default\auth.json has been created. Fill in the relevant details and then press enter to continue.
Site: 0 = onlyfans | x = Exit
0
Proxy Not Set: None

Unable to create session
Pausing scraper for 0 seconds.
```

**Comment by DIGITALCRIMINAL** [comment]
Can't do anything unless I have your account details.

**Comment by Kosmatik** [comment]
Figured it out, pihole was blocking checkip.amazonaws.com. Maybe use an alternative if that one's down or blocked?

**Comment by DIGITALCRIMINAL** [comment]
It never goes down
