### ISSUE TITLE
(sqlite3.OperationalError) database is locked 

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINAL/OnlyFans#738]
Hi, I am using the latest commit 86f32f7. When running I get the following traceback error:

<details><summary>Traceback log</summary>
<p>

```bash
Site: 0 = onlyfans | x = Exit
0
Session IP: XXXX

Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome XXXX
Scraping Paid Content
Scraping - XXXX
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/shares/w/tools/OnlyFans/./start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/mnt/shares/w/tools/OnlyFans/datascraper/main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "/mnt/shares/w/tools/OnlyFans/modules/onlyfans.py", line 350, in paid_content_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "/mnt/shares/w/tools/OnlyFans/modules/onlyfans.py", line 554, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "/mnt/shares/w/tools/OnlyFans/helpers/main_helper.py", line 225, in export_sqlite
    db_helper.run_migrations(alembic_location, database_path)
  File "/mnt/shares/w/tools/OnlyFans/helpers/db_helper.py", line 39, in run_migrations
    x = command.upgrade(alembic_cfg, 'head')
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/script/base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/shares/w/tools/OnlyFans/database/databases/messages/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/mnt/shares/w/tools/OnlyFans/database/databases/messages/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/migration.py", line 544, in run_migrations
    self._ensure_version_table()
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/migration.py", line 485, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 925, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

^CTraceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/shares/w/tools/OnlyFans/./start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/mnt/shares/w/tools/OnlyFans/datascraper/main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "/mnt/shares/w/tools/OnlyFans/modules/onlyfans.py", line 350, in paid_content_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "/mnt/shares/w/tools/OnlyFans/modules/onlyfans.py", line 554, in process_metadata
    Session, api_type, folder = main_helper.export_sqlite(
  File "/mnt/shares/w/tools/OnlyFans/helpers/main_helper.py", line 225, in export_sqlite
    db_helper.run_migrations(alembic_location, database_path)
  File "/mnt/shares/w/tools/OnlyFans/helpers/db_helper.py", line 39, in run_migrations
    x = command.upgrade(alembic_cfg, 'head')
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/script/base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/shares/w/tools/OnlyFans/database/databases/messages/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/mnt/shares/w/tools/OnlyFans/database/databases/messages/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/migration.py", line 544, in run_migrations
    self._ensure_version_table()
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/alembic/runtime/migration.py", line 485, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 925, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/shares/w/tools/OnlyFans/./start_ofd.py", line 52, in <module>
    input()
KeyboardInterrupt
```

</p>
</details>

I am using Python 3.9.0 and Ubuntu 20.04

**Comment by DIGITALCRIMINAL** [comment]
Does this happen repeatedly?

**Comment by sideloading** [comment]
Yeah, this happens on every run so I'm unable to scrape any pages.

**Comment by sjfer** [comment]
I think I saw you comment on the issue I raised about a DB locked message. The issue I had was because one of the user folder's permissions was not the script was running as. Have you checked this? You could `chmod -r user:group /path/to/folder ` if you're a linux user.

**Comment by sideloading** [comment]
Running an `ls -la` shows no discrepancies with the permissions of the files. Something I noticed is it has created a single file on the first run `/OnlyFans/.sites/OnlyFans/ARTIST1/Metadata/Messages.db`, but nothing else after crash/re-running. 

@DIGITALCRIMINAL I found the issue. The location of the project was in a SMB mapped location (`/mnt/shares/w/tools/OnlyFans/`). When I move it into a local directory of the Linux box it works. Weird behaviour :[ I'll be using 6.1.2 for the time being.

**Comment by artyom2035** [comment]
Can confirm that it's a CIFS/SMB permission issue.  Used to use a Pi to download to a NAS via CIFS mounts, which worked.  Then started getting this same error after metadata was switched to db. Changed my mounts to NFS(v3), which has no permissions, and the script worked again. Also tested with chmod 777 on the CIFS mount, which also worked.

FWIW, I tried switching to a docker container directly on the NAS to avoid having to have wide-open permissions. This works partially but unfortunately that introduced a new problem where the container always fails mid scrape with "status code 139". Research indicates that Docker has some issues with databases and a SigSegV memory access violation. Status code 139 is apparently a SigSegV or a segmentation fault

**Comment by DIGITALCRIMINAL** [comment]
I have Linux but I know very little about the file structure path and permissions so I wouldn't know where to start, sorry

**Comment by EleRas** [comment]
sqlite3 doesn't work on NFS or SMB - mounts, since those have file-locking which doesn't work for sqlite3: https://sqlite.org/faq.html#q5

**Comment by sideloading** [comment]
There was a comment here that was deleted, but something to do with SMB/CIFS mounts. I guess there's some incompatibility/or some extra configuration for it to work. I'll close the issue since it works outside of this.

**Comment by madsprite** [comment]
I have solved this. add the nolock argument to your fstab cifs args.

`uid=0,credentials=/home/user/.smb,iocharset=utf8,vers=3.0,noperm,nolock`

**Comment by sintaxx** [comment]
i'm using NFS but apparently SQLite really hates networked filesystems
