### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINAL/OnlyFans#744]
script has been working fine up until this morning where i get the following error
username, auth_id, sess, and app_taken are still correct in the auth.json.

auth_hash and auth_uniq are blank - but they were blank when it was working.
the cookie string when inspecting the header doesn't have auth_hash.

```
Choose Profile
Names: Username = username  |  0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Traceback (most recent call last):
  File "C:\of\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\of\datascraper\main_datascraper.py", line 85, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "C:\of\modules\onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'

```

**Comment by chidi9901** [comment]
Check your user-agent again and update it. That fixed it. Or just go through the auth.json file again.

**Comment by chenks** [comment]
that sorted it.
i guess my local browser had a version update which meant the agent needed changed in the config file?

**Comment by DIGITALCRIMINAL** [comment]
Fixed
