### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by calamarket** [DIGITALCRIMINAL/OnlyFans#76]
Hey, I'm having an issue with the script. Every time it tries to download a file, I get a FileNotFoundError: [Errno 2] No such file or directory error and the program stops executing. 

It can (most of the time) get subscriptions but it always runs into that error when downloading files

**Comment by monkjew** [comment]
Traceback (most recent call last):
  File "C:\Users\Name\Desktop\OnlyFans-master\StartDatascraper.py", line 109, in <module>
    x.download_media(*arg)
  File "C:\Users\Name\Desktop\OnlyFans-master\modules\onlyfans.py", line 276, in download_media
    pool.starmap(download, product(
  File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Name\Desktop\OnlyFans-master\modules\onlyfans.py", line 261, in download
    with open(directory, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '::27668438-72E96DE1-40F8-43F8-A2C5-463058A97406.jpeg'

**Comment by DIGITALCRIMINAL** [comment]
Don't use the latest commit, just use the latest release

**Comment by monkjew** [comment]
> Don't use the latest commit, just use the latest release

Sorry I'm super new to this. How do you do that? I'm not sure what that means

**Comment by calamarket** [comment]
Used the newest release and it resolved the issue for me, thanks! Sometimes forget there's a release tab on here lol
