### ISSUE TITLE
Issues starting scraper

### ISSUE THREAD

**Issue by anoeks** [DIGITALCRIMINAL/OnlyFans#760]
After install can't seem to get it to start, I've install requirements on the newest update, after trying to use start_ofd.oy it doesn't install settings.

If i double click on start_ofd.py it automatically closes after a millisecond of opening CMD. 

`C:\Users\XXXX\Downloads\OnlyFans-master` (6)\OnlyFans-master>python start_ofd.py
Execute the script with Python 3.9
Press enter to continue

C:\Users\XXXX\Downloads\OnlyFans-master `(6)\OnlyFans-master>`

**Comment by anoeks** [comment]
Managed to install profiles and settings via Docker. Having trackback issues now. 


> Site: 0 = onlyfans | x = Exit
0
 Session IP: XX.X.XX.XXX
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/usr/src/app/helpers/main_helper.py", line 569, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Unexpected character in found when decoding object value
