### ISSUE TITLE
KeyError: 'size' (using v3.7.2)

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#764]
I just updated to v3.7.2 and had to reset my settings. It had been a while since I update and everything was way different from the previous version I was using. Nevertheless, I inputted the information into their spots listed in config and ran it and immediately hit this key error. Not sure what I'm missing and/or doing wrong. Here's the traceback:

Traceback (most recent call last):
  File "/media/sdw1/holonet81/./OnlyFans/StartDatascraper.py", line 150, in <module>
    result = x.start_datascraper(
  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 56, in start_datascraper
    results = media_scraper(
  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 304, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "/media/sdw1/holonet81/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/media/sdw1/holonet81/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/media/sdw1/holonet81/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/media/sdw1/holonet81/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/sdw1/holonet81/OnlyFans/modules/onlyfans.py", line 215, in scrape_array
    size = source["size"]
KeyError: 'size'

**Comment by ElusiveZatchmo** [comment]
Please disregard, this wasn't the latest version. I have no idea how I found that one.
