### ISSUE TITLE
Missing `.profiles/default/auth.json`

### ISSUE THREAD

**Issue by ElusiveZatchmo** [DIGITALCRIMINAL/OnlyFans#765]
I noticed when I installed v6.2.4 that I don't have `.profiles/default/auth.json`

I wasn't sure how to create it on my own since I'm not sure of the formatting it needs to have. Any suggestions? If I run it for the first time. It generates a .settings/config.json, but not .profiles/default/auth.json. I filled out config.json thinking that maybe it would generate it on next run, but no I just get the following traceback:

Traceback (most recent call last):
  File "/media/sdw1/holonet81/OnlyFans/start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "/media/sdw1/holonet81/OnlyFans/tests/main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "/media/sdw1/holonet81/OnlyFans/helpers/main_helper.py", line 455, in get_config
    json_config = json.load(open(config_path))
  File "/media/sdw1/holonet81/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/media/sdw1/holonet81/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/media/sdw1/holonet81/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/media/sdw1/holonet81/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 41 column 24 (char 1147)

Help would be greatly appreciated. Thanks

**Comment by DIGITALCRIMINAL** [comment]
Use the latest commit instead
