### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by YDdraigGoch** [DIGITALCRIMINAL/OnlyFans#78]
Hello there.

I get the error _PermissionError: [Errno 13] Permission denied_. I think it's caused when an emoji or a character that's invalid (like a #) is in the post description and Windows of course can't use those characters when saving a file.

Is it possible for the script to work out if it uses an invalid character and replaces with a space?

**Comment by DIGITALCRIMINAL** [comment]
Do you have the full error?

**Comment by YDdraigGoch** [comment]
Yes it's:
`Traceback (most recent call last):

  File "StartDatascraper.py", line 102, in <module>
    x.download_media(*arg)
  File "C:\Users\\[User]\Downloads\OnlyFans-3.4\modules\onlyfans.py", line 257, in download_media
    pool.starmap(download, product(media_set, [session], [directory], [username]))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\[User]\Downloads\OnlyFans-3.4\modules\onlyfans.py", line 241, in download
    with open(directory, 'wb') as f:
PermissionError: [Errno 13] Permission denied:

This only happens on posts that have emojis or characters like # (for e.g. a lass makes up a trending hashtag).

**Comment by DIGITALCRIMINAL** [comment]
Did you change the file_name_format?

**Comment by YDdraigGoch** [comment]
Yes for OnlyFans I use _{username} - {date} - {text} - {file_name}.{ext}_, so if anything, the problem happens in the {text} part.

I'll reply further after I've had some shut eye. But thanks for responding quickly.

**Comment by DIGITALCRIMINAL** [comment]
Ahh yeah, you're right. I'll sort it out c:

**Comment by DIGITALCRIMINAL** [comment]
@YDdraigGoch Do you still get the error?

**Comment by YDdraigGoch** [comment]
I don't get an error and it looks like the posts that failed have downloaded. So I think it's fixed. Thanks again.
