### ISSUE TITLE
Error when scraping with newest release

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#782]
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "F:\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "F:\OnlyFans\datascraper\main_datascraper.py", line 87, in start_datascraper
    names = main_helper.process_names(
  File "F:\OnlyFans\helpers\main_helper.py", line 602, in process_names
    result = module.start_datascraper(
  File "F:\OnlyFans\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans\modules\onlyfans.py", line 705, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\OnlyFans\modules\onlyfans.py", line 1045, in media_scraper
    file_directory = main_helper.reformat(
  File "F:\OnlyFans\helpers\main_helper.py", line 322, in reformat
    if not prepared_format.preview:
AttributeError: 'prepare_reformat' object has no attribute 'preview'

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit

**Comment by ctrlcmdshft** [comment]
still getting errors on some models and no errors on others 

Scraping [text]. Should take less than a minute.
Traceback (most recent call last):
  File "F:\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "F:\OnlyFans\datascraper\main_datascraper.py", line 87, in start_datascraper
    names = main_helper.process_names(
  File "F:\OnlyFans\helpers\main_helper.py", line 602, in process_names
    result = module.start_datascraper(
  File "F:\OnlyFans\modules\onlyfans.py", line 155, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans\modules\onlyfans.py", line 705, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\OnlyFans\modules\onlyfans.py", line 1044, in media_scraper
    file_directory = main_helper.reformat(
  File "F:\OnlyFans\helpers\main_helper.py", line 322, in reformat
    if not prepared_format.preview:
AttributeError: 'prepare_reformat' object has no attribute 'preview'

**Comment by jimmothy-beep** [comment]
im getting a similar thing on the latest commit

`Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 356, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1044, in media_scraper
    file_directory = main_helper.reformat(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 322, in reformat
    if not prepared_format.preview:
AttributeError: 'prepare_reformat' object has no attribute 'preview'`

**Comment by Arko109** [comment]
Same error on latest master

**Comment by scgreenhalgh** [comment]
running into the same issue with the latest git pull from master.

**Comment by Gamma-Velorum** [comment]
I can repro

Traceback (most recent call last):
  File "Z:\OnlyFans-master\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "Z:\OnlyFans-master\datascraper\main_datascraper.py", line 84, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "Z:\OnlyFans-master\modules\onlyfans.py", line 356, in paid_content_scraper
    new_metadata = media_scraper(paid_content, api,
  File "Z:\OnlyFans-master\modules\onlyfans.py", line 1044, in media_scraper
    file_directory = main_helper.reformat(
  File "Z:\OnlyFans-master\helpers\main_helper.py", line 322, in reformat
    if not prepared_format.preview:
AttributeError: 'prepare_reformat' object has no attribute 'preview'
