### ISSUE TITLE
Bug + Fix: FileExistsError on MacOS Catalina

### ISSUE THREAD

**Issue by bigbluedeer** [DIGITALCRIMINAL/OnlyFans#792]
Hi.
when running the script and after choosing onlyfans, it throws this error:
Traceback (most recent call last):
  File "/Volumes/external drive/OnlyFans-6.3.2/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Volumes/external drive/OnlyFans-6.3.2/datascraper/main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "/Volumes/external drive/OnlyFans-6.3.2/helpers/main_helper.py", line 582, in process_profiles
    export_data(
  File "/Volumes/external drive/OnlyFans-6.3.2/helpers/main_helper.py", line 637, in export_data
    os.makedirs(directory, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Volumes/external drive/OnlyFans-6.3.2/.profiles/OnlyFans/.DS_Store'

fix: 
in /helpers/main_helper.py, line 637
change: matches = ["desktop.ini", ".DS_store", "@eaDir"]
to:          matches = ["desktop.ini", ".DS_store", "@eaDir", ".DS_Store"]
or make it use .lower() of the path names.

i would do a pull, but i dont know how to do that yet and until then, i guess this is the best method

**Comment by DIGITALCRIMINAL** [comment]
Wow lmao, so there's an uppercase store and a lowercase store. Thanks, I'll implement this.
