### ISSUE TITLE
Bug + Fix: NameError on MacOS Catalina

### ISSUE THREAD

**Issue by bigbluedeer** [DIGITALCRIMINAL/OnlyFans#793]
Hi again,
when running the script (after i already fixed the FileExistsError), choosing onlyfans and then the default profile, it throws this error:
Traceback (most recent call last):
  File "/Volumes/external drive/OnlyFans-6.3.2/start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Volumes/external drive/OnlyFans-6.3.2/datascraper/main_datascraper.py", line 60, in start_datascraper
    apis = choose_option(
  File "/Volumes/external drive/OnlyFans-6.3.2/helpers/main_helper.py", line 545, in choose_option
    new_names = [x for x in new_names if not isinstance(x[0], SimpleNamespace)]
  File "/Volumes/external drive/OnlyFans-6.3.2/helpers/main_helper.py", line 545, in <listcomp>
    new_names = [x for x in new_names if not isinstance(x[0], SimpleNamespace)]
NameError: name 'SimpleNamespace' is not defined

fix:
in /helpers/main_helper.py, line 2
add following line: from types import SimpleNamespace

again, till i know how to make pull requests ill just do it this way.

**Comment by DIGITALCRIMINAL** [comment]
> main_helper

It's already there.

**Comment by bigbluedeer** [comment]
Weird. Maybe i acidentally cut the first line while trying to fix the other bug. Sorry
