### ISSUE TITLE
Traceback errors After Auth

### ISSUE THREAD

**Issue by aggiefury101** [DIGITALCRIMINAL/OnlyFans#81]
Hey I'm getting this error:

Traceback (most recent call last):
  File "startDatascraper.py", line 105, in <module>
    result = x.start_datascraper(
  File "/Users/airphource/Desktop/OnlyFans-master/modules/onlyfans.py", line 56, in start_datascraper
    results = media_scraper(session, site_name, only_links, *item[1], api_type)
  File "/Users/airphource/Desktop/OnlyFans-master/modules/onlyfans.py", line 278, in media_scraper
    os.makedirs(directory, exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/sites/'

Any idea what i'm missing? I'm guess I need to manually set the directory.

**Comment by boulara** [comment]
w/ the newest build, I get this error as well.

**Comment by DIGITALCRIMINAL** [comment]
Try creating the sites folder in the onlyfans-master directory or try manually specifying the folder you want to download too.
