### ISSUE TITLE
No module named 'tqdm' after latest git clone

### ISSUE THREAD

**Issue by Aer3x** [DIGITALCRIMINAL/OnlyFans#816]
Traceback (most recent call last):
  File "Z:\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "Z:\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "Z:\OnlyFans-master\helpers\main_helper.py", line 20, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by DIGITALCRIMINAL** [comment]
pip install tqdm
