### ISSUE TITLE
Processing metadata error

### ISSUE THREAD

**Issue by alb-ctrl** [DIGITALCRIMINAL/OnlyFans#826]
I am having an issue like #789 has/had. after successfully login in and everything I am trying to download any type of content (text, images, everything, etc) but the program keeps crashing.
I thought it had to do with the metadata format so I tried downloading in a new folder but I kept getting the same error. I tried today's commit code and the error changed a little bit, it went from 
 File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
to 
AttributeError: 'list' object has no attribute 'valid'
I also tried older version of the repo but still having the same issue 
here is the whole error
Scrape: a = Everything | b = Images | c = Videos | d = Audios | e = Texts
c
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [video | stream | gif]. Should take less than a minute.
Processing metadata.
Traceback (most recent call last):
  File "/Volumes/LaCie/p/OnlyFans-master/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Volumes/LaCie/p/OnlyFans-master/datascraper/main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "/Volumes/LaCie/p/OnlyFans-master/helpers/main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "/Volumes/LaCie/p/OnlyFans-master/modules/onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "/Volumes/LaCie/p/OnlyFans-master/modules/onlyfans.py", line 713, in prepare_scraper
    old_metadata, delete_metadatas = process_legacy_metadata(
  File "/Volumes/LaCie/p/OnlyFans-master/modules/onlyfans.py", line 542, in process_legacy_metadata
    legacy_metadata_object, delete_legacy_metadatas = legacy_metadata_fixer(
  File "/Volumes/LaCie/p/OnlyFans-master/modules/onlyfans.py", line 756, in legacy_metadata_fixer
    legacy_metadata = create_metadata(
  File "/Volumes/LaCie/p/OnlyFans-master/classes/prepare_metadata.py", line 20, in __init__
    self.content = format_content(
  File "/Volumes/LaCie/p/OnlyFans-master/classes/prepare_metadata.py", line 176, in __init__
    setattr(new_item, old_key, new_posts)
AttributeError: 'list' object has no attribute 'valid'

**Comment by alb-ctrl** [comment]
if anyone reads this,
I solved the error by deleting the Metadata folder inside the models folder
