### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by scgreenhalgh** [DIGITALCRIMINAL/OnlyFans#829]
Hi there,

I'm receiving the following error since the latest commit/release 6.4.1

Thanks!

```
Traceback (most recent call last):
  File "/.../start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/.../tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/.../helpers/main_helper.py", line 20, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by SteveJSzabo** [comment]
You need to do an install of the requirements.txt again. You can find those instructions in the readme.

**Comment by ProjektPremium** [comment]
requirements has been updated man.

**Comment by scgreenhalgh** [comment]
Ah, gotcha thanks.
