### ISSUE TITLE
KeyError: 'api_type'

### ISSUE THREAD

**Issue by xImJakeyy** [DIGITALCRIMINAL/OnlyFans#830]
New error on Commit 6.4.1

Could be linked to the KeyError: 'medias' error.

Name: tlmxoo
Type: Profile
0.00B [00:00, ?B/s]
Type: Archived
Scrape Attempt: 1/100
Found: Archived_posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "E:\OnlyFans-master\modules\onlyfans.py", line 699, in prepare_scraper
    unrefined_result = pool.starmap(media_scraper, product(
  File "C:\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\OnlyFans-master\modules\onlyfans.py", line 1076, in media_scraper
    new_media["linked"] = post["api_type"]
KeyError: 'api_type'

**Comment by londontrapstar** [comment]
I've got this error:

Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "OnlyFans-master 3/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "OnlyFans-master 3/datascraper/main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "OnlyFans-master 3/helpers/main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "OnlyFans-master 3/modules/onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "OnlyFans-master 3/modules/onlyfans.py", line 699, in prepare_scraper
    unrefined_result = pool.starmap(media_scraper, product(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "OnlyFans-master 3/modules/onlyfans.py", line 1076, in media_scraper
    new_media["linked"] = post["api_type"]
KeyError: 'api_type'

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit

**Comment by IT6uru** [comment]
It is now throwing:

 File "Z:\OF\OnlyFans-master\modules\onlyfans.py", line 1073, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'

**Comment by IT6uru** [comment]
I take that back, this appears to be a separate issue - KeyError: 'api_type' issue seems to be resolved, as I have been able to scrape another that was throwing it earlier.
