### ISSUE TITLE
Crashes every time on the same person.

### ISSUE THREAD

**Issue by RonnieBlaze** [DIGITALCRIMINAL/OnlyFans#841]
So i have a person that the script crashes on every time i try to scrape the,.. If i blacklist this person the script will run.  I think this is a free profile too.

Scrape Processing
Name: feralperson
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Found: Posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "F:\Users\Ron\Downloads\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "F:\Users\Ron\Downloads\OnlyFans-master\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "F:\Users\Ron\Downloads\OnlyFans-master\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "F:\Users\Ron\Downloads\OnlyFans-master\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "F:\Users\Ron\Downloads\OnlyFans-master\modules\onlyfans.py", line 704, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "F:\Users\Ron\Downloads\OnlyFans-master\modules\onlyfans.py", line 1031, in media_scraper
    matches = [s for s in ignored_keywords if s in final_text]
  File "F:\Users\Ron\Downloads\OnlyFans-master\modules\onlyfans.py", line 1031, in <listcomp>
    matches = [s for s in ignored_keywords if s in final_text]
TypeError: argument of type 'NoneType' is not iterable

**Comment by febo01** [comment]
Had the same issue. Look in your ignore list of There is one that is empty ("") and no ',' at the end of the list

[
"Her",
"her",
"HER" <---- no comma
]
