### ISSUE TITLE
Question - Pip installing to incorrect Python version

### ISSUE THREAD

**Issue by pcjamesy** [DIGITALCRIMINAL/OnlyFans#85]
Firstly thanks for being super responsive here, I seem to be stuck and am having 0 luck with finding the issue. (ubuntu 18.04)

`root@synu:~/OnlyFans# python3.8 StartDatascraper.py
Traceback (most recent call last):
  File "StartDatascraper.py", line 9, in <module>
    import modules.helpers as helpers
  File "/home/james/OnlyFans/modules/helpers.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "StartDatascraper.py", line 9, in <module>
    import modules.helpers as helpers
  File "/home/james/OnlyFans/modules/helpers.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'`

As far as I can tell BeautifulSoup4 is installed. But maybe the issue is that it is installing into the python3.6 folder?

`james@synu:~/OnlyFans$ sudo -H pip3 install BeautifulSoup4
Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.6/dist-packages (from BeautifulSoup4)`

**Comment by DIGITALCRIMINAL** [comment]
Use Python 3.8

**Comment by pcjamesy** [comment]
Got it, thanks for the guidance!

For anyone else who hits this issue I did

python3.8 -m pip install beautifulsoup4

Then new issue about 
`File "StartDatascraper.py", line 9, in <module>
    import modules.helpers as helpers
  File "/home/james/OnlyFans/modules/helpers.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

Fixed with:

python3.8 -m pip install image

**Comment by DIGITALCRIMINAL** [comment]
`python3.8 -m pip install -r requirements.txt`

This will install all the requirements
