### ISSUE TITLE
Module sys has no attribute setcheckinterval

### ISSUE THREAD

**Issue by globalgossamer** [DIGITALCRIMINAL/OnlyFans#851]
When I try to scrape any profile using the latest version and Python 3.92 on windows, I get this error

Type: Profile
Traceback (most recent call last):
  File "D:\OF Scraper\DigitalCriminal Onlyfans\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OF Scraper\DigitalCriminal Onlyfans\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "D:\OF Scraper\DigitalCriminal Onlyfans\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "D:\OF Scraper\DigitalCriminal Onlyfans\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "D:\OF Scraper\DigitalCriminal Onlyfans\modules\onlyfans.py", line 662, in prepare_scraper
    profile_scraper(api, site_name, api_type, username,
  File "D:\OF Scraper\DigitalCriminal Onlyfans\modules\onlyfans.py", line 271, in profile_scraper
    d_session = download_session()
  File "C:\Python39\lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
    cls.monitor = TMonitor(cls, cls.monitor_interval)
  File "C:\Python39\lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
    getattr(sys, 'setcheckinterval'))(100)
AttributeError: module 'sys' has no attribute 'setcheckinterval'

**Comment by legitishan** [comment]
swap sys.setcheckinterval with sys.setswitchinterval().
sys.getcheckinterval() and sys.setcheckinterval() functions have been removed. They were deprecated since Python 3.2. Use sys.getswitchinterval() and sys.setswitchinterval() instead

**Comment by E0911CD45B19686** [comment]
You have a really old version of the `tqdm` library (it was [fixed in 2017](https://github.com/tqdm/tqdm/commit/2189a2b291c1b550fe35f54267d088083b737712)), reinstall your libraries `pip install -r requirements.txt`.

This issue can get closed/moved to discussions.

**Comment by globalgossamer** [comment]
Weird, pip was refusing to update it from 4.11.2 (from 2017) because thats what it had installed locally. I edited my requirements.txt to say tqdm >= 4.57 and re-installed requirements and it worked
