### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by Danzxzx** [DIGITALCRIMINAL/OnlyFans#856]
**Issue:**
When I try scraping a user that I have scraped in the past with a different version of your scraper with the file copied into the .sites folder I get this

`Scrape Attempt: 1/100
Found: Archived_posts
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "\modules\onlyfans.py", line 700, in prepare_scraper
    unrefined_result = pool.starmap(media_scraper, product(
  File "\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "\modules\onlyfans.py", line 1072, in media_scraper
    found_medias = [x for x in post["medias"]
  File "\modules\onlyfans.py", line 1073, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'`

In the past I've been able to copy over the .sites folder with no issue but this latest release it doesn't seem to be possible 

Also would it be possible to make a job/function that only scrapes from a list eg. "favourites" rather than excluding the "blacklist"? 
Otherwise a great bit of code!

**Comment by jeff-geoff** [comment]
I get this on a fresh install as well.


Traceback (most recent call last):
  File "/root/OnlyFans-master/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/root/OnlyFans-master/datascraper/main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "/root/OnlyFans-master/helpers/main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "/root/OnlyFans-master/modules/onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "/root/OnlyFans-master/modules/onlyfans.py", line 705, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/OnlyFans-master/modules/onlyfans.py", line 1075, in media_scraper
    found_medias = [x for x in medias
  File "/root/OnlyFans-master/modules/onlyfans.py", line 1076, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'

**Comment by Aer3x** [comment]
same issue here.

with scrape_paid_content on false it seems to skip it on some profiles but later on i still get the error.

**Comment by DIGITALCRIMINAL** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/835
