### ISSUE TITLE
Need help with error

### ISSUE THREAD

**Issue by Nido21100** [DIGITALCRIMINAL/OnlyFans#884]
Hi, just updated to the new version but every time I try to pull from a source it come up with the follower error :=

Traceback (most recent call last):
  File "T:\OF\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "T:\OF\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "T:\OF\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "T:\OF\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "T:\OF\modules\onlyfans.py", line 705, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Omega Gaming\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "T:\OF\modules\onlyfans.py", line 1075, in media_scraper
    found_medias = [x for x in medias
  File "T:\OF\modules\onlyfans.py", line 1076, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'

Anyone have any ideas on how to resolve thie?

**Comment by lEtranger1942** [comment]
check this thread. You have to edit the file manually

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/868
