### ISSUE TITLE
Gets only 3 usernames to scrape, fails to scrape

### ISSUE THREAD

**Issue by pmkz** [DIGITALCRIMINAL/OnlyFans#888]
Seem to make it past authentication and then hit this issue after it lists 3 usernames:

Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "C:\Users\matth\Downloads\OnlyFans-master\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\matth\Downloads\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 95, in start_datascraper
    paid_content = module.paid_content_scraper(apis, identifiers)
  File "C:\Users\matth\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 353, in paid_content_scraper
    unrefined_set = media_scraper(paid_content, api, subscription,
  File "C:\Users\matth\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 1075, in media_scraper
    found_medias = [x for x in medias
  File "C:\Users\matth\Downloads\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 1076, in <listcomp>
    if x["filename"] == new_media["filename"]]
KeyError: 'filename'

I have more usernames than that followed.  I've run requirements and have no issues, updated python and visualbasic, still not sure what's going on.  It seems to authenticate OK before that too because it lists accounts I do follow.

**Comment by lEtranger1942** [comment]
check this thread https://github.com/DIGITALCRIMINAL/OnlyFans/issues/868. You have to edit the file manually 

Also check this pull request - https://github.com/DIGITALCRIMINAL/OnlyFans/pull/867

**Comment by pmkz** [comment]
Issued fixed with #867
