### ISSUE TITLE
KeyError: 'medias'

### ISSUE THREAD

**Issue by formulabaritone** [DIGITALCRIMINAL/OnlyFans#892]
Just updated to 6.4.1 and have similar issue to others but with different KeyError:

Traceback (most recent call last):
  File "E:\OnlyFans-6.4.1\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "E:\OnlyFans-6.4.1\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "E:\OnlyFans-6.4.1\helpers\main_helper.py", line 625, in process_names
    result = module.start_datascraper(
  File "E:\OnlyFans-6.4.1\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "E:\OnlyFans-6.4.1\modules\onlyfans.py", line 704, in prepare_scraper
    unrefined_set = pool.starmap(media_scraper, product(
  File "C:\Users\lms0418\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\lms0418\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\lms0418\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lms0418\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\OnlyFans-6.4.1\modules\onlyfans.py", line 1071, in media_scraper
    found_medias = [x for x in post["medias"]
KeyError: 'medias'

I'm a complete newb so is there any simple way for someone with no coding experience to fix this? Don't even know how to edit a .py file or whatever the terminology is.

**Comment by lEtranger1942** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/835 check this and edit the .py file manually. It will work after
