### ISSUE TITLE
Receiving this error when running start_ofd.py (Clean New Setup)

### ISSUE THREAD

**Issue by KrypticKodi** [DIGITALCRIMINAL/OnlyFans#918]
Traceback (most recent call last):
  File "D:\OF3\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OF3\datascraper\main_datascraper.py", line 98, in start_datascraper
    names = main_helper.process_names(
  File "D:\OF3\helpers\main_helper.py", line 631, in process_names
    result = module.start_datascraper(
  File "D:\OF3\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "D:\OF3\modules\onlyfans.py", line 687, in prepare_scraper
    unrefined_set2 = process_mass_messages(api,
  File "D:\OF3\modules\onlyfans.py", line 418, in process_mass_messages
    chats = import_archive(chats_path)
  File "D:\OF3\helpers\main_helper.py", line 138, in import_archive
    metadata = ujson.load(outfile)
ValueError: Expected object or value

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit

**Comment by Gamma-Velorum** [comment]
Having the same problem with the latest commit

`Name: miamalkova | Type: Posts | Count: 592 Videos | Directory: O:\OnlyFans-master\.sites

0it [00:00, ?it/s]Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 100, in start_datascraper
    x = main_helper.process_downloads(apis, module)
  File "O:\OnlyFans-master\helpers\main_helper.py", line 642, in process_downloads
    module.download_media(api, subscription)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 1154, in __init__
    pool.starmap(self.prepare_download, product(
  File "C:\Users\No\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\No\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\No\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\No\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "O:\OnlyFans-master\modules\onlyfans.py", line 1208, in prepare_download
    unrefined_set = media_scraper(result_list, api, subscription,
  File "O:\OnlyFans-master\modules\onlyfans.py", line 926, in media_scraper
    post_id = media_api["id"]
KeyError: 'id'`

**Comment by DIGITALCRIMINAL** [comment]
That's not the same problem.
