### ISSUE TITLE
Keyerror 'email'

### ISSUE THREAD

**Issue by JordyUSA** [DIGITALCRIMINAL/OnlyFans#921]
Traceback (most recent call last):
  File "/run/media/jord/996cac65-f615-45e3-99ae-579cc18556cf/git/OnlyFans/start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/run/media/jord/996cac65-f615-45e3-99ae-579cc18556cf/git/OnlyFans/datascraper/main_datascraper.py", line 60, in start_datascraper
    apis = main_helper.process_profiles(
  File "/run/media/jord/996cac65-f615-45e3-99ae-579cc18556cf/git/OnlyFans/helpers/main_helper.py", line 607, in process_profiles
    api.set_auth_details(
  File "/run/media/jord/996cac65-f615-45e3-99ae-579cc18556cf/git/OnlyFans/apis/onlyfans/onlyfans.py", line 533, in set_auth_details
    self.auth.auth_details.email = option["email"]
KeyError: 'email'

**Comment by nepobef** [comment]
Looks like there has been some changes to auth.json (possibly to automate getting the auth_id and sess values).
It is looking for certain keypairs in auth.json and not finding them and erroring out.

You need to add:
`"email":"",
"password:""`

into your auth.json file. If your auth is correct it will not try and use them and you can scrape as normal, otherwise it prompts you for geckodriver, I suspect so it can pilot a browser and use those fields to login for you.

**Comment by DIGITALCRIMINAL** [comment]
The script should automatically add email and password to it .-.

**Comment by DIGITALCRIMINAL** [comment]
Andddd it isn't. I will fix it.

**Comment by DIGITALCRIMINAL** [comment]
Use latest commit, thanks.
