### ISSUE TITLE
Different Indentation Error

### ISSUE THREAD

**Issue by nappyapp** [DIGITALCRIMINAL/OnlyFans#923]
With the latest commit:

```
Traceback (most recent call last):
  File "/mnt/vdata/.fstor/of/./start_ofd.py", line 14, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "/mnt/vdata/.fstor/of/datascraper/main_datascraper.py", line 11, in <module>
    import modules.onlyfans as m_onlyfans
  File "/mnt/vdata/.fstor/of/modules/onlyfans.py", line 112
    elif api.auth.auth_details.email and api.auth.auth_details.password and json_settings["browser"]["auth"]:
    ^
IndentationError: expected an indented block
```

The issue is here, just delete line 111:

```
111:     elif api.auth.auth_details.email and api.auth.auth_details.password:
112:     elif api.auth.auth_details.email and api.auth.auth_details.password and json_settings["browser"]["auth"]:
113:         proxy = None
  ```

**Comment by DIGITALCRIMINAL** [comment]
:/ Fixed
