### ISSUE TITLE
Error when I write python start_ofd.py

### ISSUE THREAD

**Issue by Bezpes** [DIGITALCRIMINAL/OnlyFans#928]
C:\Users\kedif\Desktop\OnlyFans-5.3>python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\kedif\Desktop\OnlyFans-5.3\start_ofd.py", line 5, in <module>
    main_test.check_config()
  File "C:\Users\kedif\Desktop\OnlyFans-5.3\tests\main_test.py", line 19, in check_config
    for key, value in json_config["settings"].items():
KeyError: 'settings'

**Comment by DIGITALCRIMINAL** [comment]
> 5.3

lol
