### ISSUE TITLE
ModuleNotFoundError: deepdiff

### ISSUE THREAD

**Issue by el-gringo-alto** [DIGITALCRIMINAL/OnlyFans#929]
I'm using Python 3.9.0 on Windows 10.

When I try to run `python start_ofd.py`, I get:

```
Traceback (most recent call last):
  File "E:\code\OnlyFans\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "E:\code\OnlyFans\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "E:\code\OnlyFans\helpers\main_helper.py", line 4, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'
```
When I run `pip install deepdiff`, I get:
```
Requirement already satisfied: deepdiff in e:\code\onlyfans\env\lib\site-packages (5.2.3)
Requirement already satisfied: ordered-set==4.0.2 in e:\code\onlyfans\env\lib\site-packages (from deepdiff) (4.0.2)
```

I've tried looking through past issues on problem and couldn't get a straight answer from it. I've also install all C++ build tools and still get the same result.

**Comment by DIGITALCRIMINAL** [comment]
You most likely have multiple python installed

**Comment by el-gringo-alto** [comment]
I only have Python 3.9.0 installed.

**Comment by DIGITALCRIMINAL** [comment]
I dunno then

**Comment by el-gringo-alto** [comment]
I was able to get it to work by not running it in a virtual environment.
