### ISSUE TITLE
ModuleNotFoundError: No module named 'user_agent'

### ISSUE THREAD

**Issue by oferchen** [DIGITALCRIMINAL/OnlyFans#938]
Traceback (most recent call last):
  File "/OnlyFans/start_ofd.py", line 14, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "/OnlyFans/datascraper/main_datascraper.py", line 11, in <module>
    import modules.onlyfans as m_onlyfans
  File "/OnlyFans/modules/onlyfans.py", line 31, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "/OnlyFans/extras/OFLogin/start_ofl.py", line 6, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

**Comment by oferchen** [comment]
got it from https://pypi.org/project/user_agent/

**Comment by nutechmobile** [comment]
broken again:
No module named 'ultima_scraper_collection'
