### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by Luke-L** [DIGITALCRIMINAL/OnlyFans#939]
cool project, thanks for taking the time to do this, but...

Traceback (most recent call last):
  File "C:\Users\games\Downloads\OnlyFans-6.3.1\OnlyFans-6.3.1\start_ofd.py", line 9, in <module>
    main_test.check_config()
  File "C:\Users\games\Downloads\OnlyFans-6.3.1\OnlyFans-6.3.1\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\games\Downloads\OnlyFans-6.3.1\OnlyFans-6.3.1\helpers\main_helper.py", line 5, in <module>
    from sqlalchemy.ext.declarative import api
ImportError: cannot import name 'api' from 'sqlalchemy.ext.declarative' (C:\Users\games\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sqlalchemy\ext\declarative\__init__.py)

(yes i have python and pip install requirements)

**Comment by headphonia** [comment]
i think it's related to this #933

**Comment by DIGITALCRIMINAL** [comment]
Use

https://github.com/DIGITALCRIMINAL/OnlyFans/releases/tag/v6.4.3
