### ISSUE TITLE
Help me with the following error

### ISSUE THREAD

**Issue by sgaurav510** [DIGITALCRIMINAL/OnlyFans#943]
C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3>python start_ofd.py
LEGACY CONFIG FOUND, BACKING IT UP AND CREATING A NEW ONE. (C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\.settings\config_backup.json)
Traceback (most recent call last):
  File "C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\helpers\main_helper.py", line 494, in get_config
    json_config, string = make_settings.fix(json_config)
  File "C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\classes\make_settings.py", line 104, in fix
    c = x.check_unique()
  File "C:\Users\sgaur\Downloads\OnlyFans-6.4.3\OnlyFans-6.4.3\classes\prepare_metadata.py", line 321, in check_unique
    value = os.path.normpath(value)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by DIGITALCRIMINAL** [comment]
Delete old config.
