### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by dballs6666** [DIGITALCRIMINAL/OnlyFans#947]
Choose Profile
Names: Username = username  |  0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "G:\OnlyFans-master\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\OnlyFans-master\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "G:\OnlyFans-master\modules\onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "G:\OnlyFans-master\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "G:\OnlyFans-master\extras\OFLogin\start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'

**Comment by secretiveolwagner** [comment]
#945
