### ISSUE TITLE
Setting up webhooks

### ISSUE THREAD

**Issue by ChillyP** [DIGITALCRIMINAL/OnlyFans#965]
Hey,

Wondering if you can assist, trying to setup webbooks and I've added what I think the discord server webhook (for example is 123456789012345678) into my config file, but when I run the script it gets to the end and then I get the following. I've tried adding in the full URL and many other permutations but still no success... am I missing something? 

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\OnlyFans\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\user\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 102, in start_datascraper
    x = main_helper.process_webhooks(apis)
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 654, in process_webhooks
    send_webhook(subscription)
  File "C:\Users\user\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 741, in send_webhook
    x = requests.post(webhook_link, json=message)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '123456789012345678': No schema supplied. Perhaps you meant http://123456789012345678?

**Comment by DIGITALCRIMINAL** [comment]
That's not the correct url. You just have to google search Discord webhooks.

**Comment by ChillyP** [comment]
Thanks got it working just a formatting error, I missed off putting the url in quotation marks.
